/*
	*** Command Function Definitions
	*** src/command/commands.cpp
	Copyright T. Youngs 2007-2009

	This file is part of Aten.

	Aten is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	Aten is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with Aten.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "command/commands.h"
#include "parser/commandnode.h"
#include "main/aten.h"
#include "base/bundle.h"
#include "parser/tree.h"

// Static singletom
Command commands;

/* Argument Specification Tokens:
       Char	Meaning		Acceptable Types in VTypes
	N	Number		IntegerData, DoubleData
	I	Integer		IntegerData
	R	Real		DoubleData
	C	Character	StringData
	S	Any Simple	IntegerData, DoubleData, StringData
	U	Vector		VectorData
	B	Boolean		Any
	A	Atom/Id		IntegerData, AtomData
	M	Model/ID/Name	ModelData, StringData, IntegerData
	F	Frcefld/ID/Name	ForcefieldData, IntegerData, StringData
	P	Pattern/ID/Name	PatternData, StringData, IntegerData
	G	Grid/ID		GridData, StringData, IntegerData
	X	Pointer		Any pointer object
	V	Variable	Any simple variable (not path)
	Z	Any		Any
	*	<Repeat>	Any number of the last type again
	^	<Require Var>	Next token must be a modifiable variable and not a constant
	[]	<Cluster>	Surrounds groups of optional arguments that must be specified together
	|	<Or>		Separates alternative lists of arguments for the command
	&	<Array>		Next token must be an array
	/	<type Or>	Specifies an argument may be one of two types
	2-9	<NRepeat>	Next argument should occur N times
*/

// Command action
CommandData Command::data[Command::nCommands] = {

	// AST Nodes
	{ "_nofunction",	"",		"", VTypes::NoData,
				"" },
	{ "_joiner",		"",		"", VTypes::NoData,
				"" },
	{ "_declaration",	"^Z*",		"", VTypes::NoData,
				"" },

	// Analysis commands
	{ "finalise",		"",		"", VTypes::NoData,
				"Finalise all calculated quantities" },
	{ "frameanalyse",	"",		"", VTypes::NoData,
				"Analyse quantities for the current trajectory frame" },
	{ "geometry",		"CNNNCNNnn",	"<name> <min> <binwidth> <nbins> <filename> <site1> <site2> [site3 [site4]]", VTypes::NoData,
				"Calculate geometries" },
	{ "modelanalyse",	"",		"", VTypes::NoData,
				"Analyse quantities for the current model" },
	{ "pdens",		"CNNCNN",	"<name> <griddelta> <nsteps> <filename> <site1> <site2> ", VTypes::NoData,
				"Request calculation of a probability density between sites" },
	{ "listjobs",		"",		"", VTypes::NoData,
				"Print the current list of quantities to calculate" },
	{ "rdf",		"CNNNCNN",	"<name> <rmin> <binwidth> <nbins> <filename> <site1> <site2>", VTypes::NoData,
				"Request calculation of radial distribution function between sites" },
	{ "savequantities",	"",		"", VTypes::NoData,
				"Save calculated quantities to file" },
	{ "trajanalyse",	"NNn",		"<startframe> <frameskip> [nframes]", VTypes::NoData,
				"Analyse quantities for all frames in current trajectory" },
	
	// Atom commands
	{ "atomstyle",		"Ca",		"<style> [atom/id]", VTypes::NoData,
				"Set the individual style of the current atom selection (or supplied atom)" },
	{ "getatom",		"N",		"<id>", VTypes::AtomData,
				"Retrieve pointer for atom id specified, returning a reference to it" },
	{ "hide",		"a",		"[atom/id]", VTypes::NoData,
				"Hide the current selection of atoms (or supplied atom)" },
	{ "setcharge",		"Na",		"<q> [atom/id]", VTypes::NoData,
				"Set the charge of the current (or specified) atom" },
	{ "setcoords",		"NNNa",		"<x> <y> <z> [atom/id]", VTypes::NoData,
				"Set the coordinates of the current (or specified) atom" },
	{ "setelement",		"Ga",		"<element> [atom/id]", VTypes::NoData,
				"Set the element of the current (or specified) atom" },
	{ "setforces",		"NNNa",		"<fx> <fy> <fz> [atom/id]", VTypes::NoData,
				"Set the forces of the current (or specified) atom" },
	{ "setfx",		"Na",		"<fx> [atom/id]", VTypes::NoData,
				"Set the x force of the current (or specified) atom" },
	{ "setfy",		"Na",		"<fy> [atom/id]", VTypes::NoData,
				"Set the y force of the current (or specified) atom" },
	{ "setfz",		"Na",		"<fz> [atom/id]", VTypes::NoData,
				"Set the z force of the current (or specified) atom" },
	{ "setid",		"Na",		"<id> [atom/id]", VTypes::NoData,
				"Set the id of the current (or specified) atom" },
	{ "setrx",		"Na",		"<rx> [atom/id]", VTypes::NoData,
				"Set the x coordinate of the current (or specified) atom" },
	{ "setry",		"Na",		"<ry> [atom/id]", VTypes::NoData,
				"Set the y coordinate of the current (or specified) atom" },
	{ "setrz",		"Na",		"<rz> [atom/id]", VTypes::NoData,
				"Set the z coordinate of the current (or specified) atom" },
	{ "setvelocities",	"NNNa",		"<vx> <vy> <vz> [atom/id]", VTypes::NoData,
				"Set the velocities of the current (or specified) atom" },
	{ "setvx",		"Na",		"<vx> [atom/id]", VTypes::NoData,
				"Set the x velocity of the current (or specified) atom" },
	{ "setvy",		"Na",		"<vy> [atom/id]", VTypes::NoData,
				"Set the y velocity of the current (or specified) atom" },
	{ "setvz",		"Na",		"<vz> [atom/id]", VTypes::NoData,
				"Set the z velocity of the current (or specified) atom" },
	{ "show",		"a",		"[atom/id]", VTypes::NoData,
				"Show (make visible) the current selection of atoms (or supplied atom)" },
	{ "showall",		"",		"", VTypes::NoData,
				"Show all atoms in the current model" },

	// Bonding commands
	{ "augment",		"",		"", VTypes::NoData,
				"Automatically augment all bonds in the current model" },
	{ "bondtolerance",	"n",		"[double <tol>]", VTypes::DoubleData,
				"Set bonding tolerance for automatic calculation" },
	{ "clearbonds",		"",		"", VTypes::NoData,
				"Delete all bonds in the current model" },
	{ "clearselectedbonds",	"",		"", VTypes::NoData,
				"Delete all bonds in the current selection" },
	{ "newbond",		"AAs",		"<atom1> <atom2> [bondtype]", VTypes::NoData,
				"Create a bond between specified atoms" },
	{ "newbondid",		"NNs",		"<id1> <id2> [bondtype]", VTypes::NoData,
				"Create a bond between atoms with ids specified" },
	{ "rebond",		"",		"", VTypes::NoData,
				"Calculate bonding in the current model" },
	{ "rebondpatterns",	"",		"", VTypes::NoData,
				"Calculate bonds between atoms, restricted to atoms in pattern molecules" },
	{ "rebondselection",	"",		"", VTypes::NoData,
				"Calculate bonds between atoms in the current selection" },

	// Build commands
	{ "addhydrogen",	"a",		"[atom|id]", VTypes::NoData,
				"Hydrogen satisfy all (or specified) atom in model" },
	{ "bohr",		"X*",		"<object> [object...]", VTypes::NoData,
				"Convert coordinates in the specified object(s) from Angstroms to Bohr" },
	{ "chain",		"Ss|S3Ns",	"<element> [bondtype] | <element> <x> <y> <z> [bondtype]", VTypes::AtomData,
				"Create a new atom in the current model, bound to the last" },
	{ "endchain",		"",		"", VTypes::AtomData,
				"End the current bond chain (the next call to 'chain' will create an unbound atom)" },
	{ "insertatom",		"SN[nnn]",	"<element> <id> [x y z]", VTypes::AtomData,
				"Insert a new atom into the model such that it has the ID specified" },
	{ "locate",		"NNN",		"<x> <y> <z>", VTypes::NoData,
				"Position pen at specified coordinates" },
	{ "move",		"NNN",		"<dx> <dy> <dz>", VTypes::NoData,
				"Move pen by specified coordinates" },
	{ "movetoend",		"",		"", VTypes::NoData,
				"Move current atom selection to end of list" },
	{ "movetostart",	"",		"", VTypes::NoData,
				"Move current atom selection to start of list" },
	{ "newatom",		"S[nnn]",	"<element> [x y z]", VTypes::AtomData,
				"Create a new atom in the current model" },
	{ "newatomfrac",	"SNNN",		"<element> <fracx> <fracy> <fracz>", VTypes::AtomData,
				"Create a new atom in the current model, converting fractional coordinates to real coordinates" },
	{ "reorder",		"",		"", VTypes::NoData,
				"Reorder atoms in the current selection such that bond partners have adjacent atom IDs" },
	{ "resetpen",		"",		"", VTypes::NoData,
				"Reset the pen orientation to the identity matrix (but leave the current position intact)" },
	{ "rotx",		"N",		"<angle>", VTypes::NoData,
				"Rotate pen about its x axis by given angle" },
	{ "roty",		"N",		"<angle>", VTypes::NoData,
				"Rotate pen about its y axis by given angle" },
	{ "rotz",		"N",		"<angle>", VTypes::NoData,
				"Rotate pen about its z axis by given angle" },
	{ "shiftdown",		"n",		"[n]", VTypes::NoData,
				"Shift current atom selection down 1 (or 'n') places" },
	{ "shiftup",		"n",		"[n]", VTypes::NoData,
				"Shift current atom selection up 1 (or 'n') places" },
	{ "transmute",		"S",		"<element>", VTypes::NoData,
				"Transmute selection to element given" },
	
	// Cell commands
	{ "addgenerator",	"C",		"<generator>", VTypes::NoData,
				"Manually add a spacegroup generator definition to the current model's cell" },
	{ "adjustcell",		"CN",		"<quantity> <change>", VTypes::NoData,
				"Adjust a single value of the current cell specification (e.g. <quantity> = a, beta, cz, etc.)" },
	{ "cell",		"NNNNNN",	"<a> <b> <c> <alpha> <beta> <gamma>", VTypes::NoData,
				"Set or create a unit cell for the current model from lengths/angles provided" },
	{ "cellaxes",		"NNNNNNNNN",	"<ax> <ay> <az> <bx> <by> <bz> <cx> <cy> <cz>", VTypes::NoData,
				"Set or create a unit cell for the current model from the cell axes provided" },
	{ "fold",		"",		"", VTypes::NoData,
				"Fold atoms into model's unit cell" },
	{ "foldmolecules",	"",		"", VTypes::NoData,
				"Fold molecules (defined by patterns) so that they are unbroken across cell boundaries" },
	{ "fractoreal",		"",		"", VTypes::NoData,
				"Convert (assumed) fractional model coordinates to real coordinates" },
	{ "nocell",		"", 		"", VTypes::NoData,
				"Remove any cell definition from the current model" },
	{ "pack",		"",		"", VTypes::NoData,
				"Pack the unit cell with symmetry operators list in associated spacegroup" },
	{ "printcell",		"",		"", VTypes::NoData,
				"Print the unit cell of the current model" },
	{ "replicate",		"NNNNNN",	"<negx> <negy> <negz> <posx> <posy> <posz>", VTypes::NoData,
				"Replicate the cell by the unit cell amounts specified in each direction, beyond the original cell" },
	{ "rotatecell",		"CN",		"<axis> <angle>", VTypes::NoData,
				"Rotate the cell and its contents about the specified orthogonal axis (x, y, or z)" },
	{ "scale",		"NNN",		"<x> <y> <z>", VTypes::NoData,
				"Scale the unit cell and atomic positions of the current model" },
	{ "scalemolecules",	"NNN",		"<x> <y> <z>", VTypes::NoData,
				"Scale the unit cell and molecular positions of the current model" },
	{ "setcell",		"CN",		"<quantity> <value>", VTypes::NoData,
				"Set a single value of the current cell specification (e.g. <quantity> = a, beta, cz, etc.)" },
	{ "spacegroup",		"S",		"<spgrp>", VTypes::NoData,
				"Set the spacegroup for the current model" },
	
	// Charge commands
	{ "chargeff",		"",		"", VTypes::NoData,
				"Charge atoms in the model according to their forcefield atom types" },
	{ "chargefrommodel",	"",		"", VTypes::NoData,
				"Charge atoms in the current trajectory frame from the parent model" },
	{ "chargepatom",	"NN",		"<id> <q>", VTypes::NoData,
				"Set charges for specific atom id in all molecules of the current pattern" },
	{ "charge",		"N",		"<q>", VTypes::NoData,
				"Set charges of atoms in the current selection" },
	{ "chargetype",		"CN",		"<type> <q>", VTypes::NoData,
				"Set charges of all atoms of the given type" },
	{ "clearcharges",	"",		"", VTypes::NoData,
				"Zero all charges in the current model" },

	// Colourscale commands
	{ "addpoint",		"NNNNNn",	"<scaleid> <value> <r> <g> <b> [a]", VTypes::NoData,
				"Add a new point to the specified colourscale" },
	{ "clearpoints",	"N",		"<scaleid>", VTypes::NoData,
				"Clear all points from the specified colourscale" },
	{ "listscales",		"",		"", VTypes::NoData,
				"List details on all colourscales" },
	{ "removepoint",	"NN",		"<scaleid> <point>", VTypes::NoData,
				"Remove the selected point from the specified colourscale" },
	{ "scalename",		"Nc",		"<scaleid> [name]", VTypes::StringData,
				"Print (or set) the name of the colourscale specified" },
	{ "scalevisible",	"NB",		"<scaleid> true|false", VTypes::NoData,
				"Set the visibility of the specified colourscale" },
	{ "setpoint",		"NNNNNNn",	"<scaleid> <point> <value> <r> <g> <b> [a]", VTypes::NoData,
				"Set an existing point on the specified colourscale" },
	{ "setpointcolour", 	"NNNNNn",	"<scaleid> <point> <r> <g> <b> [a]", VTypes::NoData,
				"Set the colour for an existing colourscale point" },
	{ "setpointvalue", 	"NNN",		"<scaleid> <point> <value>", VTypes::NoData,
				"Set the value for an existing colourscale point" },

	// Disordered Builder Commands
	{ "disorder",		"N",		"<nsteps>", VTypes::NoData,
				"Run the disordered builder" },
	{ "listcomponents",	"",		"", VTypes::NoData,
				"Print a list of the components requested in the disordered builder" },
	{ "nmols",		"N",		"<n>", VTypes::NoData,
				"Set the number of molecules required for the component" },
	{ "region",		"CNNNNNNB",	"<shape> <cx> <cy> <cz> <x> <y> <z> <overlap?>", VTypes::NoData,
				"Set the shape, centre, size, and overlap flag of the region for the current model" },
	{ "regioncentre",	"NNN",		"<x> <y> <z>", VTypes::NoData,
				"Set the region centre of the current model" },
	{ "regioncentreffrac",	"NNN",		"<x> <y> <z>", VTypes::NoData,
				"Set the region centre of the current model (fractional coordinates)" },
	{ "regionfrac",		"CNNNNNNB",	"<shape> <cx> <cy> <cz> <x> <y> <z> <overlap?>", VTypes::NoData,
				"Set the shape, centre, size, and overlap flag of the region for the current model (fractional coordinates)" },
	{ "regiongeometry",	"NNNN",		"<x> <y> <z> [l]", VTypes::NoData,
				"Set the region geometry of the current model" },
	{ "regiongeometryfrac",	"NNNn",		"<x> <y> <z> [l]", VTypes::NoData,
				"Set the region geometry of the current model (fractional coordinates)" },
	{ "regionoverlap",	"B",		"<overlap?>", VTypes::NoData,
				"Set the overlap flag of the current model" },
	{ "regionshape",	"C",		"<shape>", VTypes::NoData,
				"Set the region shape of the current model" },
	{ "vdwscale",		"n",		"[scale]", VTypes::DoubleData,
				"Retrieve (or set) the VDW scaling factor to use in the disordered builder" },

	// Edit commands
	{ "copy",		"",		"", VTypes::NoData,
				"Copy selected atoms" },
	{ "cut",		"",		"", VTypes::NoData,
				"Cut the selected atoms" },
	{ "delete",		"",		"", VTypes::NoData,
				"Delete selected atoms" },
	{ "paste",		"nnn",		"[dx] [dy] [dz]", VTypes::NoData,
				"Paste previously-cut or copied atoms to the model (with optional shift from original position" },
	{ "redo",		"",		"", VTypes::NoData,
				"Redo last change" },
	{ "undo",		"",		"", VTypes::NoData,
				"Undo last change" },

	// Energy commands
	{ "frameenergy",	"",		"", VTypes::DoubleData,
				"Calculate the energy of the current trajectory frame" },
	{ "modelenergy",	"",		"", VTypes::DoubleData,
				"Calculate the energy of the current model" },
	{ "printelec",		"",		"", VTypes::NoData,
				"Print the electrostatic pattern matrix of the last calculated energy" },
	{ "printewald",		"",		"", VTypes::NoData,
				"Print the Ewald decomposition of the last calculated energy" },
	{ "printinter",		"",		"", VTypes::NoData,
				"Print the total intermolecular pattern matrix of the last calculated energy" },
	{ "printintra",		"",		"", VTypes::NoData,
				"Print the total intramolecular pattern matrix of the last calculated energy" },
	{ "printenergy",	"",		"", VTypes::NoData,
				"Print a short description of the last calculated energy" },
	{ "printsummary",	"",		"", VTypes::NoData,
				"Print a one-line summary of the last calculated energy" },
	{ "printvdw",		"",		"", VTypes::NoData,
				"Print the VDW pattern matrix of the last calculated energy" },

	// Flow control
	{ "break",		"",		"", VTypes::NoData,
				"Exit from the current for loop" },
	{ "continue",		"",		"", VTypes::NoData,
				"Skip to the next iteration of the current loop" },
	{ "dowhile",		"_",		"{ ... } (<expression>)", VTypes::NoData,
				"Run the enclosed block or statement as many times as <expression> evaluates to TRUE" },
	{ "for",		"_",		"(<var> = <startval>,<finalval>[,<increment>]) { ... }", VTypes::NoData,
				"" },
	{ "if",			"_",		"(<expression> <condition> <expression>) { ... } [else { ... }]", VTypes::NoData,
				"Perform a conditional test between the supplied expressions (or variables or constants)" },
	{ "return",		"z",		"[value]", VTypes::NoData,
				"Terminate execution of the current program/filter/function, optionally returning the value provided" },
	{ "while",		"_",		"(<expression>) { ... }", VTypes::NoData,
				"Run the enclosed block or statement as many times as <expression> evaluates to TRUE" },
	
	// Force commands
	{ "frameforces",	"",		"", VTypes::NoData,
				"Calculate forces for the current trajectory frame" },
	{ "modelforces",	"",		"", VTypes::NoData,
				"Calculate forces for the current model" },
	{ "printforces",	"",		"", VTypes::NoData,
				"Print calculated forces for the current model" },
	
	// Forcefield commands
	{ "angledef",		"CCCCNnnnnn", "<form> <name1> <name2> <name3> <data1> [data2 ... data6]", VTypes::NoData,
				"Add an angle definition to the current forcefield" },
	{ "bonddef",		"CCCNnnnnn", "<form> <name1> <name2> <data1> [data2 ... data6]", VTypes::NoData,
				"Add a bond definition to the current forcefield" },
	{ "clearmap",		"",		"", VTypes::NoData,
				"Clear manual type mapping list" },
	{ "createexpression",	"",		"", VTypes::NoData,
				"Create and fill a forcefield expression for the current model" },
	{ "defaultff",		"F",		"<ff>", VTypes::NoData,
				"Make named forcefield the default for occasions where no other is specified" },
	{ "equivalents",	"CC*",		"<name> <'names...'>", VTypes::NoData,
				"Define forcefield equivalents" },
	{ "ffmodel",		"c",		"[name]", VTypes::NoData,
				"Associate current (or named) forcefield to current model" },
	{ "ffpattern",		"p",		"[pattern|id|name]", VTypes::NoData,
				"Associate current forcefield to current pattern" },
	{ "finaliseff",		"",		"", VTypes::NoData,
				"Finalise current forcefield" },
	{ "genconvert",		"N*",		"<data1> [data2..data10]", VTypes::NoData,
				"Set energetic generator data to convert" },
	{ "generator",		"NNnnnnnnnnn",	"<typeId> <data1> [data2...data10]", VTypes::NoData,
				"Set generator data for specified atom type" },
	{ "getff",		"C",		"<name>", VTypes::ForcefieldData,
				"Select named (loaded) forcefield and make it current, and return a reference to it" },
	{ "interdef",		"CNNNnnnnn", "<form> <typeid> <charge> <data1> [data2...data6]", VTypes::NoData,
				"Add a new interatomic definition to the current forcefield" },
	{ "loadff",		"Cc",		"<filename> [name]", VTypes::ForcefieldData,
				"Load forcefield from file, renaming to new name if one was supplied" },
	{ "map",		"C*",		"<name=element,...>", VTypes::NoData,
				"Add typename mappings" },
	{ "newff",		"C",		"<name>", VTypes::ForcefieldData,
				"Create a new, empty forcefield" },
	{ "printsetup",		"",		"", VTypes::NoData,
				"Print the current energy/force calculation setup" },
	{ "rules",		"C",		"<rules set>", VTypes::NoData,
				"Set rules set to use for parameter generation" },
	{ "saveexpression",	"CC",		"<format> <filename>", VTypes::IntegerData,
				"Save the expression for the current model" },
	{ "torsiondef",		"CCCCCNnnnnn", "<form> <name1> <name2> <name3> <name4> <data1> [data2 ... data6]", VTypes::NoData,
				"Add a torsion definition to the current forcefield" },
	{ "typedef",		"NCSCc", "<typeid> <name> <element> <type> [description]", VTypes::NoData,
				"Add an atom type to the current forcefield" },
	{ "typemodel",		"",		"", VTypes::NoData,
				"Perform atom typing on the current model" },
	{ "typetest",		"NA",		"<id> <atom|id>", VTypes::IntegerData,
				"Test atomtype score on atom id provided" },
	{ "units",		"C",		"<energy unit>", VTypes::NoData,
				"Set energy unit of forcefield" },

	// Glyph commands
	{ "autoellipsoids",	"c*",		"[options]", VTypes::NoData,
				"Automatically add ellipsoids to the current atom selection" },
	{ "autopolyhedra",	"c*",		"[options]", VTypes::NoData,
				"Automatically add polyhedra to the current atom selection" },
	{ "glyphatomf",		"Na",		"<n> [atom/id]", VTypes::NoData,
				"Set current (or specified) atom's forces as data <n> in current glyph" },
	{ "glyphatomr",		"Na",		"<n> [atom/id]", VTypes::NoData,
				"Set current (or specified) atom's coordinates as data <n> in current glyph" },
	{ "glyphatomv",		"Na",		"<n> [atom/id]", VTypes::NoData,
				"Set current (or specified) atom's velocities data <n> in current glyph" },
	{ "glyphatomsf",	"Aaaa",		"<atom/id> [atom/id] [atom/id] [atom/id]", VTypes::NoData,
				"Set all atom forces data in current glyph" },
	{ "glyphatomsr",	"Aaaa",		"<atom/id> [atom/id] [atom/id] [atom/id]", VTypes::NoData,
				"Set all atom coordinates data in current glyph" },
	{ "glyphatomsv",	"Aaaa",		"<atom/id> [atom/id] [atom/id] [atom/id]", VTypes::NoData,
				"Set all atom velocities data in current glyph" },
	{ "glyphcolour",	"NNNNn",	"<n> <r> <g> <b> [a]", VTypes::NoData,
				"Set colour data <n> in current glyph" },
	{ "glyphdata",		"NNnn",		"<n> <x> [y] [z]", VTypes::NoData,
				"Set vector data <n> in current glyph" },
	{ "glyphsolid",		"B",		"<solid?>", VTypes::NoData,
				"Set the glyph to be drawn in solid (true) or wireframe (false) modes (glyph-permitting)" },
	{ "glyphtext",		"C",		"<text>", VTypes::NoData,
				"Set text data in current glyph" },
	{ "newglyph",		"Cc",		"<style> [options]", VTypes::NoData,
				"Add a glyph with the specified style to the current model" },

	// Grid commands
	{ "addgridpoint",	"NNNN",		"<ix> <iy> <iz> <value>", VTypes::NoData,
				"Set specific gridpoint value" },
	{ "addnextgridpoint",	"N",		"<value>", VTypes::NoData,
				"Add next gridpoint value" },
	{ "finalisegrid",	"",		"", VTypes::NoData,
				"Finalise grid import" },
	{ "getgrid",		"N",		"<id>", VTypes::GridData,
				"Retrieve data for grid with id specified, and return a reference to it" },
	{ "gridalpha",		"N",		"<alpha>", VTypes::DoubleData,
				"Set the alpha value of the surface (when not using a colourscale)" },
	{ "gridaxes",		"NNNNNNNNN",	"<ax> <ay> <az> <bx> <by> <bz> <cx> <cy> <cz>", VTypes::NoData,
				"Set axis system for the current grid" },
	{ "gridcolour",		"NNNn",		"<r> <g> <b> [a]", VTypes::NoData,
				"Set the (positive) colour of the surface (when not using a colourscale)" },
	{ "gridcolournegative",	"NNNn",		"<r> <g> <b> [a]", VTypes::NoData,
				"Set the negative colour of the surface (when not using a colourscale)" },
	{ "gridcolourscale",	"N",		"<scaleID>", VTypes::NoData,
				"Links the surface to the specified colour scale (or zero to return to internal colour)" },
	{ "gridcubic",		"N",		"<l>", VTypes::NoData,
				"Setup a cubic axis system for the current grid" },
	{ "gridcutoff",		"N",		"<cutoff>", VTypes::NoData,
				"Set the cutoff for the current grid" },
	{ "gridlooporder",	"S",		"<xyz|zyx|213...>", VTypes::NoData,
				"Set the loop ordering to use in 'addnextgridpoint'" },
	{ "gridorigin",		"NNN",		"<x> <y> <z>", VTypes::NoData,
				"Set the origin of the axes system for the current grid" },
	{ "gridortho",		"NNN",		"<a> <b> <c>", VTypes::NoData,
				"Setup an orthorhombic axis system for the current grid" },
	{ "gridsize",		"NNN",		"<nx> <ny> <nz>", VTypes::NoData,
				"Set the number of points along each axis for the current grid" },
	{ "gridstyle",		"C",		"<style>", VTypes::NoData,
				"Set the drawing style of the current grid" },
	{ "gridsymmetric",	"B",		"<symm?>", VTypes::IntegerData,
				"Set whether the isodata is symmetric about zero (i.e. whether to draw both halves)" },
	{ "gridusez",		"B",		"<usez?>", VTypes::IntegerData,
				"Whether a 2D surface uses the vertex data value as its z (height) data" },
	{ "loadgrid",		"C",		"<gridfile>", VTypes::GridData,
				"Load grid data" },
	{ "newgrid",		"C",		"<title>", VTypes::GridData,
				"Create new grid data" },

	// Image commands
	{ "savebitmap",		"CCnnn",	"<format> <filename> [width] [height] [quality, 0-100]", VTypes::NoData,
				"Save the current model view as a bitmap image: formats available are bmp, jpg, png, ppm, xbm, and xpm" },
	{ "savevector",		"CC",		"<format> <filename>", VTypes::NoData,
				"Save the current model view as a vector image: formats available are ps, eps, tex, pdf, svg, and pgf" },
	
	// Labeling commands
	{ "clearlabels",	"",		"", VTypes::NoData,
				"Remove all atom labels in the current model" },
	{ "label",		"Ca",		"<label> [atom/id]", VTypes::NoData,
				"Add labels to the current atom selection (or specified atom)" },
	{ "removelabel",	"Ca",		"<label> [atom/id]", VTypes::NoData,
				"Remove labels from the current atom selection (or specified atom)" },
	{ "removelabels",	"a",	"[atom/id]", VTypes::NoData,
				"Remove all labels from the current atom selection (or specified atom)" },

	// MC commands
	{ "mcaccept",		"CN",		"<movetype> <energy>", VTypes::NoData,
				"Set Monte Carlo move type acceptance energies" },
	{ "mcallow",		"CB",		"<movetype> <allow?>", VTypes::NoData,
				"Restrict or allow Monte Carlo move types" },
	{ "mcmaxstep",		"CN",		"<movetype> <step>", VTypes::NoData,
				"Set maximum step sizes for Monte Carlo move types" },
	{ "mcntrials",		"CN",		"<movetype> <ntrials>", VTypes::NoData,
				"Set trial numbers for Monte Carlo move types" },
	{ "printmc",		"",		"", VTypes::NoData,
				"Print current Monte Carlo parameters" },
	
	// Measurements
	{ "angle",		"AAA",		"<atom|id1> <atom|id2> <atom|id3>", VTypes::DoubleData,
				"Measure angle between atoms specified" },
	{ "angles",		"",		"", VTypes::NoData,
				"Measure bond angles between atoms in current selection" },
	{ "clearmeasurements",	"",		"", VTypes::NoData,
				"Clear all measurements in the current model" },
	{ "distance",		"AA",		"<atom|id1> <atom|id2>", VTypes::DoubleData,
				"Measure distance between atoms specified" },
	{ "distances",		"",		"", VTypes::NoData,
				"Measure bond distances between atoms in current selection" },
	{ "listmeasurements",	"",		"", VTypes::NoData,
				"List all measurements in the current model" },
	{ "measure",		"AAaa",		"<atom|id1> <atom|id2> [atom|id3] [atom|id4]", VTypes::DoubleData,
				"Make a measurement between the specified atoms" },
	{ "torsion",		"AAAA",		"<atom|id1> <atom|id2> <atom|id3> <atom|id4>", VTypes::DoubleData,
				"Measure torsion angle between atoms specified" },
	{ "torsions",		"",		"", VTypes::NoData,
				"Measure torsion angles between atoms in current selection" },

	// Messaging
	{ "error",		"Cz*",		"<message>", VTypes::NoData,
				"Raise an error message (causes exit of current command list)" },
	{ "printf",		"Cz*",		"<message>", VTypes::NoData,
				"Print a message" },
	{ "verbose",		"Cz*",		"<message>", VTypes::NoData,
				"Print a message when verbose output is enabled" },
	
	// Minimisation commands
	{ "cgminimise",		"",		"", VTypes::NoData,
				"Run a conjugate gradient minimiser on the current model" },
	{ "converge",		"NN",		"<energy> <forces>", VTypes::NoData,
				"Set energy and RMS force convergence limits for minimisation algorithms" },
	{ "linetol",		"N",		"<tolerance>", VTypes::NoData,
				"Set tolerance of line minimiser" },
	{ "mcminimise",		"N",		"<maxsteps>", VTypes::NoData,
				"Run Monte Carlo minimiser on the current model" },
	{ "sdminimise",		"N",		"<maxsteps>", VTypes::NoData,
				"Run steepest descent minimiser on the current model" },
	{ "simplexminimise",	"",		"", VTypes::NoData,
				"Run the Simplex minimiser on the current model" },
	
	// Model commands
	{ "createatoms",	"",		"", VTypes::NoData,
				"Create enough atoms in the current trajectory frame to match the parent model" },
	{ "currentmodel",	"m",		"[name|id|ptr]", VTypes::ModelData,
				"Return reference to the current model, or set the current model" },
	{ "finalisemodel",	"",		"", VTypes::NoData,
				"Finalise the current model" },
	{ "firstmodel",		"",		"", VTypes::ModelData,
				"Make the first loaded/created model current" },
	{ "getmodel",		"M",		"<name|id|ptr>", VTypes::ModelData,
				"Find the named (loaded) model, and return a reference to it" },
	{ "info",		"",		"", VTypes::NoData,
				"Print data on the current model" },
	{ "lastmodel",		"",		"", VTypes::ModelData,
				"Make the last loaded/created model current" },
	{ "listmodels",		"",		"", VTypes::NoData,
				"List the currently-loaded models" },
	{ "loadmodel",		"Cc",		"<filename> [name]", VTypes::IntegerData,
				"Load a model from file" },
	{ "loginfo",		"",		"", VTypes::NoData,
				"Print log information for model" },
	{ "modeltemplate",	"",		"", VTypes::NoData,
				"Template the atoms in the current trajectory frame, matching the parent model" },
	{ "newmodel",		"C",		"<name>", VTypes::ModelData,
				"Create a new model" },
	{ "nextmodel",		"",		"", VTypes::ModelData,
				"Skip to the next loaded model" },
	{ "prevmodel",		"",		"", VTypes::ModelData,
				"Skip to the previous loaded model" },
	{ "savemodel",		"CC",		"<format> <filename>", VTypes::IntegerData,
				"Save the current model to <filename> in the specified model <format>" },
	{ "setname",		"C",		"<name>", VTypes::NoData,
				"Set the name of the current model" },

	// Pattern commands
	{ "clearpatterns",	"",		"", VTypes::NoData,
				"Remove all pattern definitions from the current model" },
	{ "createpatterns",	"",		"", VTypes::NoData,
				"Automatically determine pattern definitions for the current model" },
	{ "getpattern",		"P",		"<name|id|ptr>", VTypes::PatternData,
				"Select the named pattern (or pattern id) and make it current" },
	{ "listpatterns",	"",		"", VTypes::NoData,
				"Print the pattern definition for the current model" },
	{ "newpattern",		"CNN",		"<name> <nmolecules> <natoms>", VTypes::PatternData,
				"Add a pattern definition 'node' to the current model" },

	// Preferences commands
	{ "anglelabel",		"C",		"<text>", VTypes::NoData,
				"Set the units label to use for angles" },
	{ "atomdetail",		"N",		"<n>", VTypes::NoData,
				"Set the quadric detail of atoms" },
	{ "bonddetail",		"N",		"<n>", VTypes::NoData,
				"Set the quadric detail of bonds" },
	{ "colour",		"CNNNN",	"<colour> <r> <g> <b> [a]", VTypes::NoData,
				"Set the specified colour" },
	{ "commonelements",	"C",		"<elements...>", VTypes::NoData,
				"Set the common elements that appear in the Select Element dialog" },
	{ "densityunits",	"C",		"atomsperang|gpercm", VTypes::NoData,
				"Set the unit of density to use" },
	{ "distancelabel",	"C",		"<text>", VTypes::NoData,
				"Set the units label to use for distances" },
	{ "ecut",		"N",		"<cutoff>", VTypes::NoData,
				"Set the electrostatic cutoff distance" },
	{ "elec",		"Cnnnn",	"<none|coulomb|ewald|ewaldauto> [ <precision> | <alpha> <kx> <ky> <kz> ]", VTypes::NoData,
				"Set the style of electrostatic energy calculation" },
	{ "elementambient",	"SNNN",		"<element> <r> <g> <b>", VTypes::NoData,
				"Set ambient colour of element" },
	{ "elementdiffuse",	"SNNN",		"<element> <r> <g> <b>", VTypes::NoData,
				"Set diffuse colour of element" },
	{ "elementradius",	"SN",		"<element> <radius>", VTypes::NoData,
				"Set effective radius of element" },
	{ "energyunits",	"C",		"j|kj|cal|kcal|ha", VTypes::NoData,
				"Set the unit of energy to use" },
	{ "gl",			"CB",		"<option> <on|off>", VTypes::NoData,
				"Turn on/off various OpenGL options: fog, linealias, polyalias, backcull" },
	{ "hdistance",		"N",		"<distance>", VTypes::NoData,
				"Set the H-X bond distance to use when adding hydrogen" },
	{ "intra",		"B",		"<on|off>", VTypes::NoData,
				"Turn on/off energy and force calculation of intramolecular terms" },
	{ "key",		"CC",		"ctrl|shift|alt <action>", VTypes::NoData,
				"Set the action of modifier keys" },
	{ "labelsize",		"N",		"<pointsize>", VTypes::NoData,
				"Set the integer pointsize for label text" },
	{ "light",		"B",		"<on|off>", VTypes::NoData,
				"Turn the spotlight on/off" },
	{ "lightambient",	"NNN",		"<r> <g> <b>", VTypes::NoData,
				"Set the ambient colour component of the spotlight" },
	{ "lightdiffuse",	"NNN",		"<r> <g> <b>", VTypes::NoData,
				"Set the diffuse colour component of the spotlight" },
	{ "lightposition",	"NNN",		"<x> <y> <z>", VTypes::NoData,
				"Set the coordinates of the spotlight" },
	{ "lightspecular",	"NNN",		"<r> <g> <b>", VTypes::NoData,
				"Set the specular colour component of the spotlight" },
	{ "mouse",		"CC",		"left|middle|right|wheel <action>", VTypes::NoData,
				"Set the action of mouse buttons" },
	{ "radius",		"CN",		"<style> <r>", VTypes::NoData,
				"Set the general atom scales for view styles" },
	{ "replicatefold",	"B",		"<on|off>", VTypes::NoData,
				"Set whether to fold atoms before cell replicate" },
	{ "replicatetrim",	"B",		"<on|off>", VTypes::NoData,
				"Set whether to trim atoms after cell replicate" },
	{ "scheme",		"C",		"[colour scheme]", VTypes::NoData,
				"Show (or set) the atomic colouring scheme to use" },
	{ "shininess",		"N",		"<n>", VTypes::NoData,
				"Set the shininess of atoms" },
	{ "showonscreen",	"cb",		"[object  yes|no]", VTypes::NoData,
				"Set (or lists) the visibility of view objects on-screen" },
	{ "showonimage",	"cb",		"[object  yes|no]", VTypes::NoData,
				"Set (or lists) the visibility of view objects on saved images" },
	{ "style",		"c",		"[style]", VTypes::NoData,
				"Set (or show) the current model drawing style" },
	{ "swapbuffers",	"b",		"[on|off]", VTypes::NoData,
				"Set (or show) the current model drawing style" },
	{ "usenicetext",	"b",		"[on|off]", VTypes::NoData,
				"Use QPainter (on) or QGlWidget (off) to render label text" },
	{ "vcut",		"N",		"<cutoff>", VTypes::NoData,
				"Set the VDW cutoff distance" },
	{ "vdw",		"B",		"<on|off>", VTypes::NoData,
				"Turn on/off VDW energy/force calculation" },
	{ "zoomthrottle",	"n",		"[ratio]", VTypes::NoData,
				"Display (or set) the zooming throttle" },

	// Read / Write Commands
	{ "addreadoption",	"C",		"<option>", VTypes::NoData,
				"Add a read option: usequotes, skipblanks, stripbrackets" },
	{ "eof",		"",		"", VTypes::IntegerData,
				"Return whether the end of the file has been reached (or only whitespace remains)" },
	{ "filterfilename",	"",		"", VTypes::StringData,
				"Returns the name of the file that the current filter is reading from / writing to" },
	{ "find",		"C^c",		"<string> [linevar]", VTypes::IntegerData,
				"Search for a string in the input file (placing matching line in optional variable)" },
	{ "getline",		"^C",		"", VTypes::IntegerData,
				"Read the next line from the file, placing in variable supplied, and returning read success" },
	{ "peekchar",		"",		"", VTypes::StringData, 
				"Peek the next character from the current input file, and return it as a string" },
	{ "peekchari",		"",		"", VTypes::IntegerData, 
				"Peek the next character from the current input file, and return its ASCII code" },
	{ "readchars",		"N",		"<nchars>", VTypes::StringData,
				"Read a number of characters from the input file" },
	{ "readdouble",		"n",		"[nbytes]", VTypes::DoubleData,
				"Read a floating point value from the (binary) input file" },
	{ "readdoublearray",	"&DN",		"<array> <nvalues>", VTypes::IntegerData,
				"Read floating point values from the (binary) input file, placing in the array provided" },
	{ "readint",		"n",		"[nbytes]", VTypes::IntegerData,
				"Read an integer value from the (binary) input file" },
	{ "readintarray",	"&IN",		"<array> <nvalues>", VTypes::IntegerData,
				"Read integer values from the (binary) input file, placing in the array provided" },
	{ "readline",		"^Z*",		"<variable>  [variable...]", VTypes::IntegerData,
				"Read a line from the input file, and split into supplied variables using whitespace delimiters" },
	{ "readlinef",		"C^z*",		"<formatting string> [data1, data2...]", VTypes::IntegerData,
				"Read a line from the input file, and parse into supplied variables using format string" },
	{ "readnext",		"^Z",		"<variable>", VTypes::IntegerData,
				"Read the next delimited item from the file and place in the variable supplied" },
	{ "readvar",		"C^z*",	"<string> [data1, data2...]", VTypes::IntegerData,
				"Parse delimited arguments from a character variable" },
	{ "readvarf",		"CC^z*",	"<string> <formatting string> [data1, data2...]", VTypes::IntegerData,
				"Parse a character variable according to the supplied format" },
	{ "removereadoption",	"C",		"<option>", VTypes::NoData,
				"Remove a read option" },
	{ "rewind",		"",		"", VTypes::NoData,
				"Rewind to the start of the input file" },
	{ "skipchars",		"N",		"<nchars>", VTypes::NoData,
				"Skip a number of characters in the input file" },
	{ "skipline",		"n",		"[nlines]", VTypes::NoData,
				"Skip a number of lines in the input file" },
	{ "writeline",		"Z*",		"<data1> [data2...]", VTypes::NoData,
				"Write an formatted line to the output file, with data items separated by spaces" },
	{ "writelinef",		"Cz*",		"<formatting string> [data1, data2...]", VTypes::NoData,
				"Write a formatted line to the output file" },
	{ "writevar",		"^Cz*",		"<variable> [data1, data2...]", VTypes::NoData,
				"Write a delimited series of arguments to the supplied character variable" },
	{ "writevarf",		"^CCz*",	"<variable> <formatting string> [data1, data2...]", VTypes::NoData,
				"Write a formatted line to the supplied character variable" },

	// Script commands
	{ "listscripts",	"",		"", VTypes::NoData,
				"List available scripts" },
	{ "loadscript",		"Cc",		"<filename> [nickname]", VTypes::NoData,
				"Load script from file" },
	{ "runscript",		"S",		"<name|id>", VTypes::NoData,
				"Execute the named script" },

	// Selection commands
	{ "deselect",		"Z*",		"<id|el|id~id|el~el|+id|+el|id+|el+,...>", VTypes::IntegerData,
				"Deselect specific atoms / ranges in the current model" },
	{ "deselecttype",	"SC",		"<element> <typedesc>", VTypes::IntegerData,
				"Deselect all atoms that match the provided atomtype description" },
	{ "expand",		"",		"", VTypes::IntegerData,
				"Expands the current atom selection" },
	{ "invert",		"",		"", VTypes::IntegerData,
				"Invert the current selection" },
	{ "select",		"Z*",		"<id|el|id-id|el-el|+id|+el|id+|el+,...>", VTypes::IntegerData,
				"Select specific atoms / ranges in the current model" },
	{ "selectall",		"",		"", VTypes::NoData,
				"Select all atoms in the current model" },
	{ "selectfftype",	"C",		"<typename>", VTypes::IntegerData,
				"Select all atoms of a specific forcefield type" },
	{ "selectioncog",	"",		"", VTypes::VectorData,
				"Return centre of geometry of current selection" },
	{ "selectioncom",	"",		"", VTypes::VectorData,
				"Return centre of mass of current selection" },
	{ "selectnone",		"",		"", VTypes::NoData,
				"Deselect all atoms in the current model" },
	{ "selectoverlaps",	"n",		"[tolerance = 0.2]", VTypes::IntegerData,
				"Select all atoms which are within a given distance of each other" },
	{ "selectpattern",	"p",		"[name]", VTypes::IntegerData,
				"Select all atoms in the current (or named) pattern" },
	{ "selecttype",		"SC",		"<element> <typedesc>", VTypes::IntegerData,
				"Select all atoms that match the provided atomtype description (returning the number matched)" },
	
	// Site commands
	{ "getsite",		"C",		"<name>", VTypes::NoData,
				"Select the defined site and make it current" },
	{ "listsites",		"",		"", VTypes::NoData,
				"Print all sites defined for the current model" },
	{ "newsite",		"CCc",		"<name> <pattern> [atomlist]", VTypes::NoData,
				"Adds a new site definition to the current model" },
	{ "siteaxes",		"CC",		"<atomlist> <atomlist>", VTypes::NoData,
				"Set the axis definitions for the current site" },

	// System commands
	{ "debug",		"C",		"<mode>", VTypes::NoData,
				"Toggle debugging for the specified mode" },
	{ "gui",		"",		"", VTypes::NoData,
				"Start the GUI (if it is not already active)" },
	{ "help",		"C",		"<command>", VTypes::NoData,
				"Provide short help on the command supplied" },
	{ "seed",		"N",		"<seed>", VTypes::NoData,
				"Set the random seed" },
	{ "quit",		"",		"", VTypes::NoData,
				"Exit the program" },
	{ "version",		"",		"", VTypes::NoData,
				"Print program version information" },

	// Trajectory commands
	{ "addframe",		"c",		"[name]", VTypes::ModelData,
				"Add a new trajectory frame to the current model (which becomes the the current model)" },
	{ "cleartrajectory",	"",		"", VTypes::NoData,
				"Clear any trajectory data in the current model" },
	{ "finaliseframe",	"",		"", VTypes::NoData,
				"Finalise the current trajectory frame" },
	{ "firstframe",		"",		"", VTypes::NoData,
				"Go to the first frame in the current trajectory" },
	{ "lastframe",		"",		"", VTypes::NoData,
				"Go to the last frame in the current trajectory" },
	{ "loadtrajectory",	"C",		"<filename>", VTypes::IntegerData,
				"Load the specified trajectory and associate it to the current model" },
	{ "nextframe",		"",		"", VTypes::NoData,
				"Go to the next frame in the current trajectory" },
	{ "prevframe",		"",		"", VTypes::NoData,
				"Go to the previous frame in the current trajectory" },
	{ "seekframe",		"N",		"<frame>", VTypes::NoData,
				"Jump to the specified frame in the current trajectory" },
	
	// Transformation commands
	{ "axisrotate",		"NNNNnnn|AANnnn",	"<ax> <ay> <ax> <theta> [ox oy oz] | <i> <j> <theta> [ox oy oz]", VTypes::NoData,
				"Rotate the current selection about a defined axis and origin" },
	{ "centre",		"NNN",		"<x> <y> <z>", VTypes::NoData,
				"Centre the atom selection of the current model at the specified coordinates" },
	{ "matrixconvert",	"NNNNNNNNNNNNnnnnnnnnn","<i_sx> <j_sx> <i_sy> <j_sy> <i_sz> <j_sz> <i_dx> <j_dx> <i_dy> <j_dy> <i_dz> <j_dz> [ox oy oz] | <sax> <say> <saz> <sbx> <sby> <sbz> <scx> <scy> <scz> <dax> <day> <daz> <dbx> <dby> <dbz> <dcx> <dcy> <dcz> [ox oy oz]", VTypes::NoData,
				"Transform selected atoms in reference frame specified to destination frame specified" },
	{ "matrixtransform",	"NNNNNNNNNnnn",	"<ax> <ay> <az> <bx> <by> <bz> <cx> <cy> <cz> [ox oy oz]", VTypes::NoData,
				"Transform selected atoms by the matrix supplied" },
	{ "mirror",		"C",		"<axis>", VTypes::NoData,
				"Mirror the atom selection of the current model about its geometric centre in the specified axis" },
	{ "translate",		"NNN",		"<dx> <dy> <dz>", VTypes::NoData,
				"Translate the atom selection of the current model" },
	{ "translateatom",	"NNN",		"<dx> <dy> <dz>", VTypes::NoData,
				"Translate the current atom" },
	{ "translatecell",	"NNN",		"<dx> <dy> <dz>", VTypes::NoData,
				"Translate the current selection along the cell axes by the fractional axes specified" },
	{ "translateworld",	"NNN",		"<dx> <dy> <dz>", VTypes::NoData,
				"Translate the current selection in world (view) coordinates" },

	// Variable Manipulation
	{ "afterstr",		"CC",		"<string> <search>", VTypes::StringData,
				"Return part of the <string> after the first occurrence of <search>" },
	{ "atof",		"C",		"<string>", VTypes::DoubleData,
				"Convert supplied string to floating point number" },
	{ "atoi",		"C",		"<string>", VTypes::IntegerData,
				"Convert supplied string to integer number" },
	{ "beforestr",		"CC",		"<string> <search>", VTypes::StringData,
				"Return part of the <string> before the first occurrence of the character <char>" },
	{ "contains",		"CC",		"<source string> <search string>", VTypes::IntegerData,
				"Return the number of times <search string> occurs in <source string>" },
	{ "ftoa",		"N",		"<number>", VTypes::StringData,
				"Convert supplied real value to a string" },
	{ "itoa",		"N",		"<number>", VTypes::StringData,
				"Convert supplied integer to a string" },
	{ "nint",		"N",		"<number>", VTypes::IntegerData,
				"Return nearest integer to supplied real value" },
	{ "normalise",		"U",		"<vector>", VTypes::DoubleData,
				"Normalise the values of the 3-vector supplied" },
	{ "stripchars",		"^CC",		"<variable> <chars>", VTypes::StringData,
				"Strip all occurrences of the supplied characters from the supplied variable" },

	// Variable Operators
	{ "+",			"..",		"", VTypes::NoData,
				"Internal Operator (+)" },
	{ "&&",			"..",		"", VTypes::NoData,
				"Internal Operator (&&)" },
	{ "=",			"..",		"", VTypes::NoData,
				"Internal Operator (=)" },
	{ "/=",			"..",		"", VTypes::NoData,
				"Internal Operator (/=)" },
	{ "-=",			"..",		"", VTypes::NoData,
				"Internal Operator (-=)" },
	{ "*=",			"..",		"", VTypes::NoData,
				"Internal Operator (*=)" },
	{ "+=",			"..",		"", VTypes::NoData,
				"Internal Operator (+=)" },
	{ "/",			"..",		"", VTypes::NoData,
				"Internal Operator (/)" },
	{ "==",			"..",		"", VTypes::NoData,
				"Internal Operator (==)" },
	{ ">",			"..",		"", VTypes::NoData,
				"Internal Operator (>)" },
	{ ">=",			"..",		"", VTypes::NoData,
				"Internal Operator (>=)" },
	{ "<",			"..",		"", VTypes::NoData,
				"Internal Operator (<)" },
	{ "<=",			"..",		"", VTypes::NoData,
				"Internal Operator (<=)" },
	{ "*",			"..",		"", VTypes::NoData,
				"Internal Operator (*)" },
	{ "-NEG",		".",		"", VTypes::NoData,
				"Internal Operator (negate)" },
	{ "!",			"..",		"", VTypes::NoData,
				"Internal Operator (!)" },
	{ "!=",			"..",		"", VTypes::NoData,
				"Internal Operator (!=)" },
	{ "||",			"..",		"", VTypes::NoData,
				"Internal Operator (||)" },
	{ "X--",		"..",		"", VTypes::NoData,
				"Internal Operator (X--)" },
	{ "X++",		"..",		"", VTypes::NoData,
				"Internal Operator (X++)" },
	{ "^",			"..",		"", VTypes::NoData,
				"Internal Operator (^)" },
	{ "--X",		"..",		"", VTypes::NoData,
				"Internal Operator (--X)" },
	{ "++X",		"..",		"", VTypes::NoData,
				"Internal Operator (++X)" },
	{ "-",			"..",		"", VTypes::NoData,
				"Internal Operator (-)" },
	
	// View
	{ "getview",		"",		"", VTypes::NoData,
				"Print the rotation matrix, camera position, and camera z-rotation for the current model" },
	{ "orthographic",	"",		"", VTypes::NoData,
				"Render in an orthographic projection" },
	{ "perspective",	"n",		"[fov]", VTypes::NoData,
				"Render in a perspective projection" },
	{ "resetview",		"",		"", VTypes::NoData,
				"Reset the camera and rotation for the current model" },
	{ "rotateview",		"NN",		"<x> <y>", VTypes::NoData,
				"Rotate the current model about the x and y axes by the specified amounts" },
	{ "setview",		"NNNNNNNNNNNNn","<ax> <ay> <az> <bx> <by> <bz> <cx> <cy> <cz> <camx> <camyu> <camz> [zrot]", VTypes::NoData,
				"Set the rotation matrix, camera position, and camera z-rotation for the current model" },
	{ "speedtest",		"n",		"[nrender]", VTypes::NoData,
				"Time 100 (or 'nrender') updates of the model display" },
	{ "translateview",	"NNN",		"<dx> <dy> <dz>", VTypes::NoData,
				"Translate the camera for the current model" },
	{ "viewalong",		"NNN",		"<x> <y> <z>", VTypes::NoData,
				"Set the rotation for the current model so the view is along the specified vector" },
	{ "viewalongcell",	"NNN",		"<x> <y> <z>", VTypes::NoData,
				"Set the rotation for the current model so the view is along the specified cell vector" },
	{ "zoomview",		"N",		"<dz>", VTypes::NoData,
				"Zoom in/out the camera - equivalent to 'translateview 0 0 dz'" },
	{ "zrotateview",	"N",		"<dr>", VTypes::NoData,
				"Rotate the model in the plane of the screen" }
};

// Return enumerated command from string
Command::Function Command::command(const char *s)
{
	int result;
	for (result = Command::NoFunction; result < Command::nCommands; result++) if (strcmp(data[result].keyword,s) == 0) break;
	return (Command::Function) result;
}

// Constructor
Command::Command()
{
	// Create pointer list
	initPointers();
}

// Constructor
Command::~Command()
{
}

// Return whether command accepts any arguments
bool CommandData::hasArguments()
{
	return (!(arguments[0] == '\0'));
}

// Execute command
bool Command::call(Command::Function cf, CommandNode *c, ReturnValue &rv)
{
	msg.print(Messenger::Commands, "Calling command '%s' (node is %li)...\n", data[cf].keyword, c);
	return (this->pointers_[cf])(c, aten.current, rv);
}

