/*
	*** User Actions
	*** src/gui/useractions.cpp
	Copyright T. Youngs 2007-2018

	This file is part of Aten.

	Aten is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	Aten is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with Aten.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "gui/useractions.h"
#include "math/constants.h"

ATEN_BEGIN_NAMESPACE

// User action texts (name, nomod, shift, ctrl, alt)
UserAction UserActions[] = {
	{ "", "", "", "", "" },
	{ "Select", 	"Click or click-drag to select",
		"toggle (left click) or add area to selection (left click-drag) or translate (middle click-drag) or rotate in local frame (right click-drag)",
		"remove from selection",
		"",
		0 },
	{ "Select Bound", "Click atom to select bound fragment",
		"add to current selection",
		"remove from selection",
		"",
		0 },
	{ "Select Element", "Click to select all atoms of the same element",
		"add to current selection",
		"remove from selection",
		"",
		0 },
	{ "Select Radial", "",
		"",
		"",
		"",
		0 },
	{ "Measure Distance", "Click two atoms i-j to measure distance",
		"",
		"",
		"",
		0 },
	{ "Measure Angle", "Click three atoms i-j-k to measure angle",
		"",
		"",
		"",
		0 },
	{ "Measure Torsion", "Click four atoms i-j-k-l to measure torsion",
		"",
		"",
		"",
		0 },
	{ "Draw Atoms", "Click in empty space to create an atom of the current drawing element",
		"",
		"",
		"",
		0 },
	{ "Draw Fragments", "Click or click-drag to draw free fragments, or attach to existing atoms (click-drag to rotate)",
		"to replace attached atom instead of creating new bond",
		"cycle over bonds on attachment point (existing atom)",
		"cycle between anchor points on fragment" },
	{ "Transmute", "Click atoms to transmute into current drawing element",
		"to transmute all atoms of the same element as the clicked atom",
		"",
		"",
		0 },
	{ "Delete Atoms/Bonds", "Click individual atoms to delete them",
		"to delete all bonds attached to atom",
		"",
		"",
		0 },
	{ "Probe Atom", "Click individual atoms to view atom information",
		"",
		"",
		"",
		0 },
	{ "Add Hydrogens", "Click single atoms to automatically add hydrogen atoms",
		"",
		"",
		"",
		0 },
	{ "Grow Atom", "Click single atoms to grow additional atoms in selected geometry",
		"grow without bonding",
		"",
		"",
		0 },
	{ "Rotate (XY)", "Click-drag to rotate entire model",
		"modify coordinates of current atom selection",
		"",
		"",
		0 },
	{ "Rotate (Z)", "Click-drag to rotate entire model",
		"modify coordinates of current atom selection",
		"",
		"",
		0 },
	{ "Translate", "Click-drag to move camera",
		"modify coordinates of current atom selection",
		"",
		"",
		0 },
	{ "Zoom Camera", "Click-drag to zoom camera",
		"",
		"",
		"",
		0 },
	{ "Rotate (XY)", "Click-drag to rotate entire model",
		"modify coordinates of current atom selection",
		"",
		"",
		0 },
	{ "Rotate (Z)", "Click-drag to rotate entire model",
		"modify coordinates of current atom selection",
		"",
		"",
		0 },
	{ "Translate", "Click-drag to move camera",
		"modify coordinates of current atom selection",
		"",
		"",
		0 },
	{ "Picking Mode", "Pick two atoms which define the vector shift",
		"",
		"",
		"",
		2 },
	{ "Picking Mode", "Pick two atoms which will define the rotation axis for the transformation",
		"",
		"",
		"",
		2 },
	{ "Picking Mode", "Pick two atoms which define the X-axis of the transformation matrix",
		"",
		"",
		"",
		2 },
	{ "Picking Mode", "Pick two atoms which define the Y-axis of the transformation matrix",
		"",
		"",
		"",
		2 },
	{ "Picking Mode", "Pick two atoms which define the Z-axis of the transformation matrix",
		"",
		"",
		"",
		2 },
	{ "Picking Mode", "Pick two atoms which define the X-axis of the reference matrix for the conversion",
		"",
		"",
		"",
		2 },
	{ "Picking Mode", "Pick two atoms which define the Y-axis of the reference matrix for the conversion",
		"",
		"",
		"",
		2 },
	{ "Picking Mode", "Pick two atoms which define the Z-axis of the reference matrix for the conversion",
		"",
		"",
		"",
		2 },
	{ "Picking Mode", "Pick two atoms which define the X-axis of the target matrix for the conversion",
		"",
		"",
		"",
		2 },
	{ "Picking Mode", "Pick two atoms which define the Y-axis of the target matrix for the conversion",
		"",
		"",
		"",
		2 },
	{ "Picking Mode", "Pick two atoms which define the Z-axis of the target matrix for the conversion",
		"",
		"",
		"",
		2 }
};

ATEN_END_NAMESPACE
