#!/bin/bash

# Script to 'wrap' around git and update ChangeLog and version / date in file.

COMMITFILE="none"
COMMITMSG="none"
COMMITTYPE="none"
BUMP="false"
PUSH="false"
ALL="false"

# Parse CLI arguments / options
USAGE1="commit [-F <filename>] [-m <text>] [-p] [-b]"

while getopts "F:m:bp" options; do
  case $options in
    F ) COMMITFILE=$OPTARG
	COMMITTYPE="file"
        echo "Using file "$COMMITFILE" for commit message.";;
    m ) COMMITMSG=$OPTARG
	COMMITTYPE="msg"
        echo "Using supplied text for commit message.";;
    b ) BUMP="true"
	echo "Version (patch) number will be bumped.";;
    p ) PUSH="true"
	echo "Files will be committed and local changes pushed to server.";;
    \? ) echo -e $USAGE1
         exit 1;;
    * ) echo -e $USAGE1
        exit 1;;
  esac
done

# Check that a commit type was given
if [ "$COMMITTYPE" = "none" ]
then
  echo "No commit message/file was given."
  exit 0
fi

# Bump version if requested
if [ "$BUMP" = "true" ]
then
  ./changeversion bump
else
  ./changeversion
fi

# Commit changes
if [ "$COMMITTYPE" = "file" ]
then
  git commit -a -F $COMMITFILE
fi
if [ "$COMMITTYPE" = "msg" ]
then
  git commit -a -m "$COMMITMSG"
fi

# Push changes to server?
if [ "$PUSH" = "true" ]
then
  git push origin master --tags
fi

exit 0
