#!/bin/bash

# Script to 'wrap' around svn and update ChangeLog and version / date in file.

COMMITFILE="none"
COMMITMSG="none"
COMMITTYPE="none"
TEST="false"
UPDATE="false"

# Parse CLI arguments / options
USAGE1="commit [-F <filename>] [-m <text>] [-t]"

while getopts "F:m:tu" options; do
  case $options in
    F ) COMMITFILE=$OPTARG
	COMMITTYPE="file"
        echo "Using file "$COMMITFILE" for commit message.";;
    m ) COMMITMSG=$OPTARG
	COMMITTYPE="msg"
        echo "Using supplied text for commit message.";;
    t ) TEST="true"
	echo "Test only - no file changes will be made.";;
    u ) UPDATE="true"
	echo "Local source will be updated before commit.";;
    \? ) echo -e $USAGE1
         exit 1;;
    * ) echo -e $USAGE1
        exit 1;;
  esac
done

# Check that a commit type was given
if [ "$COMMITTYPE" = "none" ] && [ "$TEST" = "false" ]
then
  echo "No commit message/file was given."
  exit 0
fi

# Update if requested
if [ "$UPDATE" = "true" ]
then
  svn update
fi

# Determine current svn version number and increase it by one.
OLDREV=`svn info -r HEAD | grep Revision | sed "s/Revision: \([0-9]*\)/\1/g"`
let NEWREV=OLDREV+1
echo "Current version is revision $OLDREV - committed version will be revision $NEWREV..."

# Determine svn URL
grep 'Version:' ./doc/aten.xml | sed -e 's/Version: \([0-9\.]\+\)/\1/g'
URL=`svn info | grep URL | sed -e "s/URL: \(.*\)/\1/g" -e "s/https/http/g"`
echo "Subversion repository is: "$URL

# Get current date and time
DATE=`date "+%a %d %b - %H:%M"`

# Change URL, revision, and date in src/main/version.h
echo "Setting #defines in src/main/version.h..."
cp src/main/version.h src/main/version.h.orig
DESTFILE=src/main/version.h
if [ "$TEST" = "true" ]
then
  DESTFILE=src/main/version.h.test
fi
sed -e "s/#define ATENREVISION \"\(.*\)\"/#define ATENREVISION \"$NEWREV\"/g" -e "s/#define ATENDATE \".*\"/#define ATENDATE \"$DATE\"/g" -e "s,#define ATENURL \".*\",#define ATENURL \"$URL\",g" src/main/version.h.orig > $DESTFILE
echo -n "     version.h (ATENREVISION) : "
grep '#define ATENREVISION' $DESTFILE | sed -e 's/#define ATENREVISION "\(.*\)"/\1/g'
echo -n "     version.h (ATENDATE)     : "
grep '#define ATENDATE' $DESTFILE | sed -e 's/#define ATENDATE "\(.*\)"/\1/g'
echo -n "     version.h (ATENURL)      : "
grep '#define ATENURL' $DESTFILE | sed -e 's/#define ATENURL "\(.*\)"/\1/g'

# Update ChangeLog
#TODO

# If this was just a test we're done at this point
if [ "$TEST" = "true" ]
then
  exit 0
fi

# Commit changes
if [ "$COMMITTYPE" = "file" ]
then
  svn commit -F $COMMITFILE
fi
if [ "$COMMITTYPE" = "msg" ]
then
  svn commit -m "$COMMITMSG"
fi

exit 0
