#!/bin/bash

# Script to 'wrap' around svn and update ChangeLog and version / date in file.

COMMITFILE="none"
COMMITMSG="none"
COMMITTYPE="none"

# Parse CLI arguments / options
USAGE1="commit [-F <filename>] [-m <text>]"

while getopts "F:m:" options; do
  case $options in
    F ) COMMITFILE=$OPTARG
	COMMITTYPE="file"
        echo "Using file "$COMMITFILE" for commit message.";;
    m ) COMMITMSG=$OPTARG
	COMMITTYPE="msg"
        echo "Using supplied text for commit message.";;
    \? ) echo -e $USAGE1
         exit 1;;
    * ) echo -e $USAGE1
        exit 1;;
  esac
done

# Check that a commit type was given
if [ "$COMMITTYPE" = "none" ]
then
  echo "No commit message/file was given."
  exit 0
fi

# Determine current svn version number and increase it by one.
OLDREV=`svn info | grep Revision | sed "s/Revision: \([0-9]*\)/\1/g"`
let NEWREV=OLDREV+1
echo "Current version is revision $OLDREV - commited version will be revision $NEWREV..."

# Determine svn URL
URL=`svn info | grep URL | sed "s/URL: \(.*\)/\1/g"`
echo "Subversion repository is: "$URL

# Get current date and time
DATE=`date "+%a %d %b - %H:%M"`

# Change URL, revision, and date in src/base/master.h
echo "Setting #defines in src/base/master.h..."
cp src/base/master.h src/base/master.h.orig
sed -e "s/#define ATENREVISION \"\(.*\)\"/#define ATENREVISION \"$NEWREV\"/g" -e "s/#define ATENDATE \".*\"/#define ATENDATE \"$DATE\"/g" -e "s,#define ATENURL \".*\",#define ATENURL \"$URL\",g" src/base/master.h.orig > src/base/master.h
echo -n "        master.h (ATENREVISION) : "
grep '#define ATENREVISION' src/base/master.h | sed -e 's/#define ATENREVISION "\(.*\)"/\1/g'
echo -n "        master.h (ATENDATE)     : "
grep '#define ATENDATE' src/base/master.h | sed -e 's/#define ATENDATE "\(.*\)"/\1/g'
echo -n "        master.h (ATENURL)      : "
grep '#define ATENURL' src/base/master.h | sed -e 's/#define ATENURL "\(.*\)"/\1/g'

# Update ChangeLog
#TODO

# Commit changes
if [ "$COMMITTYPE" = "file" ]
then
  svn commit -F $COMMITFILE
fi
if [ "$COMMITTYPE" = "msg" ]
then
  svn commit -m $COMMITMSG
fi

exit 0
