#!/bin/bash

# -------------------------------
#
# Start Build of Mac Packages
#
# -------------------------------

# Remove old build directory and create new one
#cd ~
#rm -rf aten-build
#mkdir aten-build
#cd aten-build

# Get latest source and setup build
#svn co http://aten.googlecode.com/svn/trunk ./aten-latest
#cd aten-latest
REVISION=`svn info -r HEAD | grep Revision | sed "s/Revision: \([0-9]*\)/\1/g"`
cmake -G Xcode

# Loop over SDK versions as appropriate
for SDK in 10.6 10.5 # 10.4
do

  echo "Building MacOSX release "$SDK
  GCC_VERSION="4.2"
  if [ "$SDK" = "10.4" ]
  then
    GCC_VERSION="4.0"
  fi

  # Clean previous build
  rm -rf ./bin/
  make clean

  # Build basic app package and check for success
  xcodebuild -configuration Release -sdk macosx$SDK GCC_VERSION=$GCC_VERSION GCC_OPTIMIZATION_LEVEL="s"
  if [ ! -e bin/Release/Aten.app/Contents/MacOS/Aten ];
  then
    echo "Build failed!"
    exit 1
  fi

  # Descend into created app directory
  cd bin/
  cp -r Release Aten-r$REVISION
  cd Aten-r$REVISION

  # Use macdeployqt to setup most (but not all) Framework data
  macdeployqt Aten.app -verbose=2

  # Copy Aten's data to SharedSupport
  cp -r ../../data ./Aten.app/Contents/SharedSupport

  # Copy in additional data for dmg file (icon, license etc)
  cp ../../extra/aten.icns ./Aten.app/Contents/Resources

  # Copy in missing libqsvg.dylib iconengine and QtSvg Framework, and change DyLib links to reference the package 
  cp /Developer/Applications/Qt/plugins/imageformats/libqsvg.dylib ./Aten.app/Contents/PlugIns/imageformats/
  mkdir -p Aten.app/Contents/Frameworks/QtXml.framework/Resources Aten.app/Contents/Frameworks/QtXml.framework/Versions/4
  #cp -a /Library/Frameworks/QtSvg.framework/Versions/4/QtSvg Aten.app/Contents/Frameworks/QtSvg.framework/Versions/4/
  cp -a /Library/Frameworks/QtXml.framework/Versions/4/QtXml Aten.app/Contents/Frameworks/QtXml.framework/Versions/4/
  for a in QtSvg QtXml QtCore QtGui; 
  do 
    install_name_tool -change "\$a.framework/Versions/4/\$a" "@executable_path/../Frameworks/\$a.framework/Versions/4/\$a" Aten.app/Contents/PlugIns/imageformats/libqsvg.dylib 
#  install_name_tool -change "\$a.framework/Versions/4/\$a" "@executable_path/../Frameworks/\$a.framework/Versions/4/\$a" Aten.app/Contents/Frameworks/QtSvg.framework/Versions/4/QtSvg
    install_name_tool -change "\$a.framework/Versions/4/\$a" "@executable_path/../Frameworks/\$a.framework/Versions/4/\$a" Aten.app/Contents/Frameworks/QtXml.framework/Versions/4/QtXml
  done
  #install_name_tool -id "@executable_path/../Frameworks/QtSvg.framework/Versions/4/QtSvg" Aten.app/Contents/Frameworks/QtSvg.framework/Versions/4/QtSvg
  install_name_tool -id "@executable_path/../Frameworks/QtXml.framework/Versions/4/QtXml" Aten.app/Contents/Frameworks/QtXml.framework/Versions/4/QtXml

  # Add extra files to dir, ready for package creation
  cp ../../COPYING .COPYING
  cp ../../extra/aten.icns .VolumeIcon.icns
  cp ../../extra/Aten.DS_Store .DS_Store
  mkdir .background
  cp ../../extra/background.png .background/

  # Create final dmg
  cd ../
  echo -n "Creating dmg in: "
  pwd
  ~/bin/pkg-dmg --source Aten-r$REVISION --target Aten.dmg --volname Aten-r$REVISION --icon Aten-r$REVISION/.VolumeIcon.icns --license Aten-r$REVISION/.COPYING --symlink /Applications:"/Applications"

  # Rename dmg
  mv Aten.dmg Aten-r$REVISION-OSX$SDK.dmg

done
