#!/bin/bash

# Fix MathML usage in sgmltools-lite
#export SGML_CATALOG_FILES=~/.docbook/catalog.txt

# Update version info...
DESTFILE=../src/main/version.h
ATENREVISION=`grep '#define ATENREVISION' $DESTFILE | sed -e 's/#define ATENREVISION "\(.*\)"/\1/g'`
ATENVERSION=`grep '#define ATENVERSION' $DESTFILE | sed -e 's/#define ATENVERSION "\(.*\)"/\1/g'`
ATENDATE=`grep '#define ATENDATE' $DESTFILE | sed -e 's/#define ATENDATE "\(.*\)"/\1/g'`
ATENURL=`grep '#define ATENURL' $DESTFILE | sed -e 's/#define ATENURL "\(.*\)"/\1/g'`
echo "     version.h (ATENREVISION) : $ATENREVISION"
echo "     version.h (ATENVERSION)  : $ATENVERSION"
echo "     version.h (ATENDATE)     : $ATENDATE"
echo "     version.h (ATENURL)      : $ATENURL"

rm -rf aten aten-versioned.xml
sed -e "s/ATENREVISION/$ATENREVISION/g" -e "s,ATENURL,$ATENURL,g" -e "s/ATENDATE/$ATENDATE/g" -e "s/ATENVERSION/$ATENVERSION/g" aten.xml > aten-versioned.xml

#sgmltools -b html $a-versioned.xml

mkdir aten
#docbook2html --output aten aten-versioned.xml
docbook2pdf --output aten.pdf aten-versioned.xml
rm aten-versioned.xml
