/*
	*** Command Function Definitions
	*** src/nucommand/commands.cpp
	Copyright T. Youngs 2007-2009

	This file is part of Aten.

	Aten is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	Aten is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with Aten.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "nucommand/commands.h"
#include "parser/commandnode.h"
#include "main/aten.h"
#include "base/bundle.h"
#include "parser/tree.h"

/* Argument Specification Tokens:
       Char	Meaning		Acceptable Types in VTypes
	N	Number		IntegerData, RealData
	C	Character	StringData
	S	Any Simple	IntegerData, RealData, StringData
	U	Vector		VectorData
	B	Boolean		Any
	A	Atom/Id		IntegerData, AtomData
	M	Model/ID/Name	ModelData, StringData, IntegerData
	P	Pattern/ID/Name	PatternData, StringData, IntegerData
	X	Pointer		Any pointer object
	V	Variable	Any simple variable (not path)
	Z	Any		Any
	*	<Repeat>	Any number of the last type again
	^	<Require Var>	Next token must be a modifiable variable and not a constant
	[]	<Cluster>	Surrounds groups of optional arguments that must be specified together
	|	<Or>		Separates alternative lists of arguments for the command
*/

// Command action
NuCommandData NuCommand::data[NuCommand::nCommands] = {

	// AST Nodes
	{ "_nofunction",	"",		"", NuVTypes::NoData,
				"" },
	{ "_joiner",		"",		"", NuVTypes::NoData,
				"" },
	{ "_initialisations",	"V*",		"<variable| variable = expr> ...", NuVTypes::NoData,
				"" },

	// Analysis commands
	{ "finalise",		"",		"", NuVTypes::NoData,
				"Finalise all calculated quantities" },
	{ "frameanalyse",	"",		"", NuVTypes::NoData,
				"Analyse quantities for the current trajectory frame" },
	{ "geometry",		"CNNNCNNnn",	"<name> <min> <binwidth> <nbins> <filename> <site1> <site2> [site3 [site4]]", NuVTypes::NoData,
				"Calculate geometries" },
	{ "modelanalyse",	"",		"", NuVTypes::NoData,
				"Analyse quantities for the current model" },
	{ "pdens",		"CNNCNN",	"<name> <griddelta> <nsteps> <filename> <site1> <site2> ", NuVTypes::NoData,
				"Request calculation of a probability density between sites" },
	{ "listjobs",		"",		"", NuVTypes::NoData,
				"Print the current list of quantities to calculate" },
	{ "rdf",		"CNNNCNN",	"<name> <rmin> <binwidth> <nbins> <filename> <site1> <site2>", NuVTypes::NoData,
				"Request calculation of radial distribution function between sites" },
	{ "savequantities",	"",		"", NuVTypes::NoData,
				"Save calculated quantities to file" },
	{ "trajanalyse",	"NNn",		"<startframe> <frameskip> [nframes]", NuVTypes::NoData,
				"Analyse quantities for all frames in current trajectory" },
	
	// Atom commands
	{ "atomstyle",		"Ca",		"<style> [atom/id]", NuVTypes::NoData,
				"Set the individual style of the current atom selection (or supplied atom)" },
	{ "getatom",		"N",		"<id>", NuVTypes::AtomData,
				"Retrieve pointer for atom id specified, returning a reference to it" },
	{ "hide",		"a",		"[atom/id]", NuVTypes::NoData,
				"Hide the current selection of atoms (or supplied atom)" },
	{ "setcharge",		"Na",		"<q> [atom/id]", NuVTypes::NoData,
				"Set the charge of the current (or specified) atom" },
	{ "setcoords",		"NNNa",		"<x> <y> <z> [atom/id]", NuVTypes::NoData,
				"Set the coordinates of the current (or specified) atom" },
	{ "setelement",		"Ga",		"<element> [atom/id]", NuVTypes::NoData,
				"Set the element of the current (or specified) atom" },
	{ "setforces",		"NNNa",		"<fx> <fy> <fz> [atom/id]", NuVTypes::NoData,
				"Set the forces of the current (or specified) atom" },
	{ "setfx",		"Na",		"<fx> [atom/id]", NuVTypes::NoData,
				"Set the x force of the current (or specified) atom" },
	{ "setfy",		"Na",		"<fy> [atom/id]", NuVTypes::NoData,
				"Set the y force of the current (or specified) atom" },
	{ "setfz",		"Na",		"<fz> [atom/id]", NuVTypes::NoData,
				"Set the z force of the current (or specified) atom" },
	{ "setid",		"Na",		"<id> [atom/id]", NuVTypes::NoData,
				"Set the id of the current (or specified) atom" },
	{ "setrx",		"Na",		"<rx> [atom/id]", NuVTypes::NoData,
				"Set the x coordinate of the current (or specified) atom" },
	{ "setry",		"Na",		"<ry> [atom/id]", NuVTypes::NoData,
				"Set the y coordinate of the current (or specified) atom" },
	{ "setrz",		"Na",		"<rz> [atom/id]", NuVTypes::NoData,
				"Set the z coordinate of the current (or specified) atom" },
	{ "setvelocities",	"NNNa",		"<vx> <vy> <vz> [atom/id]", NuVTypes::NoData,
				"Set the velocities of the current (or specified) atom" },
	{ "setvx",		"Na",		"<vx> [atom/id]", NuVTypes::NoData,
				"Set the x velocity of the current (or specified) atom" },
	{ "setvy",		"Na",		"<vy> [atom/id]", NuVTypes::NoData,
				"Set the y velocity of the current (or specified) atom" },
	{ "setvz",		"Na",		"<vz> [atom/id]", NuVTypes::NoData,
				"Set the z velocity of the current (or specified) atom" },
	{ "show",		"a",		"[atom/id]", NuVTypes::NoData,
				"Show (make visible) the current selection of atoms (or supplied atom)" },
	{ "showall",		"",		"", NuVTypes::NoData,
				"Show all atoms in the current model" },

	// Bonding commands
	{ "augment",		"",		"", NuVTypes::NoData,
				"Automatically augment all bonds in the current model" },
	{ "bondtolerance",	"n",		"<tolerance>", NuVTypes::NoData,
				"Set bonding tolerance for automatic calculation" },
	{ "clearbonds",		"",		"", NuVTypes::NoData,
				"Delete all bonds in the current model" },
	{ "clearselectedbonds",	"",		"", NuVTypes::NoData,
				"Delete all bonds in the current selection" },
	{ "newbond",		"AAs",		"<atom1> <atom2> [bondtype]", NuVTypes::NoData,
				"Create a bond between specified atoms" },
	{ "newbondid",		"AAs",		"<id1> <id2> [bondtype]", NuVTypes::NoData,
				"Create a bond between atoms with ids specified" },
	{ "rebond",		"",		"", NuVTypes::NoData,
				"Calculate bonding in the current model" },
	{ "rebondpatterns",	"",		"", NuVTypes::NoData,
				"Calculate bonds between atoms, restricted to atoms in pattern molecules" },
	{ "rebondselection",	"",		"", NuVTypes::NoData,
				"Calculate bonds between atoms in the current selection" },

	// Build commands
	{ "addhydrogen",	"a",		"[atom|id]", NuVTypes::NoData,
				"Hydrogen satisfy all (or specified) atom in model" },
	{ "bohr",		"X*",		"<object> [object...]", NuVTypes::NoData,
				"Convert coordinates in the specified object(s) from Angstroms to Bohr" },
	{ "chain",		"Neeee",	"<element> [bondtype] | <element> <x> <y> <z> [bondtype]", NuVTypes::AtomData,
				"Create a new atom in the current model, bound to the last" },
	{ "endchain",		"",		"", NuVTypes::AtomData,
				"End the current bond chain (the next call to 'chain' will create an unbound atom)" },
	{ "insertatom",		"SN[nnn]",	"<element> <id> [x y z]", NuVTypes::AtomData,
				"Insert a new atom into the model such that it has the ID specified" },
	{ "locate",		"NNN",		"<x> <y> <z>", NuVTypes::NoData,
				"Position pen at specified coordinates" },
	{ "move",		"NNN",		"<dx> <dy> <dz>", NuVTypes::NoData,
				"Move pen by specified coordinates" },
	{ "movetoend",		"",		"", NuVTypes::NoData,
				"Move current atom selection to end of list" },
	{ "movetostart",	"",		"", NuVTypes::NoData,
				"Move current atom selection to start of list" },
	{ "newatom",		"S[nnn]",	"<element> [x y z]", NuVTypes::AtomData,
				"Create a new atom in the current model" },
	{ "newatomfrac",	"SNNN",		"<element> <fracx> <fracy> <fracz>", NuVTypes::AtomData,
				"Create a new atom in the current model, converting fractional coordinates to real coordinates" },
	{ "reorder",		"",		"", NuVTypes::NoData,
				"Reorder atoms in the current selection such that bond partners have adjacent atom IDs" },
	{ "resetpen",		"",		"", NuVTypes::NoData,
				"Reset the pen orientation to the identity matrix (but leave the current position intact)" },
	{ "rotx",		"N",		"<angle>", NuVTypes::NoData,
				"Rotate pen about its x axis by given angle" },
	{ "roty",		"N",		"<angle>", NuVTypes::NoData,
				"Rotate pen about its y axis by given angle" },
	{ "rotz",		"N",		"<angle>", NuVTypes::NoData,
				"Rotate pen about its z axis by given angle" },
	{ "shiftdown",		"n",		"[n]", NuVTypes::NoData,
				"Shift current atom selection down 1 (or 'n') places" },
	{ "shiftup",		"n",		"[n]", NuVTypes::NoData,
				"Shift current atom selection up 1 (or 'n') places" },
	{ "transmute",		"S",		"<element>", NuVTypes::NoData,
				"Transmute selection to element given" },
	
	// Cell commands
	{ "addgenerator",	"C",		"<generator>", NuVTypes::NoData,
				"Manually add a spacegroup generator definition to the current model's cell" },
	{ "adjustcell",		"CN",		"<quantity> <change>", NuVTypes::NoData,
				"Adjust a single value of the current cell specification (e.g. <quantity> = a, beta, cz, etc.)" },
	{ "cell",		"NNNNNN",	"<a> <b> <c> <alpha> <beta> <gamma>", NuVTypes::NoData,
				"Set or create a unit cell for the current model from lengths/angles provided" },
	{ "cellaxes",		"NNNNNNNNN",	"<ax> <ay> <az> <bx> <by> <bz> <cx> <cy> <cz>", NuVTypes::NoData,
				"Set or create a unit cell for the current model from the cell axes provided" },
	{ "fold",		"",		"", NuVTypes::NoData,
				"Fold atoms into model's unit cell" },
	{ "foldmolecules",	"",		"", NuVTypes::NoData,
				"Fold molecules (defined by patterns) so that they are unbroken across cell boundaries" },
	{ "fractoreal",		"",		"", NuVTypes::NoData,
				"Convert (assumed) fractional model coordinates to real coordinates" },
	{ "nocell",		"", 		"", NuVTypes::NoData,
				"Remove any cell definition from the current model" },
	{ "pack",		"",		"", NuVTypes::NoData,
				"Pack the unit cell with symmetry operators list in associated spacegroup" },
	{ "printcell",		"",		"", NuVTypes::NoData,
				"Print the unit cell of the current model" },
	{ "replicate",		"NNNNNN",	"<negx> <negy> <negz> <posx> <posy> <posz>", NuVTypes::NoData,
				"Replicate the cell along the directions given" },
	{ "rotatecell",		"CN",		"<axis> <angle>", NuVTypes::NoData,
				"Rotate the cell and its contents about the specified orthogonal axis (x, y, or z)" },
	{ "scale",		"NNN",		"<x> <y> <z>", NuVTypes::NoData,
				"Scale the unit cell and atomic positions of the current model" },
	{ "scalemolecules",	"NNN",		"<x> <y> <z>", NuVTypes::NoData,
				"Scale the unit cell and molecular positions of the current model" },
	{ "setcell",		"CN",		"<quantity> <value>", NuVTypes::NoData,
				"Set a single value of the current cell specification (e.g. <quantity> = a, beta, cz, etc.)" },
	{ "spacegroup",		"S",		"<spgrp>", NuVTypes::NoData,
				"Set the spacegroup for the current model" },
	
	// Charge commands
	{ "chargeff",		"",		"", NuVTypes::NoData,
				"Charge atoms in the model according to their forcefield atom types" },
	{ "chargefrommodel",	"",		"", NuVTypes::NoData,
				"Charge atoms in the current trajectory frame from the parent model" },
	{ "chargepatom",	"NN",		"<id> <q>", NuVTypes::NoData,
				"Set charges for specific atom id in all molecules of the current pattern" },
	{ "charge",		"N",		"<q>", NuVTypes::NoData,
				"Set charges of atoms in the current selection" },
	{ "chargetype",		"CN",		"<type> <q>", NuVTypes::NoData,
				"Set charges of all atoms of the given type" },
	{ "clearcharges",	"",		"", NuVTypes::NoData,
				"Zero all charges in the current model" },

	// Colourscale commands
	{ "addpoint",		"NNNNNn",	"<scaleid> <value> <r> <g> <b> [a]", NuVTypes::NoData,
				"Add a new point to the specified colourscale" },
	{ "clearpoints",	"N",		"<scaleid>", NuVTypes::NoData,
				"Clear all points from the specified colourscale" },
	{ "listscales",		"",		"", NuVTypes::NoData,
				"List details on all colourscales" },
	{ "removepoint",	"NN",		"<scaleid> <point>", NuVTypes::NoData,
				"Remove the selected point from the specified colourscale" },
	{ "scalename",		"Nc",		"<scaleid> [name]", NuVTypes::StringData,
				"Print (or set) the name of the colourscale specified" },
	{ "scalevisible",	"NB",		"<scaleid> true|false", NuVTypes::NoData,
				"Set the visibility of the specified colourscale" },
	{ "setpoint",		"NNNNNNn",	"<scaleid> <point> <value> <r> <g> <b> [a]", NuVTypes::NoData,
				"Set an existing point on the specified colourscale" },
	{ "setpointcolour", 	"NNNNNn",	"<scaleid> <point> <r> <g> <b> [a]", NuVTypes::NoData,
				"Set the colour for an existing colourscale point" },
	{ "setpointvalue", 	"NNN",		"<scaleid> <point> <value>", NuVTypes::NoData,
				"Set the value for an existing colourscale point" },

	// Disordered Builder Commands
	{ "disorder",		"N",		"<nsteps>", NuVTypes::NoData,
				"Run the disordered builder" },
	{ "listcomponents",	"",		"", NuVTypes::NoData,
				"Print a list of the components requested in the disordered builder" },
	{ "nmols",		"N",		"<n>", NuVTypes::NoData,
				"Set the number of molecules required for the component" },
	{ "region",		"CNNNNNNB",	"<shape> <cx> <cy> <cz> <x> <y> <z> <overlap?>", NuVTypes::NoData,
				"Set the shape, centre, size, and overlap flag of the region for the current model" },
	{ "regioncentre",	"NNN",		"<x> <y> <z>", NuVTypes::NoData,
				"Set the region centre of the current model" },
	{ "regioncentreffrac",	"NNN",		"<x> <y> <z>", NuVTypes::NoData,
				"Set the region centre of the current model (fractional coordinates)" },
	{ "regionfrac",		"CNNNNNNB",	"<shape> <cx> <cy> <cz> <x> <y> <z> <overlap?>", NuVTypes::NoData,
				"Set the shape, centre, size, and overlap flag of the region for the current model (fractional coordinates)" },
	{ "regiongeometry",	"NNNN",		"<x> <y> <z> [l]", NuVTypes::NoData,
				"Set the region geometry of the current model" },
	{ "regiongeometryfrac",	"NNNn",		"<x> <y> <z> [l]", NuVTypes::NoData,
				"Set the region geometry of the current model (fractional coordinates)" },
	{ "regionoverlap",	"B",		"<overlap?>", NuVTypes::NoData,
				"Set the overlap flag of the current model" },
	{ "regionshape",	"C",		"<shape>", NuVTypes::NoData,
				"Set the region shape of the current model" },
	{ "vdwscale",		"n",		"[scale]", NuVTypes::RealData,
				"Print (or set) the VDW scaling factor to use in the disordered builder" },

	// Edit commands
	{ "copy",		"",		"", NuVTypes::NoData,
				"Copy selected atoms" },
	{ "cut",		"",		"", NuVTypes::NoData,
				"Cut the selected atoms" },
	{ "delete",		"",		"", NuVTypes::NoData,
				"Delete selected atoms" },
	{ "paste",		"nnn",		"[dx] [dy] [dz]", NuVTypes::NoData,
				"Paste previously-cut or copied atoms to the model (with optional shift from original position" },
	{ "redo",		"",		"", NuVTypes::NoData,
				"Redo last change" },
	{ "undo",		"",		"", NuVTypes::NoData,
				"Undo last change" },

	// Energy commands
	{ "frameenergy",	"",		"", NuVTypes::RealData,
				"Calculate the energy of the current trajectory frame" },
	{ "modelenergy",	"",		"", NuVTypes::RealData,
				"Calculate the energy of the current model" },
	{ "printelec",		"",		"", NuVTypes::NoData,
				"Print the electrostatic pattern matrix of the last calculated energy" },
	{ "printewald",		"",		"", NuVTypes::NoData,
				"Print the Ewald decomposition of the last calculated energy" },
	{ "printinter",		"",		"", NuVTypes::NoData,
				"Print the total intermolecular pattern matrix of the last calculated energy" },
	{ "printintra",		"",		"", NuVTypes::NoData,
				"Print the total intramolecular pattern matrix of the last calculated energy" },
	{ "printenergy",	"",		"", NuVTypes::NoData,
				"Print a short description of the last calculated energy" },
	{ "printsummary",	"",		"", NuVTypes::NoData,
				"Print a one-line summary of the last calculated energy" },
	{ "printvdw",		"",		"", NuVTypes::NoData,
				"Print the VDW pattern matrix of the last calculated energy" },

	// Flow control
	{ "break",		"",		"", NuVTypes::NoData,
				"Exit from the current for loop" },
	{ "continue",		"",		"", NuVTypes::NoData,
				"Skip to the next iteration of the current loop" },
	{ "end",		"",		"", NuVTypes::NoData,
				"End the current for/if block" },
	{ "for",		"_",		"(<var> = <startval>,<finalval>[,<increment>]) { ... }", NuVTypes::NoData,
				"" },
	{ "if",			"_",		"(<expression> <condition> <expression>) { ... } [else { ... }]", NuVTypes::NoData,
				"Perform a conditional test between the supplied expressions (or variables or constants)" },
	{ "_TERMINATE_",	"",		"", NuVTypes::NoData,
				"" },
	
	// Force commands
	{ "frameforces",	"",		"", NuVTypes::NoData,
				"Calculate forces for the current trajectory frame" },
	{ "modelforces",	"",		"", NuVTypes::NoData,
				"Calculate forces for the current model" },
	{ "printforces",	"",		"", NuVTypes::NoData,
				"Print calculated forces for the current model" },
	
	// Forcefield commands
	{ "angledef",		"CCCCNnnnnn", "<form> <name1> <name2> <name3> <data1> [data2 ... data6]", NuVTypes::NoData,
				"Add an angle definition to the current forcefield." },
	{ "bonddef",		"CCCNnnnnn", "<form> <name1> <name2> <data1> [data2 ... data6]", NuVTypes::NoData,
				"Add a bond definition to the current forcefield." },
	{ "clearmap",		"",		"", NuVTypes::NoData,
				"Clear manual type mapping list." },
	{ "createexpression",	"",		"", NuVTypes::NoData,
				"Create and fill a forcefield expression for the current model" },
	{ "defaultff",		"C",		"<ff>", NuVTypes::NoData,
				"Make named forcefield the default for occasions where no other is specified." },
	{ "equivalents",	"CC",		"<name> <'names...'>", NuVTypes::NoData,
				"Define forcefield equivalents" },
	{ "ffmodel",		"c",		"[name]", NuVTypes::NoData,
				"Associate current (or named) forcefield to current model" },
	{ "ffpattern",		"p",		"[pattern|id|name]", NuVTypes::NoData,
				"Associate current forcefield to current pattern" },
	{ "finaliseff",		"",		"", NuVTypes::NoData,
				"Finalise current forcefield." },
	{ "genconvert",		"N*",		"<data1> [data2..data10]", NuVTypes::NoData,
				"Set energetic generator data to convert" },
	{ "generator",		"NNnnnnnnnnn",	"<typeId> <data1> [data2...data10]", NuVTypes::NoData,
				"Set generator data for specified atom type" },
	{ "getff",		"C",		"<name>", NuVTypes::ForcefieldData,
				"Select named (loaded) forcefield and make it current, and return a reference to it" },
	{ "interdef",		"CNNNnnnnn", "<form> <typeid> <charge> <data1> [data2...data6]", NuVTypes::NoData,
				"Add a new interatomic definition to the current forcefield" },
	{ "loadff",		"Cc",		"<filename> [name]", NuVTypes::ForcefieldData,
				"Load forcefield" },
	{ "map",		"C*",		"<name=element,...>", NuVTypes::NoData,
				"Add typename mappings" },
	{ "newff",		"C",		"<name>", NuVTypes::NoData,
				"Create a new, empty forcefield." },
	{ "printsetup",		"",		"", NuVTypes::NoData,
				"Print the current energy/force calculation setup" },
	{ "rules",		"C",		"<rules set>", NuVTypes::NoData,
				"Set rules set to use for parameter generation" },
	{ "saveexpression",	"CC",		"<format> <filename>", NuVTypes::NoData,
				"Save the expression for the current model" },
	{ "torsiondef",		"CCCCCNnnnnn", "<form> <name1> <name2> <name3> <name4> <data1> [data2 ... data6]", NuVTypes::NoData,
				"Add a torsion definition to the current forcefield." },
	{ "typedef",		"NCSCc", "<typeid> <name> <element> <type> [description]", NuVTypes::NoData,
				"Add an atom type to the current forcefield." },
	{ "typemodel",		"",		"", NuVTypes::NoData,
				"Perform atom typing on the current model" },
	{ "typetest",		"NN",		"<id> <id>", NuVTypes::NoData,
				"Test atomtype score on atom id provided" },
	{ "units",		"C",		"<energy unit>", NuVTypes::NoData,
				"Set energy unit of forcefield" },

	// Glyph commands
	{ "autoellipsoids",	"c*",		"[options]", NuVTypes::NoData,
				"Automatically add ellipsoids to the current atom selection" },
	{ "autopolyhedra",	"c*",		"[options]", NuVTypes::NoData,
				"Automatically add polyhedra to the current atom selection" },
	{ "glyphatomf",		"Na",		"<n> [atom/id]", NuVTypes::NoData,
				"Set current (or specified) atom's forces as data <n> in current glyph" },
	{ "glyphatomr",		"Na",		"<n> [atom/id]", NuVTypes::NoData,
				"Set current (or specified) atom's coordinates as data <n> in current glyph" },
	{ "glyphatomv",		"Na",		"<n> [atom/id]", NuVTypes::NoData,
				"Set current (or specified) atom's velocities data <n> in current glyph" },
	{ "glyphatomsf",	"Aaaa",		"<atom/id> [atom/id] [atom/id] [atom/id]", NuVTypes::NoData,
				"Set all atom forces data in current glyph" },
	{ "glyphatomsr",	"Aaaa",		"<atom/id> [atom/id] [atom/id] [atom/id]", NuVTypes::NoData,
				"Set all atom coordinates data in current glyph" },
	{ "glyphatomsv",	"Aaaa",		"<atom/id> [atom/id] [atom/id] [atom/id]", NuVTypes::NoData,
				"Set all atom velocities data in current glyph" },
	{ "glyphcolour",	"NNNNn",	"<n> <r> <g> <b> [a]", NuVTypes::NoData,
				"Set colour data <n> in current glyph" },
	{ "glyphdata",		"NNnn",		"<n> <x> [y] [z]", NuVTypes::NoData,
				"Set vector data <n> in current glyph" },
	{ "glyphsolid",		"B",		"<solid?>", NuVTypes::NoData,
				"Set the glyph to be drawn in solid (true) or wireframe (false) modes (glyph-permitting)" },
	{ "glyphtext",		"C",		"<text>", NuVTypes::NoData,
				"Set text data in current glyph" },
	{ "newglyph",		"Cc",		"<style> [options]", NuVTypes::NoData,
				"Add a glyph with the specified style to the current model" },

	// Grid commands
	{ "addgridpoint",	"NNNN",		"<ix> <iy> <iz> <value>", NuVTypes::NoData,
				"Set specific gridpoint value" },
	{ "addnextgridpoint",	"N",		"<value>", NuVTypes::NoData,
				"Add next gridpoint value" },
	{ "finalisegrid",	"",		"", NuVTypes::NoData,
				"Finalise grid import" },
	{ "getgrid",		"N",		"<id>", NuVTypes::GridData,
				"Retrieve data for grid with id specified, and return a reference to it" },
	{ "gridalpha",		"N",		"<alpha>", NuVTypes::NoData,
				"Set the alpha value of the surface (when not using a colourscale)" },
	{ "gridaxes",		"NNNNNNNNN",	"<ax> <ay> <az> <bx> <by> <bz> <cx> <cy> <cz>", NuVTypes::NoData,
				"Set axis system for the current grid" },
	{ "gridcolour",		"NNNn",		"<r> <g> <b> [a]", NuVTypes::NoData,
				"Set the (positive) colour of the surface (when not using a colourscale)" },
	{ "gridcolournegative",	"NNNn",		"<r> <g> <b> [a]", NuVTypes::NoData,
				"Set the negative colour of the surface (when not using a colourscale)" },
	{ "gridcolourscale",	"N",		"<scaleID>", NuVTypes::NoData,
				"Links the surface to the specified colour scale (or zero to return to internal colour)" },
	{ "gridcubic",		"N",		"<l>", NuVTypes::NoData,
				"Setup a cubic axis system for the current grid" },
	{ "gridcutoff",		"N",		"<cutoff>", NuVTypes::NoData,
				"Set the cutoff for the current grid" },
	{ "gridlooporder",	"S",		"<xyz|zyx|213...>", NuVTypes::NoData,
				"Set the loop ordering to use in 'addnextgridpoint'" },
	{ "gridorigin",		"NNN",		"<x> <y> <z>", NuVTypes::NoData,
				"Set the origin of the axes system for the current grid" },
	{ "gridortho",		"NNN",		"<a> <b> <c>", NuVTypes::NoData,
				"Setup an orthorhombic axis system for the current grid" },
	{ "gridsize",		"NNN",		"<nx> <ny> <nz>", NuVTypes::NoData,
				"Set the number of points along each axis for the current grid" },
	{ "gridstyle",		"C",		"<style>", NuVTypes::NoData,
				"Set the drawing style of the current grid" },
	{ "gridsymmetric",	"B",		"<symm?>", NuVTypes::NoData,
				"Set whether the isodata is symmetric about zero (i.e. whether to draw both halves)" },
	{ "gridusez",		"B",		"<usez?>", NuVTypes::NoData,
				"Whether a 2D surface uses the vertex data value as its z (height) data" },
	{ "loadgrid",		"C",		"<gridfile>", NuVTypes::GridData,
				"Load grid data" },
	{ "newgrid",		"C",		"<title>", NuVTypes::GridData,
				"Create new grid data" },

	// Image commands
	{ "savebitmap",		"CCnnn",	"<format> <filename> [width] [height] [quality, 0-100]", NuVTypes::NoData,
				"Save the current model view as a bitmap image: formats available are bmp, jpg, png, ppm, xbm, and xpm" },
	{ "savevector",		"CC",		"<format> <filename>", NuVTypes::NoData,
				"Save the current model view as a vector image: formats available are ps, eps, tex, pdf, svg, and pgf" },
	
	// Labeling commands
	{ "clearlabels",	"",		"", NuVTypes::NoData,
				"Remove all atom labels in the current model" },
	{ "label",		"Ca",		"<label> [atom/id]", NuVTypes::NoData,
				"Add labels to the current atom selection (or specified atom)" },
	{ "removelabel",	"Ca",		"<label> [atom/id]", NuVTypes::NoData,
				"Remove labels from the current atom selection (or specified atom)" },
	{ "removelabels",	"a",	"[atom/id]", NuVTypes::NoData,
				"Remove all labels from the current atom selection (or specified atom)" },

	// MC commands
	{ "mcaccept",		"CN",		"<movetype> <energy>", NuVTypes::NoData,
				"Set Monte Carlo move type acceptance energies" },
	{ "mcallow",		"CB",		"<movetype> <allow?>", NuVTypes::NoData,
				"Restrict or allow Monte Carlo move types" },
	{ "mcmaxstep",		"CN",		"<movetype> <step>", NuVTypes::NoData,
				"Set maximum step sizes for Monte Carlo move types" },
	{ "mcntrials",		"CN",		"<movetype> <ntrials>", NuVTypes::NoData,
				"Set trial numbers for Monte Carlo move types" },
	{ "printmc",		"",		"", NuVTypes::NoData,
				"Print current Monte Carlo parameters" },
	
	// Measurements
	{ "angle",		"AAA",		"<atom/id1> <atom/id2> <atom/id3>", NuVTypes::RealData,
				"Measure angle between atoms specified" },
	{ "angles",		"",		"", NuVTypes::NoData,
				"Measure bond angles between atoms in current selection" },
	{ "clearmeasurements",	"",		"", NuVTypes::NoData,
				"Clear all measurements in the current model" },
	{ "distance",		"AA",		"<atom/id1> <atom/id2>", NuVTypes::RealData,
				"Measure distance between atoms specified" },
	{ "distances",		"",		"", NuVTypes::NoData,
				"Measure bond distances between atoms in current selection" },
	{ "listmeasurements",	"",		"", NuVTypes::NoData,
				"List all measurements in the current model" },
	{ "measure",		"AAaa",		"<atom/id1> <atom/id2> [atom/id3] [atom/id4]", NuVTypes::RealData,
				"Make a measurement between the specified atoms" },
	{ "torsion",		"AAAA",		"<atom/id1> <atom/id2> <atom/id3> <atom/id4>", NuVTypes::RealData,
				"Measure torsion angle between atoms specified" },
	{ "torsions",		"",		"", NuVTypes::NoData,
				"Measure torsion angles between atoms in current selection" },

	// Messaging
	{ "error",		"C",		"<message>", NuVTypes::NoData,
				"Raise an error message (causes exit of current command list)" },
	{ "printf",		"C",		"<message>", NuVTypes::NoData,
				"Print a message" },
	{ "verbose",		"C",		"<message>", NuVTypes::NoData,
				"Print a message when verbose output is enabled" },
	{ "warn",		"C",		"<message>", NuVTypes::NoData,
				"Raise a warning message (command list will continue)" },
	
	// Minimisation commands
	{ "cgminimise",		"",		"", NuVTypes::NoData,
				"Run a conjugate gradient minimiser on the current model" },
	{ "converge",		"NN",		"<energy> <forces>", NuVTypes::NoData,
				"Set energy and RMS force convergence limits for minimisation algorithms" },
	{ "linetol",		"N",		"<tolerance>", NuVTypes::NoData,
				"Set tolerance of line minimiser" },
	{ "mcminimise",		"N",		"<maxsteps>", NuVTypes::NoData,
				"Run Monte Carlo minimiser on the current model" },
	{ "sdminimise",		"N",		"<maxsteps>", NuVTypes::NoData,
				"Run steepest descent minimiser on the current model" },
	{ "simplexminimise",	"",		"", NuVTypes::NoData,
				"Run the Simplex minimiser on the current model" },
	
	// Model commands
	{ "createatoms",	"",		"", NuVTypes::NoData,
				"Create enough atoms in the current trajectory frame to match the parent model" },
	{ "currentmodel",	"m",		"[model]", NuVTypes::StringData,
				"Print the name of the current model, or set the current displayed model" },
	{ "finalisemodel",	"",		"", NuVTypes::NoData,
				"Finalise the current model" },
	{ "firstmodel",		"",		"", NuVTypes::ModelData,
				"Make the first loaded/created model current" },
	{ "getmodel",		"m",		"<name|id|ptr>", NuVTypes::ModelData,
				"FInd the named (loaded) model, and return a reference to it" },
	{ "info",		"",		"", NuVTypes::NoData,
				"Print data on the current model" },
	{ "lastmodel",		"",		"", NuVTypes::ModelData,
				"Make the last loaded/created model current" },
	{ "listmodels",		"",		"", NuVTypes::NoData,
				"List the currently-loaded models" },
	{ "loadmodel",		"Cc",		"<filename> [name]", NuVTypes::ModelData,
				"Load a model from file" },
	{ "loginfo",		"",		"", NuVTypes::NoData,
				"Print log information for model" },
	{ "modeltemplate",	"",		"", NuVTypes::NoData,
				"Template the atoms in the current trajectory frame, matching the parent model" },
	{ "newmodel",		"C",		"<name>", NuVTypes::ModelData,
				"Create a new model" },
	{ "nextmodel",		"",		"", NuVTypes::ModelData,
				"Skip to the next loaded model" },
	{ "prevmodel",		"",		"", NuVTypes::ModelData,
				"Skip to the previous loaded model" },
	{ "savemodel",		"CC",		"<format> <filename>", NuVTypes::IntegerData,
				"Save the current model to <filename> in the specified model <format>" },
	{ "setname",		"C",		"<name>", NuVTypes::NoData,
				"Set the name of the current model" },

	// Pattern commands
	{ "clearpatterns",	"",		"", NuVTypes::NoData,
				"Remove all pattern definitions from the current model" },
	{ "createpatterns",	"",		"", NuVTypes::NoData,
				"Automatically determine pattern definitions for the current model" },
	{ "getpattern",		"P",		"<name|id|ptr>", NuVTypes::PatternData,
				"Select the named pattern (or pattern id) and make it current" },
	{ "listpatterns",	"",		"", NuVTypes::NoData,
				"Print the pattern definition for the current model" },
	{ "newpattern",		"CNN",		"<name> <nmolecules> <atoms per molecule>", NuVTypes::PatternData,
				"Add a pattern definition 'node' to the current model" },

	// Preferences commands
	{ "anglelabel",		"C",		"<text>", NuVTypes::NoData,
				"Set the units label to use for angles" },
	{ "atomdetail",		"N",		"<n>", NuVTypes::NoData,
				"Set the quadric detail of atoms" },
	{ "bonddetail",		"N",		"<n>", NuVTypes::NoData,
				"Set the quadric detail of bonds" },
	{ "colour",		"CNNNN",	"<colour> <r> <g> <b> [a]", NuVTypes::NoData,
				"Set the specified colour" },
	{ "commonelements",	"C",		"<elements...>", NuVTypes::NoData,
				"Set the common elements that appear in the Select Element dialog" },
	{ "densityunits",	"C",		"atomsperang|gpercm", NuVTypes::NoData,
				"Set the unit of density to use" },
	{ "distancelabel",	"C",		"<text>", NuVTypes::NoData,
				"Set the units label to use for distances" },
	{ "ecut",		"N",		"<cutoff>", NuVTypes::NoData,
				"Set the electrostatic cutoff distance" },
	{ "elec",		"Cnnnn",	"<none|coulomb|ewald|ewaldauto> [ <precision> | <alpha> <kx> <ky> <kz> ]", NuVTypes::NoData,
				"Set the style of electrostatic energy calculation" },
	{ "elementambient",	"SNNN",		"<element> <r> <g> <b>", NuVTypes::NoData,
				"Set ambient colour of element" },
	{ "elementdiffuse",	"SNNN",		"<element> <r> <g> <b>", NuVTypes::NoData,
				"Set diffuse colour of element" },
	{ "elementradius",	"SN",		"<element> <radius>", NuVTypes::NoData,
				"Set effective radius of element" },
	{ "energyunits",	"C",		"j|kj|cal|kcal|ha", NuVTypes::NoData,
				"Set the unit of energy to use" },
	{ "gl",			"CB",		"<option> <on|off>", NuVTypes::NoData,
				"Turn on/off various OpenGL options: fog, linealias, polyalias, backcull" },
	{ "hdistance",		"N",		"<distance>", NuVTypes::NoData,
				"Set the H-X bond distance to use when adding hydrogen" },
	{ "intra",		"B",		"<on|off>", NuVTypes::NoData,
				"Turn on/off energy and force calculation of intramolecular terms" },
	{ "key",		"CC",		"ctrl|shift|alt <action>", NuVTypes::NoData,
				"Set the action of modifier keys" },
	{ "labelsize",		"N",		"<pointsize>", NuVTypes::NoData,
				"Set the integer pointsize for label text" },
	{ "light",		"B",		"<on|off>", NuVTypes::NoData,
				"Turn the spotlight on/off" },
	{ "lightambient",	"NNN",		"<r> <g> <b>", NuVTypes::NoData,
				"Set the ambient colour component of the spotlight" },
	{ "lightdiffuse",	"NNN",		"<r> <g> <b>", NuVTypes::NoData,
				"Set the diffuse colour component of the spotlight" },
	{ "lightposition",	"NNN",		"<x> <y> <z>", NuVTypes::NoData,
				"Set the coordinates of the spotlight" },
	{ "lightspecular",	"NNN",		"<r> <g> <b>", NuVTypes::NoData,
				"Set the specular colour component of the spotlight" },
	{ "mouse",		"CC",		"left|middle|right|wheel <action>", NuVTypes::NoData,
				"Set the action of mouse buttons" },
	{ "radius",		"CN",		"<style> <r>", NuVTypes::NoData,
				"Set the general atom scales for view styles" },
	{ "replicatefold",	"B",		"<on|off>", NuVTypes::NoData,
				"Set whether to fold atoms before cell replicate" },
	{ "replicatetrim",	"B",		"<on|off>", NuVTypes::NoData,
				"Set whether to trim atoms after cell replicate" },
	{ "scheme",		"C",		"[colour scheme]", NuVTypes::NoData,
				"Show (or set) the atomic colouring scheme to use" },
	{ "shininess",		"N",		"<n>", NuVTypes::NoData,
				"Set the shininess of atoms" },
	{ "showonscreen",	"cb",		"[object  yes|no]", NuVTypes::NoData,
				"Set (or lists) the visibility of view objects on-screen" },
	{ "showonimage",	"cb",		"[object  yes|no]", NuVTypes::NoData,
				"Set (or lists) the visibility of view objects on saved images" },
	{ "style",		"c",		"[style]", NuVTypes::NoData,
				"Set (or show) the current model drawing style" },
	{ "swapbuffers",	"b",		"[on|off]", NuVTypes::NoData,
				"Set (or show) the current model drawing style" },
	{ "usenicetext",	"b",		"[on|off]", NuVTypes::NoData,
				"Use QPainter (on) or QGlWidget (off) to render label text" },
	{ "vcut",		"N",		"<cutoff>", NuVTypes::NoData,
				"Set the VDW cutoff distance" },
	{ "vdw",		"B",		"<on|off>", NuVTypes::NoData,
				"Turn on/off VDW energy/force calculation" },
	{ "zoomthrottle",	"n",		"[ratio]", NuVTypes::NoData,
				"Display (or set) the zooming throttle" },

	// Read / Write Commands
	{ "addreadoption",	"C",		"<option>", NuVTypes::NoData,
				"Add a read option: usequotes, skipblanks, stripbrackets" },
	{ "find",		"C^c",		"<string> [linevar]", NuVTypes::IntegerData,
				"Search for a string in the input file (placing matching line in optional variable" },
	{ "getline",		"^C",		"", NuVTypes::IntegerData,
				"Read the next line from the file, placing in variable supplied, and returning read success" },
	{ "readchars",		"N",		"<nchars>", NuVTypes::StringData,
				"Read a number of characters from the input file" },
	{ "readint",		"n",		"[nbytes=4]", NuVTypes::IntegerData,
				"Read an integer value from the (binary) input file" },
	{ "readline",		"^Z*",		"<variable>  [variable...]", NuVTypes::IntegerData,
				"Read a line from the input file, and split into supplied variables using whitespace delimiters" },
	{ "readlinef",		"C^z*",		"<formatting string> [data1, data2...]", NuVTypes::IntegerData,
				"Read a line from the input file, and parse into supplied variables using format string" },
	{ "readnext",		"^Z",		"<variable>", NuVTypes::IntegerData,
				"Read the next delimited item from the file and place in the variable supplied" },
	{ "readreal",		"n",		"[nbytes=8]", NuVTypes::RealData,
				"Read a floating point value from the (binary) input file" },
	{ "readvar",		"CC^z*",	"<variable> <formatting string> [data1, data2...]", NuVTypes::IntegerData,
				"Parse a character variable according to the supplied format" },
	{ "removereadoption",	"C",		"<option>", NuVTypes::NoData,
				"Remove a read option" },
	{ "rewind",		"",		"", NuVTypes::NoData,
				"Rewind to the start of the input file" },
	{ "skipchars",		"N",		"<nchars>", NuVTypes::NoData,
				"Skip a number of characters in the input file" },
	{ "skipline",		"n",		"[nlines]", NuVTypes::NoData,
				"Skip a number of lines in the input file" },
	{ "writelinef",		"Cz*",		"<formatting string> [data1, data2...]", NuVTypes::IntegerData,
				"Write a formatted line to the output file" },
	{ "writevar",		"C^Cz*",	"<variable> <formatting string> [data1, data2...]", NuVTypes::IntegerData,
				"Return a formatted line to the character variable supplied" },

	// Script commands
	{ "listscripts",	"",		"", NuVTypes::NoData,
				"List available scripts" },
	{ "loadscript",		"Cc",		"<filename> [nickname]", NuVTypes::NoData,
				"Load script from file" },
	{ "runscript",		"S",		"<name|id>", NuVTypes::NoData,
				"Execute the named script" },

	// Selection commands
	{ "deselect",		"S*",		"<id|el|id-id|el-el|+id|+el|id+|el+,...>", NuVTypes::IntegerData,
				"Deselect specific atoms / ranges in the current model" },
	{ "deselecttype",	"SC",		"<element> <typedesc>", NuVTypes::IntegerData,
				"Deselect all atoms that match the provided atomtype description" },
	{ "expand",		"",		"", NuVTypes::NoData,
				"Expands the current atom selection" },
	{ "invert",		"",		"", NuVTypes::NoData,
				"Invert the current selection" },
	{ "select",		"S*",		"<id|el|id-id|el-el|+id|+el|id+|el+,...>", NuVTypes::IntegerData,
				"Select specific atoms / ranges in the current model" },
	{ "selectall",		"",		"", NuVTypes::NoData,
				"Select all atoms in the current model" },
	{ "selectfftype",	"C",		"<typename>", NuVTypes::NoData,
				"Select all atoms of a specific forcefield type" },
	{ "selectioncog",	"",		"", NuVTypes::VectorData,
				"Return centre of geometry of current selection" },
	{ "selectioncom",	"",		"", NuVTypes::VectorData,
				"Return centre of mass of current selection (and place in variables if supplied" },
	{ "selectnone",		"",		"", NuVTypes::NoData,
				"Deselect all atoms in the current model" },
	{ "selectoverlaps",	"n",		"[tolerance = 0.2]", NuVTypes::IntegerData,
				"Select all atoms which are within a given distance of each other" },
	{ "selectpattern",	"p",		"[name]", NuVTypes::NoData,
				"Select all atoms in the current (or named) pattern" },
	{ "selecttype",		"SC",		"<element> <typedesc>", NuVTypes::IntegerData,
				"Select all atoms that match the provided atomtype description (returning the number matched)" },
	
	// Site commands
	{ "getsite",		"C",		"<name>", NuVTypes::NoData,
				"Select the defined site and make it current" },
	{ "listsites",		"",		"", NuVTypes::NoData,
				"Print all sites defined for the current model" },
	{ "newsite",		"CCc",		"<name> <pattern> [atomlist]", NuVTypes::NoData,
				"Adds a new site definition to the current model" },
	{ "siteaxes",		"CC",		"<atomlist> <atomlist>", NuVTypes::NoData,
				"Set the axis definitions for the current site" },

	// System commands
	{ "debug",		"C",		"<mode>", NuVTypes::NoData,
				"Toggle debugging for the specified mode" },
	{ "gui",		"",		"", NuVTypes::NoData,
				"Start the GUI (if it is not already active)" },
	{ "help",		"C",		"<command>", NuVTypes::NoData,
				"Provide short help on the command supplied" },
	{ "seed",		"N",		"<seed>", NuVTypes::NoData,
				"Set the random seed" },
	{ "quit",		"",		"", NuVTypes::NoData,
				"Exit the program" },
	{ "version",		"",		"", NuVTypes::NoData,
				"Print program version information" },

	// Trajectory commands
	{ "finaliseframe",	"",		"", NuVTypes::NoData,
				"Finalise the current trajectory frame" },
	{ "firstframe",		"",		"", NuVTypes::NoData,
				"Go to the first frame in the current trajectory" },
	{ "lastframe",		"",		"", NuVTypes::NoData,
				"Go to the last frame in the current trajectory" },
	{ "loadtrajectory",	"C",		"<filename>", NuVTypes::NoData,
				"Load the specified trajectory and associate it to the current model" },
	{ "nextframe",		"",		"", NuVTypes::NoData,
				"Go to the next frame in the current trajectory" },
	{ "prevframe",		"",		"", NuVTypes::NoData,
				"Go to the previous frame in the current trajectory" },
	{ "seekframe",		"N",		"<frame>", NuVTypes::NoData,
				"Jump to the specified frame in the current trajectory" },
	
	// Transformation commands
	{ "axisrotate",		"NNNNnnn|AANnnn",	"<ax> <ay> <ax> <theta> [ox oy oz] | <i> <j> <theta> [ox oy oz]", NuVTypes::NoData,
				"Rotate the current selection about a defined axis and origin" },
	{ "centre",		"NNN",		"<x> <y> <z>", NuVTypes::NoData,
				"Centre the atom selection of the current model at the specified coordinates" },
	{ "matrixconvert",	"NNNNNNNNNNNNnnnnnnnnn","<i_sx> <j_sx> <i_sy> <j_sy> <i_sz> <j_sz> <i_dx> <j_dx> <i_dy> <j_dy> <i_dz> <j_dz> [ox oy oz] | <sax> <say> <saz> <sbx> <sby> <sbz> <scx> <scy> <scz> <dax> <day> <daz> <dbx> <dby> <dbz> <dcx> <dcy> <dcz> [ox oy oz]", NuVTypes::NoData,
				"Transform selected atoms in reference frame specified to destination frame specified" },
	{ "matrixtransform",	"NNNNNNNNNnnn",	"<ax> <ay> <az> <bx> <by> <bz> <cx> <cy> <cz> [ox oy oz]", NuVTypes::NoData,
				"Transform selected atoms by the matrix supplied" },
	{ "mirror",		"C",		"<axis>", NuVTypes::NoData,
				"Mirror the atom selection of the current model about its geometric centre in the specified axis" },
	{ "translate",		"NNN",		"<dx> <dy> <dz>", NuVTypes::NoData,
				"Translate the atom selection of the current model" },
	{ "translateatom",	"NNN",		"<dx> <dy> <dz>", NuVTypes::NoData,
				"Translate the current atom" },
	{ "translatecell",	"NNN",		"<dx> <dy> <dz>", NuVTypes::NoData,
				"Translate the current selection along the cell axes by the fractional axes specified" },
	{ "translateworld",	"NNN",		"<dx> <dy> <dz>", NuVTypes::NoData,
				"Translate the current selection in world (view) coordinates" },

	// Variable Manipulation
	{ "afterchar",		"CC",		"<string> <char>", NuVTypes::StringData,
				"Return part of the <string> after the first occurrence of the character <char>" },
	{ "beforechar",		"CC",		"<string> <char>", NuVTypes::StringData,
				"Return part of the <string> before the first occurrence of the character <char>" },
	{ "normalise",		"U",		"<vector>", NuVTypes::RealData,
				"Normalise the values of the 3-vector supplied" },
	{ "stripchars",		"^CC",		"<variable> <chars>", NuVTypes::StringData,
				"Strip all occurrences of the supplied characters from the supplied variable" },

	// Variable Operators
	{ "+",			"..",		"", NuVTypes::NoData,
				"Internal Operator (+)" },
	{ "=",			"..",		"", NuVTypes::NoData,
				"Internal Operator (=)" },
	{ "/=",			"..",		"", NuVTypes::NoData,
				"Internal Operator (/=)" },
	{ "-=",			"..",		"", NuVTypes::NoData,
				"Internal Operator (-=)" },
	{ "*=",			"..",		"", NuVTypes::NoData,
				"Internal Operator (*=)" },
	{ "+=",			"..",		"", NuVTypes::NoData,
				"Internal Operator (+=)" },
	{ "/",			"..",		"", NuVTypes::NoData,
				"Internal Operator (/)" },
	{ "==",			"..",		"", NuVTypes::NoData,
				"Internal Operator (==)" },
	{ ">",			"..",		"", NuVTypes::NoData,
				"Internal Operator (>)" },
	{ ">=",			"..",		"", NuVTypes::NoData,
				"Internal Operator (>=)" },
	{ "<",			"..",		"", NuVTypes::NoData,
				"Internal Operator (<)" },
	{ "<=",			"..",		"", NuVTypes::NoData,
				"Internal Operator (<=)" },
	{ "*",			"..",		"", NuVTypes::NoData,
				"Internal Operator (*)" },
	{ "-NEG",		".",		"", NuVTypes::NoData,
				"Internal Operator (negate)" },
	{ "!=",			"..",		"", NuVTypes::NoData,
				"Internal Operator (!=)" },
	{ "^",			"..",		"", NuVTypes::NoData,
				"Internal Operator (^)" },
	{ "-",			"..",		"", NuVTypes::NoData,
				"Internal Operator (-)" },
	
	// View
	{ "getview",		"",		"", NuVTypes::NoData,
				"Print the rotation matrix, camera position, and camera z-rotation for the current model" },
	{ "orthographic",	"",		"", NuVTypes::NoData,
				"Render in an orthographic projection" },
	{ "perspective",	"n",		"[fov]", NuVTypes::NoData,
				"Render in a perspective projection" },
	{ "resetview",		"",		"", NuVTypes::NoData,
				"Reset the camera and rotation for the current model" },
	{ "rotateview",		"NN",		"<x> <y>", NuVTypes::NoData,
				"Rotate the current model about the x and y axes by the specified amounts" },
	{ "setview",		"NNNNNNNNNNNNn","<ax> <ay> <az> <bx> <by> <bz> <cx> <cy> <cz> <camx> <camyu> <camz> [zrot]", NuVTypes::NoData,
				"Set the rotation matrix, camera position, and camera z-rotation for the current model" },
	{ "speedtest",		"n",		"[nrender]", NuVTypes::NoData,
				"Time 100 (or 'nrender') updates of the model display." },
	{ "translateview",	"NNN",		"<dx> <dy> <dz>", NuVTypes::NoData,
				"Translate the camera for the current model" },
	{ "viewalong",		"NNN",		"<x> <y> <z>", NuVTypes::NoData,
				"Set the rotation for the current model so the view is along the specified vector" },
	{ "viewalongcell",	"NNN",		"<x> <y> <z>", NuVTypes::NoData,
				"Set the rotation for the current model so the view is along the specified cell vector" },
	{ "zoomview",		"N",		"<dz>", NuVTypes::NoData,
				"Zoom in/out the camera - equivalent to 'translateview 0 0 dz'" },
	{ "zrotateview",	"N",		"<dr>", NuVTypes::NoData,
				"Rotate the model in the plane of the screen" }
};

// Return enumerated command from string
NuCommand::Function NuCommand::command(const char *s)
{
	int result;
	for (result = NuCommand::NoFunction; result < NuCommand::nCommands; result++) if (strcmp(data[result].keyword,s) == 0) break;
	return (NuCommand::Function) result;
}

// Constructor
NuCommand::NuCommand()
{
	// Create pointer list
	initPointers();
	// Create dummyCommandList complete with a single dummy command
// 	dummyCommandList_ = new NuCommandList;
// 	dummyCommandNode_ = new NuCommandNode;
// 	dummyCommandNode_->setParent(dummyCommandList_);
}

// Constructor
NuCommand::~NuCommand()
{
// 	delete dummyCommandNode_;
// 	delete dummyCommandList_;
}

// Return whether command accepts any arguments
bool NuCommandData::hasArguments()
{
	return (!(arguments[0] == '\0'));
}

// Execute command
int NuCommand::call(NuCommand::Function cf, NuCommandNode *c, NuReturnValue &rv)
{
// 	return CALL_COMMAND(commands,pointers_[cf])(c, aten.current);
	return (this->pointers_[cf])(c, aten.current, rv);
}

