/*
	*** Command Function Definitions
	*** src/parser/commands.cpp
	Copyright T. Youngs 2007-2009

	This file is part of Aten.

	Aten is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	Aten is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with Aten.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "parser/commands.h"
#include "parser/commandnode.h"
#include "parser/tree.h"
#include "main/aten.h"
#include "base/bundle.h"

// Singleton
NuCommand nucommands;

// Command action
NuCommandData NuCommand::data[NuCommand::nFunctions] = {

	// Root node
	{ "_ROOTNODE_",		"",		"", VTypes::NoData,
				"" },

	// Joiner
	{ "_JOINER_",		"",		"", VTypes::NoData,
				"" },

	// Analysis commands
	{ "finalise",		"",		"", VTypes::IntegerData,
				"Finalise all calculated quantities" },
	{ "frameanalyse",	"",		"", VTypes::IntegerData,
				"Analyse quantities for the current trajectory frame" },
	{ "geometry",		"NEEENNNnn",	"<name> <min> <binwidth> <nbins> <filename> <site1> <site2> [site3 [site4]]", VTypes::IntegerData,
				"Calculate geometries" },
	{ "modelanalyse",	"",		"", VTypes::IntegerData,
				"Analyse quantities for the current model" },
	{ "pdens",		"NEENNN",	"<name> <griddelta> <nsteps> <filename> <site1> <site2> ", VTypes::IntegerData,
				"Request calculation of a probability density between sites" },
	{ "listjobs",		"",		"", VTypes::IntegerData,
				"Print the current list of quantities to calculate" },
	{ "rdf",		"NEEENNN",	"<name> <rmin> <binwidth> <nbins> <filename> <site1> <site2>", VTypes::IntegerData,
				"Request calculation of radial distribution function between sites" },
	{ "savequantities",	"",		"", VTypes::IntegerData,
				"Save calculated quantities to file" },
	{ "trajanalyse",	"EEe",		"<startframe> <frameskip> [nframes]", VTypes::IntegerData,
				"Analyse quantities for all frames in current trajectory" },
	
	// Atom commands
	{ "atomstyle",		"Ne",		"<style> [id]", VTypes::IntegerData,
				"Set the individual style of the current atom selection (or supplied atom)" },
	{ "getatom",		"Ea",		"<id> [variable]", VTypes::IntegerData,
				"Retrieve information for atom id, placing in variable supplied" },
	{ "hide",		"n",		"[id]", VTypes::IntegerData,
				"Hide the current selection of atoms (or supplied atom)" },
	{ "setcharge",		"Ee",		"<q> [id]", VTypes::IntegerData,
				"Set the charge of the current (or specified) atom" },
	{ "setcoords",		"EEEe",		"<x> <y> <z> [id]", VTypes::IntegerData,
				"Set the coordinates of the current (or specified) atom" },
	{ "setelement",		"Ne",		"<element> [id]", VTypes::IntegerData,
				"Set the element of the current (or specified) atom" },
	{ "setforces",		"EEEe",		"<fx> <fy> <fz> [id]", VTypes::IntegerData,
				"Set the forces of the current (or specified) atom" },
	{ "setfx",		"Ee",		"<fx> [id]", VTypes::IntegerData,
				"Set the x force of the current (or specified) atom" },
	{ "setfy",		"Ee",		"<fy> [id]", VTypes::IntegerData,
				"Set the y force of the current (or specified) atom" },
	{ "setfz",		"Ee",		"<fz> [id]", VTypes::IntegerData,
				"Set the z force of the current (or specified) atom" },
	{ "setid",		"Ee",		"<id> [id]", VTypes::IntegerData,
				"Set the id of the current (or specified) atom" },
	{ "setrx",		"Ee",		"<rx> [id]", VTypes::IntegerData,
				"Set the x coordinate of the current (or specified) atom" },
	{ "setry",		"Ee",		"<ry> [id]", VTypes::IntegerData,
				"Set the y coordinate of the current (or specified) atom" },
	{ "setrz",		"Ee",		"<rz> [id]", VTypes::IntegerData,
				"Set the z coordinate of the current (or specified) atom" },
	{ "setvelocities",	"EEEe",		"<vx> <vy> <vz> [id]", VTypes::IntegerData,
				"Set the velocities of the current (or specified) atom" },
	{ "setvx",		"Ee",		"<vx> [id]", VTypes::IntegerData,
				"Set the x velocity of the current (or specified) atom" },
	{ "setvy",		"Ee",		"<vy> [id]", VTypes::IntegerData,
				"Set the y velocity of the current (or specified) atom" },
	{ "setvz",		"Ee",		"<vz> [id]", VTypes::IntegerData,
				"Set the z velocity of the current (or specified) atom" },
	{ "show",		"n",		"[id]", VTypes::IntegerData,
				"Show the current selection of atoms (or supplied atom)" },
	{ "showall",		"",		"", VTypes::IntegerData,
				"Show all atoms in the current model" },

	// Bonding commands
	{ "augment",		"",		"", VTypes::IntegerData,
				"Automatically augment all bonds in the current model" },
	{ "bondtolerance",	"E",		"<tolerance>", VTypes::IntegerData,
				"Set bonding tolerance for automatic calculation" },
	{ "clearbonds",		"",		"", VTypes::IntegerData,
				"Delete all bonds in the current model" },
	{ "clearselectedbonds",	"",		"", VTypes::IntegerData,
				"Delete all bonds in the current selection" },
	{ "newbond",		"EEn",		"<atom1> <atom2> [bondtype]", VTypes::IntegerData,
				"Create a bond between specified atoms" },
	{ "newbondid",		"EEn",		"<id1> <id2> [bondtype]", VTypes::IntegerData,
				"Create a bond between atoms with ids specified" },
	{ "rebond",		"",		"", VTypes::IntegerData,
				"Calculate bonding in the current model" },
	{ "rebondpatterns",	"",		"", VTypes::IntegerData,
				"Calculate bonds between atoms, restricted to atoms in pattern molecules" },
	{ "rebondselection",	"",		"", VTypes::IntegerData,
				"Calculate bonds between atoms in the current selection" },

	// Build commands
	{ "addhydrogen",	"e",		"[atom|id]", VTypes::IntegerData,
				"Hydrogen satisfy all (or specified) atom in model" },
	{ "bohr",		"v*",		"<object> [object...]", VTypes::IntegerData,
				"Convert coordinates in the specified object " },
	{ "chain",		"Neeee",	"<element> [bondtype] | <element> <x> <y> <z> [bondtype]", VTypes::IntegerData,
				"Create a new atom in the current model, bound to the last" },
	{ "endchain",		"",		"", VTypes::IntegerData,
				"End the current bond chain (the next call to 'chain' will create an unbound atom)" },
	{ "insertatom",		"NNeee",	"<element> <id> [x y z]", VTypes::IntegerData,
				"Insert a new atom into the model such that it has the ID specified" },
	{ "locate",		"EEE",		"<x> <y> <z>", VTypes::IntegerData,
				"Position pen at specified coordinates" },
	{ "move",		"EEE",		"<dx> <dy> <dz>", VTypes::IntegerData,
				"Move pen by specified coordinates" },
	{ "movetoend",		"",		"", VTypes::IntegerData,
				"Move current atom selection to end of list" },
	{ "movetostart",	"",		"", VTypes::IntegerData,
				"Move current atom selection to start of list" },
	{ "newatom",		"Neee",		"<element> [x y z]", VTypes::IntegerData,
				"Create a new atom in the current model" },
	{ "newatomfrac",	"NEEE",		"<element> <fracx> <fracy> <fracz>", VTypes::IntegerData,
				"Create a new atom in the current model, converting fractional coordinates to real coordinates" },
	{ "reorder",		"",		"", VTypes::IntegerData,
				"Reorder atoms in the current selection such that bond partners have adjacent atom IDs" },
	{ "resetpen",		"",		"", VTypes::IntegerData,
				"Reset the pen orientation to the identity matrix (but leave the current position intact)" },
	{ "rotx",		"E",		"<angle>", VTypes::IntegerData,
				"Rotate pen about its x axis by given angle" },
	{ "roty",		"E",		"<angle>", VTypes::IntegerData,
				"Rotate pen about its y axis by given angle" },
	{ "rotz",		"E",		"<angle>", VTypes::IntegerData,
				"Rotate pen about its z axis by given angle" },
	{ "shiftdown",		"e",		"[n]", VTypes::IntegerData,
				"Shift current atom selection down 1 (or 'n') places" },
	{ "shiftup",		"e",		"[n]", VTypes::IntegerData,
				"Shift current atom selection up 1 (or 'n') places" },
	{ "transmute",		"E",		"<element>", VTypes::IntegerData,
				"Transmute selection to element given" },
	
	// Cell commands
	{ "addgenerator",	"N",		"<generator>", VTypes::IntegerData,
				"Manually add a spacegroup generator definition to the current model's cell" },
	{ "adjustcell",		"NE",		"<quantity> <change>", VTypes::IntegerData,
				"Adjust a single value of the current cell specification (e.g. <quantity> = a, beta, cz, etc.)" },
	{ "cell",		"EEEEEE",	"<a> <b> <c> <alpha> <beta> <gamma>", VTypes::IntegerData,
				"Set or create a unit cell for the current model from lengths/angles provided" },
	{ "cellaxes",		"EEEEEEEEE",	"<ax> <ay> <az> <bx> <by> <bz> <cx> <cy> <cz>", VTypes::IntegerData,
				"Set or create a unit cell for the current model from the cell axes provided" },
	{ "fold",		"",		"", VTypes::IntegerData,
				"Fold atoms into model's unit cell" },
	{ "foldmolecules",	"",		"", VTypes::IntegerData,
				"Fold molecules (defined by patterns) so that they are unbroken across cell boundaries" },
	{ "fractoreal",		"",		"", VTypes::IntegerData,
				"Convert (assumed) fractional model coordinates to real coordinates" },
	{ "nocell",		"", 		"", VTypes::IntegerData,
				"Remove any cell definition from the current model" },
	{ "pack",		"",		"", VTypes::IntegerData,
				"Pack the unit cell with symmetry operators list in associated spacegroup" },
	{ "printcell",		"",		"", VTypes::IntegerData,
				"Print the unit cell of the current model" },
	{ "replicate",		"EEEEEE",	"<negx> <negy> <negz> <posx> <posy> <posz>", VTypes::IntegerData,
				"Replicate the cell along the directions given" },
	{ "rotatecell",		"NE",		"<axis> <angle>", VTypes::IntegerData,
				"Rotate the cell and its contents about the specified orthogonal axis (x, y, or z)" },
	{ "scale",		"EEE",		"<x> <y> <z>", VTypes::IntegerData,
				"Scale the unit cell and atomic positions of the current model" },
	{ "scalemolecules",	"EEE",		"<x> <y> <z>", VTypes::IntegerData,
				"Scale the unit cell and molecular positions of the current model" },
	{ "setcell",		"NE",		"<quantity> <value>", VTypes::IntegerData,
				"Set a single value of the current cell specification (e.g. <quantity> = a, beta, cz, etc.)" },
	{ "spacegroup",		"N",		"<spgrp>", VTypes::IntegerData,
				"Set the spacegroup for the current model" },
	
	// Charge commands
	{ "chargeff",		"",		"", VTypes::IntegerData,
				"Charge atoms in the model according to their forcefield atom types" },
	{ "chargefrommodel",	"",		"", VTypes::IntegerData,
				"Charge atoms in the current trajectory frame from the parent model" },
	{ "chargepatom",	"EE",		"<id> <q>", VTypes::IntegerData,
				"Set charges for specific atom id in all molecules of the current pattern" },
	{ "charge",		"E",		"<q>", VTypes::IntegerData,
				"Set charges of atoms in the current selection" },
	{ "chargetype",		"EE",		"<type> <q>", VTypes::IntegerData,
				"Set charges of all atoms of the given type" },
	{ "clearcharges",	"",		"", VTypes::IntegerData,
				"Zero all charges in the current model" },

	// Colourscale commands
	{ "addpoint",		"EEEEEe",	"<scaleid> <value> <r> <g> <b> [a]", VTypes::IntegerData,
				"Add a new point to the specified colourscale" },
	{ "clearpoints",	"E",		"<scaleid>", VTypes::IntegerData,
				"Clear all points from the specified colourscale" },
	{ "listscales",		"",		"", VTypes::IntegerData,
				"List details on all colourscales" },
	{ "removepoint",	"EE",		"<scaleid> <point>", VTypes::IntegerData,
				"Remove the selected point from the specified colourscale" },
	{ "scalename",		"En",		"<scaleid> [name]", VTypes::IntegerData,
				"Print (or set) the name of the colourscale specified" },
	{ "scalevisible",	"EN",		"<scaleid> true|false", VTypes::IntegerData,
				"Set the visibility of the specified colourscale" },
	{ "setpoint",		"EEEEEEe",	"<scaleid> <point> <value> <r> <g> <b> [a]", VTypes::IntegerData,
				"Set an existing point on the specified colourscale" },
	{ "setpointcolour", 	"EEEEEe",	"<scaleid> <point> <r> <g> <b> [a]", VTypes::IntegerData,
				"Set the colour for an existing colourscale point" },
	{ "setpointvalue", 	"EEE",		"<scaleid> <point> <value>", VTypes::IntegerData,
				"Set the value for an existing colourscale point" },

	// Disordered Builder Commands
	{ "disorder",		"E",		"<nsteps>", VTypes::IntegerData,
				"Run the disordered builder" },
	{ "listcomponents",	"",		"", VTypes::IntegerData,
				"Print a list of the components requested in the disordered builder" },
	{ "nmols",		"E",		"<n>", VTypes::IntegerData,
				"Set the number of molecules required for the component" },
	{ "region",		"NEEEEEEN",	"<shape> <cx> <cy> <cz> <x> <y> <z> yes|no", VTypes::IntegerData,
				"Set the shape, centre, size, and overlap flag of the region for the current model" },
	{ "regioncentre",	"EEE",		"<x> <y> <z>", VTypes::IntegerData,
				"Set the region centre of the current model" },
	{ "regioncentref",	"EEE",		"<x> <y> <z>", VTypes::IntegerData,
				"Set the region centre of the current model (fractional coordinates)" },
	{ "regionf",		"NEEEEEEN",	"<shape> <cx> <cy> <cz> <x> <y> <z> yes|no", VTypes::IntegerData,
				"Set the shape, centre, size, and overlap flag of the region for the current model (fractional coordinates)" },
	{ "regiongeometry",	"EEEe",		"<x> <y> <z> [l]", VTypes::IntegerData,
				"Set the region geometry of the current model" },
	{ "regiongeometryf",	"EEEe",		"<x> <y> <z> [l]", VTypes::IntegerData,
				"Set the region geometry of the current model (fractional coordinates)" },
	{ "regionoverlap",	"N",		"yes|no", VTypes::IntegerData,
				"Set the overlap flag of the current model" },
	{ "regionshape",	"N",		"<shape>", VTypes::IntegerData,
				"Set the region shape of the current model" },
	{ "vdwscale",		"E",		"<scale>", VTypes::IntegerData,
				"Set the VDW scaling factor to use in the disordered builder" },

	// Edit commands
	{ "copy",		"",		"", VTypes::IntegerData,
				"Copy selected atoms" },
	{ "cut",		"",		"", VTypes::IntegerData,
				"Cut the selected atoms" },
	{ "delete",		"",		"", VTypes::IntegerData,
				"Delete selected atoms" },
	{ "paste",		"eee",		"[dx] [dy] [dz]", VTypes::IntegerData,
				"Paste previously-cut or copied atoms to the model (with optional shift from original position" },
	{ "redo",		"",		"", VTypes::IntegerData,
				"Redo last change" },
	{ "undo",		"",		"", VTypes::IntegerData,
				"Undo last change" },

	// Energy commands
	{ "frameenergy",	"",		"", VTypes::IntegerData,
				"Calculate the energy of the current trajectory frame" },
	{ "modelenergy",	"",		"", VTypes::IntegerData,
				"Calculate the energy of the current model" },
	{ "printelec",		"",		"", VTypes::IntegerData,
				"Print the electrostatic pattern matrix of the last calculated energy" },
	{ "printewald",		"",		"", VTypes::IntegerData,
				"Print the Ewald decomposition of the last calculated energy" },
	{ "printinter",		"",		"", VTypes::IntegerData,
				"Print the total intermolecular pattern matrix of the last calculated energy" },
	{ "printintra",		"",		"", VTypes::IntegerData,
				"Print the total intramolecular pattern matrix of the last calculated energy" },
	{ "printenergy",	"",		"", VTypes::IntegerData,
				"Print a short description of the last calculated energy" },
	{ "printsummary",	"",		"", VTypes::IntegerData,
				"Print a one-line summary of the last calculated energy" },
	{ "printvdw",		"",		"", VTypes::IntegerData,
				"Print the VDW pattern matrix of the last calculated energy" },

	// Flow control
	{ "break",		"",		"", VTypes::IntegerData,
				"Exit from the current for loop" },
	{ "continue",		"",		"", VTypes::IntegerData,
				"Skip to the next iteration of the current loop" },
	{ "else",		"",		"", VTypes::IntegerData,
				"Perform the subsequent block if all previous if/elseif tests failed" },
	{ "elseif",		"ESE",		"<variable> <condition> <variable|constant>", VTypes::IntegerData,
				"Perform a conditional test on the supplied variable against the second variable (or constant), if all previous tests failed" },
	{ "end",		"",		"", VTypes::IntegerData,
				"End the current for/if block" },
	{ "for",		"Vee",		"<variable> [start] [end]", VTypes::IntegerData,
				"" },
	{ "_GOTO_",		"",		"", VTypes::IntegerData,
				"" },
	{ "_GOTONONIF_",	"",		"", VTypes::IntegerData,
				"" },
	{ "if",			"ESE",		"<expression> <condition> <expression>", VTypes::IntegerData,
				"Perform a conditional test between the supplied expressions (or variables or constants)" },
	{ "_TERMINATE_",	"",		"", VTypes::IntegerData,
				"" },
	
	// Force commands
	{ "frameforces",	"",		"", VTypes::IntegerData,
				"Calculate forces for the current trajectory frame" },
	{ "modelforces",	"",		"", VTypes::IntegerData,
				"Calculate forces for the current model" },
	{ "printforces",	"",		"", VTypes::IntegerData,
				"Print calculated forces for the current model" },
	
	// Forcefield commands
	{ "angledef",		"NNNNEeeeee", "<form> <name1> <name2> <name3> <data1> [data2 ... data6]", VTypes::IntegerData,
				"Add an angle definition to the current forcefield." },
	{ "bonddef",		"NNNEeeeee", "<form> <name1> <name2> <data1> [data2 ... data6]", VTypes::IntegerData,
				"Add a bond definition to the current forcefield." },
	{ "clearmap",		"",		"", VTypes::IntegerData,
				"Clear manual type mapping list." },
	{ "createexpression",	"",		"", VTypes::IntegerData,
				"Create and fill a forcefield expression for the current model" },
	{ "defaultff",		"N",		"<ff>", VTypes::IntegerData,
				"Make named forcefield the default for occasions where no other is specified." },
	{ "equivalents",	"NN",		"<name> <'names...'>", VTypes::IntegerData,
				"Define forcefield equivalents" },
	{ "ffmodel",		"n",		"[name]", VTypes::IntegerData,
				"Associate current (or named) forcefield to current model" },
	{ "ffpattern",		"",		"", VTypes::IntegerData,
				"Associate current forcefield to current pattern" },
	{ "ffpatternid",	"E",		"<patternid>", VTypes::IntegerData,
				"Associate current forcefield to specified pattern ID" },
	{ "finaliseff",		"",		"", VTypes::IntegerData,
				"Finalise current forcefield." },
	{ "genconvert",		"E*",		"<data1> [data2..data10]", VTypes::IntegerData,
				"Set energetic generator data to convert" },
	{ "generator",		"EEeeeeeeeee",	"<typeId> <data1> [data2...data10]", VTypes::IntegerData,
				"Set generator data for specified atom type" },
	{ "getff",		"N",		"<name>", VTypes::IntegerData,
				"Select named (loaded) forcefield and make it current" },
	{ "interdef",		"NEEEeeeee", "<form> <typeid> <charge> <data1> [data2...data6]", VTypes::IntegerData,
				"Add a new interatomic definition to the current forcefield" },
	{ "loadff",		"Nn",		"<filename> [name]", VTypes::IntegerData,
				"Load forcefield" },
	{ "map",		"N*",		"<name=element,...>", VTypes::IntegerData,
				"Add typename mappings" },
	{ "newff",		"N",		"<name>", VTypes::IntegerData,
				"Create a new, empty forcefield." },
	{ "printsetup",		"",		"", VTypes::IntegerData,
				"Print the current energy/force calculation setup" },
	{ "rules",		"N",		"<rules set>", VTypes::IntegerData,
				"Set rules set to use for parameter generation" },
	{ "saveexpression",	"NN",		"<format> <filename>", VTypes::IntegerData,
				"Save the expression for the current model" },
	{ "torsiondef",		"NNNNNEeeeee", "<form> <name1> <name2> <name3> <name4> <data1> [data2 ... data6]", VTypes::IntegerData,
				"Add a torsion definition to the current forcefield." },
	{ "typedef",		"ENNNn", "<typeid> <name> <element> <type> [description]", VTypes::IntegerData,
				"Add an atom type to the current forcefield." },
	{ "typemodel",		"",		"", VTypes::IntegerData,
				"Perform atom typing on the current model" },
	{ "typetest",		"EE",		"<ffid> <atomid>", VTypes::IntegerData,
				"Test atomtype score on atom provided" },
	{ "units",		"N",		"<energy unit>", VTypes::IntegerData,
				"Set energy unit of forcefield" },

	// Glyph commands
	{ "autoellipsoids",	"n*",		"[options]", VTypes::IntegerData,
				"Automatically add ellipsoids to the current atom selection" },
	{ "autopolyhedra",	"n*",		"[options]", VTypes::IntegerData,
				"Automatically add polyhedra to the current atom selection" },
	{ "glyphatomf",		"Ee",		"<n> [atom|atomid]", VTypes::IntegerData,
				"Set current (or specified) atom's forces as data <n> in current glyph" },
	{ "glyphatomr",		"Ee",		"<n> [atom|atomid]", VTypes::IntegerData,
				"Set current (or specified) atom's coordinates as data <n> in current glyph" },
	{ "glyphatomv",		"Ee",		"<n> [atom|atomid]", VTypes::IntegerData,
				"Set current (or specified) atom's velocities data <n> in current glyph" },
	{ "glyphatomsf",	"Eeee",		"<atom|atomid> [atom|atomid] [atom|atomid] [atom|atomid]", VTypes::IntegerData,
				"Set all atom forces data in current glyph" },
	{ "glyphatomsr",	"Eeee",		"<atom|atomid> [atom|atomid] [atom|atomid] [atom|atomid]", VTypes::IntegerData,
				"Set all atom coordinates data in current glyph" },
	{ "glyphatomsv",	"Eeee",		"<atom|atomid> [atom|atomid] [atom|atomid] [atom|atomid]", VTypes::IntegerData,
				"Set all atom velocities data in current glyph" },
	{ "glyphcolour",	"EEEEe",	"<n> <r> <g> <b> [a]", VTypes::IntegerData,
				"Set colour data <n> in current glyph" },
	{ "glyphdata",		"EEee",		"<n> <x> <y> <z>", VTypes::IntegerData,
				"Set vector data <n> in current glyph" },
	{ "glyphsolid",		"N",		"<true|false>", VTypes::IntegerData,
				"Set the glyph to be drawn in solid (true) or wireframe (false) modes (glyph-permitting)" },
	{ "glyphtext",		"N",		"<text>", VTypes::IntegerData,
				"Set text data in current glyph" },
	{ "newglyph",		"Nn",		"<style> [options]", VTypes::IntegerData,
				"Add a glyph with the specified style to the current model" },

	// Grid commands
	{ "addgridpoint",	"EEEE",		"<ix> <iy> <iz> <value>", VTypes::IntegerData,
				"Set specific gridpoint value" },
	{ "addnextgridpoint",	"E",		"<value>", VTypes::IntegerData,
				"Add next gridpoint value" },
	{ "finalisegrid",	"",		"", VTypes::IntegerData,
				"Finalise grid import" },
	{ "getgrid",		"EV",		"<id> <variable>", VTypes::IntegerData,
				"Retrieve data for grid with id specified, placing in variable supplied" },
	{ "gridalpha",		"E",		"<alpha>", VTypes::IntegerData,
				"Set the alpha value of the surface (when not using a colourscale)" },
	{ "gridaxes",		"EEEEEEEEE",	"<ax> <ay> <az> <bx> <by> <bz> <cx> <cy> <cz>", VTypes::IntegerData,
				"Set axis system for the current grid" },
	{ "gridcolour",		"EEEe",		"<r> <g> <b> [a]", VTypes::IntegerData,
				"Set the (positive) colour of the surface (when not using a colourscale)" },
	{ "gridcolournegative",	"EEEe",		"<r> <g> <b> [a]", VTypes::IntegerData,
				"Set the negative colour of the surface (when not using a colourscale)" },
	{ "gridcolourscale",	"E",		"<scaleID>", VTypes::IntegerData,
				"Links the surface to the specified colour scale (or zero to return to internal colour)" },
	{ "gridcubic",		"E",		"<l>", VTypes::IntegerData,
				"Setup a cubic axis system for the current grid" },
	{ "gridcutoff",		"E",		"<cutoff>", VTypes::IntegerData,
				"Set the cutoff for the current grid" },
	{ "gridlooporder",	"N",		"<xyz|zyx|213...>", VTypes::IntegerData,
				"Set the loop ordering to use in 'addnextgridpoint'" },
	{ "gridorigin",		"EEE",		"<x> <y> <z>", VTypes::IntegerData,
				"Set the origin of the axes system for the current grid" },
	{ "gridortho",		"EEE",		"<a> <b> <c>", VTypes::IntegerData,
				"Setup an orthorhombic axis system for the current grid" },
	{ "gridsize",		"EEE",		"<nx> <ny> <nz>", VTypes::IntegerData,
				"Set the number of points along each axis for the current grid" },
	{ "gridstyle",		"N",		"<style>", VTypes::IntegerData,
				"Set the drawing style of the current grid" },
	{ "gridsymmetric",	"N",		"yes|no", VTypes::IntegerData,
				"Set whether the isodata is symmetric about zero (i.e. whether to draw both halves)" },
	{ "gridusez",		"N",		"yes|no", VTypes::IntegerData,
				"Whether a 2D surface uses the vertex data value as its z (height) data" },
	{ "loadgrid",		"N",		"<gridfile>", VTypes::IntegerData,
				"Load grid data" },
	{ "newgrid",		"N",		"<title>", VTypes::IntegerData,
				"Create new grid data" },

	// Image commands
	{ "savebitmap",		"NNnnn",	"<format> <filename> [width] [height] [quality, 0-100]", VTypes::IntegerData,
				"Save the current model view as a bitmap image: formats available are bmp, jpg, png, ppm, xbm, and xpm" },
	{ "savevector",		"NN",		"<format> <filename>", VTypes::IntegerData,
				"Save the current model view as a vector image: formats available are ps, eps, tex, pdf, svg, and pgf" },
	
	// Labeling commands
	{ "clearlabels",	"",		"", VTypes::IntegerData,
				"Remove all atom labels in the current model" },
	{ "label",		"Nn",		"<label> [id]", VTypes::IntegerData,
				"Add labels to the current atom selection (or specified atom)" },
	{ "removelabel",	"Nn",		"<label> [id]", VTypes::IntegerData,
				"Remove labels from the current atom selection (or specified atom)" },
	{ "removelabels",	"n",	"[id]", VTypes::IntegerData,
				"Remove all labels from the current atom selection (or specified atom)" },

	// MC commands
	{ "mcaccept",		"NE",		"<movetype> <energy>", VTypes::IntegerData,
				"Set Monte Carlo move type acceptance energies" },
	{ "mcallow",		"NN",		"<movetype> yes|no", VTypes::IntegerData,
				"Restrict or allow Monte Carlo move types" },
	{ "mcmaxstep",		"NE",		"<movetype> <step>", VTypes::IntegerData,
				"Set maximum step sizes for Monte Carlo move types" },
	{ "mcntrials",		"NE",		"<movetype> <ntrials>", VTypes::IntegerData,
				"Set trial numbers for Monte Carlo move types" },
	{ "printmc",		"",		"", VTypes::IntegerData,
				"Print current Monte Carlo parameters" },
	
	// Measurements
	{ "angle",		"EEEv",		"<id1> <id2> <id3> [result]", VTypes::IntegerData,
				"Measure angle between atoms specified (and put in variable if supplied)" },
	{ "angles",		"",		"", VTypes::IntegerData,
				"Measure bond angles between atoms in current selection" },
	{ "clearmeasurements",	"",		"", VTypes::IntegerData,
				"Clear all measurements in the current model" },
	{ "distance",		"EEv",		"<id1> <id2> [result]", VTypes::IntegerData,
				"Measure distance between atoms specified (and put in variable if supplied)" },
	{ "distances",		"",		"", VTypes::IntegerData,
				"Measure bond distances between atoms in current selection" },
	{ "listmeasurements",	"",		"", VTypes::IntegerData,
				"List all measurements in the current model" },
	{ "measure",		"EEee",		"<id1> <id2> [id3] [id4]", VTypes::IntegerData,
				"Make a measurement between the specified atoms" },
	{ "torsion",		"EEEEv",	"<id1> <id2> <id3> <id4> [result]", VTypes::IntegerData,
				"Measure torsion angle between atoms specified (and put in variable if supplied)" },
	{ "torsions",		"",		"", VTypes::IntegerData,
				"Measure torsion angles between atoms in current selection" },

	// Messaging
	{ "error",		"G",		"<message>", VTypes::IntegerData,
				"Raise an error message (causes exit of current command list)" },
	{ "print",		"G",		"<message>", VTypes::IntegerData,
				"Print a message" },
	{ "verbose",		"G",		"<message>", VTypes::IntegerData,
				"Print a message when verbose output is enabled" },
	{ "warn",		"G",		"<message>", VTypes::IntegerData,
				"Raise a warning message (command list will continue)" },
	
	// Minimisation commands
	{ "cgminimise",		"",		"", VTypes::IntegerData,
				"Run a conjugate gradient minimiser on the current model" },
	{ "converge",		"EE",		"<energy> <forces>", VTypes::IntegerData,
				"Set energy and RMS force convergence limits for minimisation algorithms" },
	{ "linetol",		"E",		"<tolerance>", VTypes::IntegerData,
				"Set tolerance of line minimiser" },
	{ "mcminimise",		"E",		"<maxsteps>", VTypes::IntegerData,
				"Run Monte Carlo minimiser on the current model" },
	{ "sdminimise",		"E",		"<maxsteps>", VTypes::IntegerData,
				"Run steepest descent minimiser on the current model" },
	{ "simplexminimise",	"",		"", VTypes::IntegerData,
				"Run the Simplex minimiser on the current model" },
	
	// Model commands
	{ "createatoms",	"",		"", VTypes::IntegerData,
				"Create enough atoms in the current trajectory frame to match the parent model" },
	{ "currentmodel",	"N",		"[model]", VTypes::IntegerData,
				"Print the name of the current model, or set the current displayed model" },
	{ "finalisemodel",	"",		"", VTypes::IntegerData,
				"Finalise the current model" },
	{ "firstmodel",		"",		"", VTypes::IntegerData,
				"Make the first loaded/created model current" },
	{ "getmodel",		"Nm",		"<name> [variable]", VTypes::IntegerData,
				"Select the named (loaded) model and make it current [and set variables]" },
	{ "info",		"",		"", VTypes::IntegerData,
				"Print data on the current model" },
	{ "lastmodel",		"",		"", VTypes::IntegerData,
				"Make the last loaded/created model current" },
	{ "listmodels",		"",		"", VTypes::IntegerData,
				"List the currently-loaded models" },
	{ "loadmodel",		"Nn",		"<filename> [name]", VTypes::IntegerData,
				"Load a model from file" },
	{ "loginfo",		"",		"", VTypes::IntegerData,
				"Print log information for model" },
	{ "modeltemplate",	"",		"", VTypes::IntegerData,
				"Template the atoms in the current trajectory frame, matching the parent model" },
	{ "newmodel",		"N",		"<name>", VTypes::IntegerData,
				"Create a new model" },
	{ "nextmodel",		"",		"", VTypes::IntegerData,
				"Skip to the next loaded model" },
	{ "prevmodel",		"",		"", VTypes::IntegerData,
				"Skip to the previous loaded model" },
	{ "savemodel",		"NN",		"<format> <filename>", VTypes::IntegerData,
				"Save the current model to <filename> in the specified model <format>" },
	{ "setname",		"N",		"<name>", VTypes::IntegerData,
				"Set the name of the current model" },

	// Pattern commands
	{ "clearpatterns",	"",		"", VTypes::IntegerData,
				"Remove all pattern definitions from the current model" },
	{ "createpatterns",	"",		"", VTypes::IntegerData,
				"Automatically determine pattern definitions for the current model" },
	{ "getpattern",		"Np",		"<name|id> [variable]", VTypes::IntegerData,
				"Select the named pattern (or pattern id) and make it current" },
	{ "listpatterns",	"",		"", VTypes::IntegerData,
				"Print the pattern definition for the current model" },
	{ "newpattern",		"NEE",		"<name> <nmolecules> <atoms per molecule>", VTypes::IntegerData,
				"Add a pattern definition 'node' to the current model" },

	// Preferences commands
	{ "anglelabel",		"N",		"<text>", VTypes::IntegerData,
				"Set the units label to use for angles" },
	{ "atomdetail",		"E",		"<n>", VTypes::IntegerData,
				"Set the quadric detail of atoms" },
	{ "bonddetail",		"E",		"<n>", VTypes::IntegerData,
				"Set the quadric detail of bonds" },
	{ "colour",		"NEEEe",	"<colour> <r> <g> <b> [a]", VTypes::IntegerData,
				"Set the specified colour" },
	{ "commonelements",	"N",		"<elements...>", VTypes::IntegerData,
				"Set the common elements that appear in the Select Element dialog" },
	{ "densityunits",	"N",		"atomsperang|gpercm", VTypes::IntegerData,
				"Set the unit of density to use" },
	{ "distancelabel",	"N",		"<text>", VTypes::IntegerData,
				"Set the units label to use for distances" },
	{ "ecut",		"N",		"<cutoff>", VTypes::IntegerData,
				"Set the electrostatic cutoff distance" },
	{ "elec",		"Neeee",	"<none|coulomb|ewald|ewaldauto> [ <precision> | <alpha> <kx> <ky> <kz> ]", VTypes::IntegerData,
				"Set the style of electrostatic energy calculation" },
	{ "elementambient",	"NEEE",		"<element> <r> <g> <b>", VTypes::IntegerData,
				"Set ambient colour of element" },
	{ "elementdiffuse",	"NEEE",		"<element> <r> <g> <b>", VTypes::IntegerData,
				"Set diffuse colour of element" },
	{ "elementradius",	"NE",		"<element> <radius>", VTypes::IntegerData,
				"Set effective radius of element" },
	{ "energyunits",	"N",		"j|kj|cal|kcal|ha", VTypes::IntegerData,
				"Set the unit of energy to use" },
	{ "gl",			"NN",		"<option> <on|off>", VTypes::IntegerData,
				"Turn on/off various OpenGL options: fog, linealias, polyalias, backcull" },
	{ "hdistance",		"E",		"<distance>", VTypes::IntegerData,
				"Set the H-X bond distance to use when adding hydrogen" },
	{ "intra",		"N",		"<on|off>", VTypes::IntegerData,
				"Turn on/off energy and force calculation of intramolecular terms" },
	{ "key",		"NN",		"ctrl|shift|alt <action>", VTypes::IntegerData,
				"Set the action of modifier keys" },
	{ "labelsize",		"E",		"<pointsize>", VTypes::IntegerData,
				"Set the integer pointsize for label text" },
	{ "light",		"N",		"<on|off>", VTypes::IntegerData,
				"Turn the spotlight on/off" },
	{ "lightambient",	"EEE",		"<r> <g> <b>", VTypes::IntegerData,
				"Set the ambient colour component of the spotlight" },
	{ "lightdiffuse",	"EEE",		"<r> <g> <b>", VTypes::IntegerData,
				"Set the diffuse colour component of the spotlight" },
	{ "lightposition",	"EEE",		"<x> <y> <z>", VTypes::IntegerData,
				"Set the coordinates of the spotlight" },
	{ "lightspecular",	"EEE",		"<r> <g> <b>", VTypes::IntegerData,
				"Set the specular colour component of the spotlight" },
	{ "mouse",		"NN",		"left|middle|right|wheel <action>", VTypes::IntegerData,
				"Set the action of mouse buttons" },
	{ "radius",		"NE",		"<style> <r>", VTypes::IntegerData,
				"Set the general atom scales for view styles" },
	{ "replicatefold",	"N",		"<on|off>", VTypes::IntegerData,
				"Set whether to fold atoms before cell replicate" },
	{ "replicatetrim",	"N",		"<on|off>", VTypes::IntegerData,
				"Set whether to trim atoms after cell replicate" },
	{ "scheme",		"n",		"[colour scheme]", VTypes::IntegerData,
				"Show (or set) the atomic colouring scheme to use" },
	{ "shininess",		"E",		"<n>", VTypes::IntegerData,
				"Set the shininess of atoms" },
	{ "showonscreen",	"nn",		"[object  yes|no]", VTypes::IntegerData,
				"Set (or lists) the visibility of view objects on-screen" },
	{ "showonimage",	"nn",		"[object  yes|no]", VTypes::IntegerData,
				"Set (or lists) the visibility of view objects on saved images" },
	{ "style",		"n",		"[style]", VTypes::IntegerData,
				"Set (or show) the current model drawing style" },
	{ "swapbuffers",	"n",		"[on|off]", VTypes::IntegerData,
				"Set (or show) the current model drawing style" },
	{ "usenicetext",	"N",		"<<on|off>>", VTypes::IntegerData,
				"Use QPainter (on) or QGlWidget (off) to render label text" },
	{ "vcut",		"E",		"<cutoff>", VTypes::IntegerData,
				"Set the VDW cutoff distance" },
	{ "vdw",		"N",		"<on|off>", VTypes::IntegerData,
				"Turn on/off VDW energy/force calculation" },
	{ "zoomthrottle",	"n",		"[ratio]", VTypes::IntegerData,
				"Display (or set) the zooming throttle" },

	// Read / Write Commands
	{ "addreadoption",	"N",		"<option>", VTypes::IntegerData,
				"Add a read option: usequotes, skipblanks, stripbrackets" },
	{ "find",		"NVv",		"<string> <resultvar> [linevar]", VTypes::IntegerData,
				"Search for a string in the input file" },
	{ "getline",		"C",		"<variable>", VTypes::IntegerData,
				"Read the next line from the file and place it in the supplied variable" },
	{ "readchars",		"VE",		"<variable> <nchars>", VTypes::IntegerData,
				"Read a number of characters from the input file" },
	{ "readfloat",		"V",		"<variable>", VTypes::IntegerData,
				"Read a floating point value from the input file" },
	{ "readint",		"V",		"<variable>", VTypes::IntegerData,
				"Read an integer value from the input file" },
	{ "readline",		"F",		"<formatting string>", VTypes::IntegerData,
				"Read and parse a line from the input file" },
	{ "readnext",		"V",		"<variable>", VTypes::IntegerData,
				"Read the next delimited item from the file" },
	{ "readvar",		"VJ",		"<variable> <formatting string>", VTypes::IntegerData,
				"Parse a variable according to the supplied format" },
	{ "removereadoption",	"N",		"<option>", VTypes::IntegerData,
				"Remove a read option" },
	{ "rewind",		"",		"", VTypes::IntegerData,
				"Rewind to the start of the input file" },
	{ "skipchars",		"E",		"<nchars>", VTypes::IntegerData,
				"Skip a number of characters in the input file" },
	{ "skipline",		"e",		"[nlines]", VTypes::IntegerData,
				"Skip a number of lines in the input file" },
	{ "writeline",		"G",		"<formatting string>", VTypes::IntegerData,
				"Write a line to the output file" },
	{ "writevar",		"VK",		"<variable> <formatting string>", VTypes::IntegerData,
				"Write a line to the specified variable" },

	// Script commands
	{ "listscripts",	"",		"", VTypes::IntegerData,
				"List available scripts" },
	{ "loadscript",		"Nn",		"<filename> [nickname]", VTypes::IntegerData,
				"Load script from file" },
	{ "runscript",		"N",		"<name>", VTypes::IntegerData,
				"Execute the named script" },

	// Selection commands
	{ "deselect",		"Q*",		"<id|el|id-id|el-el|+id|+el|id+|el+,...>", VTypes::IntegerData,
				"Deselect specific atoms / ranges in the current model" },
	{ "deselecttype",	"NN",		"<element> <typedesc>", VTypes::IntegerData,
				"Deselect all atoms that match the provided atomtype description" },
	{ "expand",		"",		"", VTypes::IntegerData,
				"Expands the current atom selection" },
	{ "invert",		"",		"", VTypes::IntegerData,
				"Invert the current selection" },
	{ "select",		"Q*",		"<id|el|id-id|el-el|+id|+el|id+|el+,...>", VTypes::IntegerData,
				"Select specific atoms / ranges in the current model" },
	{ "selectall",		"",		"", VTypes::IntegerData,
				"Select all atoms in the current model" },
	{ "selectfftype",	"N",		"<typename>", VTypes::IntegerData,
				"Select all atoms of a specific forcefield type" },
	{ "selectioncog",	"vvv",		"[cogx cogy cogz]", VTypes::IntegerData,
				"Get centre of geometry of current selection (and place in variables if supplied" },
	{ "selectioncom",	"vvv",		"[cogx cogy cogz]", VTypes::IntegerData,
				"Get centre of mass of current selection (and place in variables if supplied" },
	{ "selectnone",		"",		"", VTypes::IntegerData,
				"Deselect all atoms in the current model" },
	{ "selectoverlaps",	"E",		"<tolerance>", VTypes::IntegerData,
				"Select all atoms which are within a given distance of each other" },
	{ "selectpattern",	"n",		"[name]", VTypes::IntegerData,
				"Select all atoms in the current (or named) pattern" },
	{ "selecttype",		"NN",		"<element> <typedesc>", VTypes::IntegerData,
				"Select all atoms that match the provided atomtype description" },
	
	// Site commands
	{ "getsite",		"N",		"<name>", VTypes::IntegerData,
				"Select the defined site and make it current" },
	{ "listsites",		"",		"", VTypes::IntegerData,
				"Print all sites defined for the current model" },
	{ "newsite",		"NNn",		"<name> <pattern> [atomlist]", VTypes::IntegerData,
				"Adds a new site definition to the current model" },
	{ "siteaxes",		"NN",		"<atomlist> <atomlist>", VTypes::IntegerData,
				"Set the axis definitions for the current site" },

	// System commands
	{ "debug",		"N",		"<mode>", VTypes::IntegerData,
				"Toggle debugging for the specified mode" },
	{ "gui",		"",		"", VTypes::IntegerData,
				"Start the GUI (if it is not already active)" },
	{ "help",		"N",		"<command>", VTypes::IntegerData,
				"Provide short help on the command supplied" },
	{ "seed",		"E",		"<seed>", VTypes::IntegerData,
				"Set the random seed" },
	{ "quit",		"",		"", VTypes::IntegerData,
				"Exit the program" },
	{ "version",		"",		"", VTypes::IntegerData,
				"Print program version information" },

	// Trajectory commands
	{ "finaliseframe",	"",		"", VTypes::IntegerData,
				"Finalise the current trajectory frame" },
	{ "firstframe",		"",		"", VTypes::IntegerData,
				"Go to the first frame in the current trajectory" },
	{ "lastframe",		"",		"", VTypes::IntegerData,
				"Go to the last frame in the current trajectory" },
	{ "loadtrajectory",	"N",		"<filename>", VTypes::IntegerData,
				"Load the specified trajectory and associate it to the current model" },
	{ "nextframe",		"",		"", VTypes::IntegerData,
				"Go to the next frame in the current trajectory" },
	{ "prevframe",		"",		"", VTypes::IntegerData,
				"Go to the previous frame in the current trajectory" },
	{ "seekframe",		"E",		"<frame>", VTypes::IntegerData,
				"Jump to the specified frame in the current trajectory" },
	
	// Transformation commands
	{ "axisrotate",		"EEEeeee",	"<ax> <ay> <ax> <theta> [ox oy oz] | <i> <j> <theta> [ox oy oz]", VTypes::IntegerData,
				"Rotate the current selection about a defined axis and origin" },
	{ "centre",		"EEE",		"<x> <y> <z>", VTypes::IntegerData,
				"Centre the atom selection of the current model at the specified coordinates" },
	{ "matrixconvert",	"EEEEEEEEEEEEeeeeeeeee","<i_sx> <j_sx> <i_sy> <j_sy> <i_sz> <j_sz> <i_dx> <j_dx> <i_dy> <j_dy> <i_dz> <j_dz> [ox oy oz] | <sax> <say> <saz> <sbx> <sby> <sbz> <scx> <scy> <scz> <dax> <day> <daz> <dbx> <dby> <dbz> <dcx> <dcy> <dcz> [ox oy oz]", VTypes::IntegerData,
				"Transform selected atoms in reference frame specified to destination frame specified" },
	{ "matrixtransform",	"EEEEEEEEEeee",	"<ax> <ay> <az> <bx> <by> <bz> <cx> <cy> <cz> [ox oy oz]", VTypes::IntegerData,
				"Transform selected atoms by the matrix supplied" },
	{ "mirror",		"N",		"<axis>", VTypes::IntegerData,
				"Mirror the atom selection of the current model about its geometric centre in the specified axis" },
	{ "translate",		"EEE",		"<dx> <dy> <dz>", VTypes::IntegerData,
				"Translate the atom selection of the current model" },
	{ "translateatom",	"EEE",		"<dx> <dy> <dz>", VTypes::IntegerData,
				"Translate the current atom" },
	{ "translatecell",	"EEE",		"<dx> <dy> <dz>", VTypes::IntegerData,
				"Translate the current selection along the cell axes by the fractional axes specified" },

	// Variables
	{ "character",		"",		"<variables>", VTypes::IntegerData,
				"Create character (string) variables with the names provided" },
	{ "integer",		"",		"<variables>", VTypes::IntegerData,
				"Create integer variables with the names provided" },
	{ "real",		"",		"<variables>", VTypes::IntegerData,
				"Create real (floating-point) variables with the names provided" },
	{ "_constvector_",	"",		"<variables>", VTypes::IntegerData,
				"Create constvectors with the names provided" },
	{ "atom",		"",		"<variables>", VTypes::IntegerData,
				"Create atom& variables with the names provided" },
	{ "bond",		"",		"<variables>", VTypes::IntegerData,
				"Create bond& variables with the names provided" },
	{ "pattern",		"",		"<variables>", VTypes::IntegerData,
				"Create pattern& variables with the names provided" },
	{ "bound",		"",		"<variables>", VTypes::IntegerData,
				"Create bound& variables with the names provided" },
	{ "model",		"",		"<variables>", VTypes::IntegerData,
				"Create model& variables with the names provided" },
	{ "grid",		"",		"<variables>", VTypes::IntegerData,
				"Create grid& variables with the names provided" },
	{ "ffatom",		"",		"<variables>", VTypes::IntegerData,
				"Create ffatom& variables with the names provided" },
	{ "ffbound",		"",		"<variables>", VTypes::IntegerData,
				"Create ffbound& variables with the names provided" },
	{ "_cellvar_",		"",		"<variables>", VTypes::IntegerData,
				"Create cell& variables with the names provided" },
	{ "forcefield",		"",		"<variables>", VTypes::IntegerData,
				"Create forcefield& variables with the names provided" },
	{ "_prefsvar_",		"",		"<variables>", VTypes::IntegerData,
				"Create prefs& variables with the names provided" },
	{ "_elementsvar_",	"",		"<variables>", VTypes::IntegerData,
				"Create elements& variables with the names provided" },
	{ "vector",		"",		"<variables>", VTypes::IntegerData,
				"Create vector variables with the names provided" },
	
	// Variable Manipulation
	{ "afterchar",		"NNV",		"<string> <char> <result>", VTypes::IntegerData,
				"Return part of the <string> after the first occurrence of the character <char>" },
	{ "beforechar",		"NNV",		"<string> <char> <result>", VTypes::IntegerData,
				"Return part of the <string> before the first occurrence of the character <char>" },
	{ "dec",		"V",		"<variable>", VTypes::IntegerData,
				"Decrease the specified variable" },
	{ "inc",		"V",		"<variable>", VTypes::IntegerData,
				"Increase the specified variable" },
	{ "let",		"VOE",		"<variable> [-+/*]= <variable|value|expression>", VTypes::IntegerData,
				"Set the specified variable" },
	{ "letchar",		"V~N",		"<variable> =|+= <variable|value>", VTypes::IntegerData,
				"Set the specified character variable" },
	{ "letptr",		"V=V",		"<variable> = <variable>", VTypes::IntegerData,
				"Set the specified pointer variable" },
	{ "letvector",		"VON",		"<variable> = <variable>", VTypes::IntegerData,
				"Set the specified vector variable" },
	{ "normalise",		"VVV",		"<x> <y> <z>", VTypes::IntegerData,
				"Normalise the values of the 3-vector supplied" },
	{ "+",			"",		"", VTypes::NoData,
				"Internal Operator (+)" },
	{ "/",			"",		"", VTypes::NoData,
				"Internal Operator (/)" },
	{ "*",			"",		"", VTypes::NoData,
				"Internal Operator (*)" },
	{ "^",			"",		"", VTypes::NoData,
				"Internal Operator (^)" },
	{ "-",			"",		"", VTypes::NoData,
				"Internal Operator (-)" },
	{ "stripchars",		"VN",		"<variable> <chars>", VTypes::IntegerData,
				"Strip all occurrences of the supplied characters from <variable>" },
	
	// View
	{ "getview",		"",		"", VTypes::IntegerData,
				"Print the rotation matrix, camera position, and camera z-rotation for the current model" },
	{ "orthographic",	"",		"", VTypes::IntegerData,
				"Render in an orthographic projection" },
	{ "perspective",	"e",		"[fov]", VTypes::IntegerData,
				"Render in a perspective projection" },
	{ "resetview",		"",		"", VTypes::IntegerData,
				"Reset the camera and rotation for the current model" },
	{ "rotateview",		"EE",		"<x> <y>", VTypes::IntegerData,
				"Rotate the current model about the x and y axes by the specified amounts" },
	{ "setview",		"EEEEEEEEEEEEe","<ax> <ay> <az> <bx> <by> <bz> <cx> <cy> <cz> <camx> <camyu> <camz> [zrot]", VTypes::IntegerData,
				"Set the rotation matrix, camera position, and camera z-rotation for the current model" },
	{ "speedtest",		"e",		"[nrender]", VTypes::IntegerData,
				"Time 100 (or 'nrender') updates of the model display." },
	{ "translateview",	"EEE",		"<dx> <dy> <dz>", VTypes::IntegerData,
				"Translate the camera for the current model" },
	{ "viewalong",		"EEE",		"<x> <y> <z>", VTypes::IntegerData,
				"Set the rotation for the current model so the view is along the specified vector" },
	{ "viewalongcell",	"EEE",		"<x> <y> <z>", VTypes::IntegerData,
				"Set the rotation for the current model so the view is along the specified cell vector" },
	{ "zoomview",		"E",		"<dz>", VTypes::IntegerData,
				"Zoom in/out the camera - equivalent to 'translateview 0 0 dz'" },
	{ "zrotateview",	"E",		"<dr>", VTypes::IntegerData,
				"Rotate the model in the plane of the screen" }
};

// Return enumerated command from string
NuCommand::Function NuCommand::command(const char *s)
{
	int result;
	for (result = NuCommand::NoFunction; result < NuCommand::nFunctions; result++) if (strcmp(data[result].keyword,s) == 0) break;
	return (NuCommand::Function) result;
}

// Constructor
NuCommand::NuCommand()
{
	// Create pointer list
	initPointers();
	// Create dummyCommandList complete with a single dummy command
// 	dummyCommandList_ = new NuCommandList;
// 	dummyCommandNode_ = new NuCommandNode;
// 	dummyCommandNode_->setParent(dummyCommandList_);
}

// Constructor
NuCommand::~NuCommand()
{
// 	delete dummyCommandNode_;
// 	delete dummyCommandList_;
}

// Return whether command accepts any arguments
bool NuCommandData::hasArguments()
{
	return (!(arguments[0] == '\0'));
}

// Execute command
int NuCommand::call(NuCommand::Function cf, NuCommandNode *c, NuReturnValue &rv)
{
// 	return CALL_COMMAND(commands,pointers_[cf])(c, aten.current);
	return (this->pointers_[cf])(c, aten.current, rv);
}

