      MODULE aintgs_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:27:09  03/09/06  
      SUBROUTINE aintgs (X, K) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(IN) :: X 
      INTEGER, INTENT(IN) :: K 
!VAST.../SETC/ A(INOUT)
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
