      MODULE deri1_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  17:23:45  03/12/06  
      SUBROUTINE deri1 (NUMBER, GRAD, F, MINEAR, fd, SCALAR) 
      USE vast_kind_param,ONLY: DOUBLE     
      INTEGER, INTENT(IN) :: NUMBER 
      REAL(DOUBLE), INTENT(OUT) :: GRAD 
      REAL(DOUBLE), DIMENSION(10000), INTENT(INOUT) :: F 
      real(double)  :: fd(*) 
      INTEGER, INTENT(IN) :: MINEAR 
      REAL(DOUBLE), DIMENSION(10000), INTENT(IN) :: SCALAR 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
