      MODULE dgedi_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:10  03/09/06  
      SUBROUTINE dgedi (A, LDA, N, IPVT, JOB) 
      USE vast_kind_param,ONLY: DOUBLE       
      integer, INTENT(IN) :: LDA 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(LDA,N), INTENT(INOUT) :: A 
      integer, DIMENSION(N), INTENT(IN) :: IPVT 
      integer, INTENT(IN) :: JOB 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
