      MODULE dgemm_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:48:56  03/08/06  
      SUBROUTINE dgemm (TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C&
        , LDC) 
      USE vast_kind_param,ONLY: DOUBLE 
      character (LEN = *) :: TRANSA 
      character (LEN = *) :: TRANSB 
      integer, INTENT(IN) :: M 
      integer, INTENT(IN) :: N 
      integer, INTENT(IN) :: K 
      integer, INTENT(IN) :: LDA 
      integer, INTENT(IN) :: LDB, ldc 
      real(DOUBLE), INTENT(IN) :: ALPHA 
      real(DOUBLE), DIMENSION(LDA,*), INTENT(IN) :: A       
      real(DOUBLE), DIMENSION(LDB,*), INTENT(IN) :: B       
      real(DOUBLE), INTENT(IN) :: BETA 
      real(DOUBLE), DIMENSION(LDC,*), INTENT(INOUT) :: C  
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
