      MODULE dger_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:48:56  03/08/06  
      SUBROUTINE dger (M, N, ALPHA, X, INCX, Y, INCY, A, LDA) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: M 
      integer, INTENT(IN) :: N, LDA
      real(DOUBLE), INTENT(IN) :: ALPHA 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: X 
      integer, INTENT(IN) :: INCX 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: Y 
      integer, INTENT(IN) :: INCY 
      real(DOUBLE), DIMENSION(LDA,*), INTENT(INOUT) :: A 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
