      MODULE dmecip_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  14:15:03  03/10/06  
      SUBROUTINE dmecip (COEFFS, DELTAP, DELTA, CDIAG, CIF2, EIG, VECTCI, CONF) 
      USE vast_kind_param,ONLY: DOUBLE 
      use molkst_C, only : norbs
      use meci_C, only : nmos
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: COEFFS 
      real(DOUBLE), DIMENSION(NMOS,NMOS), INTENT(INOUT) :: DELTAP 
      real(DOUBLE), DIMENSION(NORBS,NMOS), INTENT(IN) :: DELTA 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: CDIAG 
      real(DOUBLE), INTENT(IN) :: CIF2 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: EIG  
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: VECTCI 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: CONF 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
