      MODULE dscal_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:48:56  03/08/06  
      SUBROUTINE dscal (N, DA, DX, INCX) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), INTENT(IN) :: DA 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: DX 
      integer, INTENT(IN) :: INCX 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
