      MODULE dswap_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:48:56  03/08/06  
      SUBROUTINE dswap (N, DX, INCX, DY, INCY) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: DX 
      integer, INTENT(IN) :: INCX 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: DY 
      integer, INTENT(IN) :: INCY 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
