      MODULE dtrans_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:33:49  03/09/06  
      SUBROUTINE dtrans (D, H, IOPER, FIRST, R) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(5), INTENT(INOUT) :: D 
      REAL(DOUBLE), DIMENSION(5), INTENT(INOUT) :: H 
      INTEGER, INTENT(IN) :: IOPER 
      LOGICAL, INTENT(INOUT) :: FIRST 
      REAL(DOUBLE), DIMENSION(3,3), INTENT(IN) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
