      MODULE efsav_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:10  03/09/06  
      SUBROUTINE efsav (TT0, HESS, FUNCT, GRAD, XPARAM, PMAT, IL, JL, BMAT, IPOW) 
      USE vast_kind_param,ONLY: DOUBLE 
      doubleprecision DUMY
      real(DOUBLE), INTENT(INOUT) :: TT0 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: HESS 
      real(DOUBLE), INTENT(IN) :: FUNCT 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: GRAD 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: XPARAM 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: PMAT 
      integer, INTENT(IN) :: IL 
      integer, INTENT(IN) :: JL 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: BMAT 
      integer, DIMENSION(9), INTENT(INOUT) :: IPOW
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
