      MODULE efstr_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:10  03/09/06  
      SUBROUTINE efstr (XPARAM, FUNCT, IHESS, NTIME, ILOOP, IGTHES, MXSTEP&
        , IRECLC, IUPD, DMAX, DDMAX, DMIN, TOL2, TIME1, TIME2, NVAR, SCF1, LUPD&
        , LDUMP, LOG, RRSCAL, DONR, GNMIN, HESS, BMAT, PMAT) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(*) :: XPARAM 
      real(DOUBLE) :: FUNCT 
      integer, INTENT(OUT) :: IHESS 
      integer, INTENT(OUT) :: NTIME 
      integer, INTENT(OUT) :: ILOOP 
      integer, INTENT(INOUT) :: IGTHES 
      integer, INTENT(OUT) :: MXSTEP 
      integer, INTENT(OUT) :: IRECLC 
      integer, INTENT(INOUT) :: IUPD 
      real(DOUBLE), INTENT(OUT) :: DMAX 
      real(DOUBLE), INTENT(OUT) :: DDMAX 
      real(DOUBLE), INTENT(OUT) :: DMIN 
      real(DOUBLE), INTENT(OUT) :: TOL2 
      real(DOUBLE), INTENT(OUT) :: TIME1 
      real(DOUBLE), INTENT(OUT) :: TIME2 
      integer, INTENT(INOUT) :: NVAR 
      logical, INTENT(OUT) :: SCF1 
      logical, INTENT(OUT) :: LUPD 
      integer, INTENT(OUT) :: LDUMP 
      logical, INTENT(OUT) :: LOG 
      logical, INTENT(OUT) :: RRSCAL 
      logical, INTENT(OUT) :: DONR 
      logical, INTENT(OUT) :: GNMIN 
      real(DOUBLE), DIMENSION(NVAR,NVAR) :: HESS 
      real(DOUBLE), DIMENSION(NVAR,NVAR) :: BMAT 
      real(DOUBLE), DIMENSION(NVAR,NVAR) :: PMAT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
