      MODULE fbx_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE fbx 
!VAST.../XFACT/ FACTE(INOUT), B(INOUT)
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
