      MODULE fmat_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:14  03/09/06  
      SUBROUTINE fmat (FMATRX, NREAL, TSCF, TDER, DELDIP, HEAT,  EVECS,coordl) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(OUT) :: FMATRX 
      INTEGER, INTENT(OUT) :: NREAL 
      REAL(DOUBLE), INTENT(IN) :: TSCF 
      REAL(DOUBLE), INTENT(IN) :: TDER 
      REAL(DOUBLE), DIMENSION(3,*), INTENT(OUT) :: DELDIP 
      REAL(DOUBLE) :: HEAT 
      REAL(DOUBLE), DIMENSION(*) :: coordl
      REAL(DOUBLE), DIMENSION(*) :: EVECS 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
