      MODULE formxd_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE formxd (WD, NWII, NWJJ, WCA, WCB, CA, NA, CB, NB) 
      USE vast_kind_param,ONLY: DOUBLE 
      use molkst_C, only : lm6
      real(DOUBLE), DIMENSION(LM6,LM6), INTENT(IN) :: WD 
      integer, INTENT(IN) :: NWII 
      integer, INTENT(IN) :: NWJJ 
      real(DOUBLE), DIMENSION(45), INTENT(INOUT) :: WCA 
      real(DOUBLE), DIMENSION(45), INTENT(INOUT) :: WCB 
      real(DOUBLE), DIMENSION(45), INTENT(IN) :: CA 
      integer, INTENT(IN) :: NA 
      real(DOUBLE), DIMENSION(45), INTENT(IN) :: CB 
      integer, INTENT(IN) :: NB 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
