      MODULE gethes_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:12:16  03/10/06  
      SUBROUTINE gethes (XPARAM, IGTHES, NVAR, ILOOP, HESS, PMAT, BMAT) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(*), INTENT(OUT) :: XPARAM 
      integer, INTENT(IN) :: IGTHES 
      integer, INTENT(IN) :: NVAR 
      integer, INTENT(IN) :: ILOOP 
      real(DOUBLE), DIMENSION(NVAR,NVAR), INTENT(INOUT) :: HESS 
      real(DOUBLE), DIMENSION(NVAR*NVAR) :: PMAT 
      real(DOUBLE), DIMENSION(NVAR,NVAR) :: BMAT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
