      MODULE ilaenv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:04  03/09/06  
      INTEGER FUNCTION ilaenv (ISPEC, NAME, N1, N2, N4) 
      integer, INTENT(IN) :: ISPEC 
      character (LEN = *), INTENT(IN) :: NAME 
      integer, INTENT(IN) :: N1 
      integer, INTENT(IN) :: N2 
      integer, INTENT(IN) :: N4 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
