      MODULE interp_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:21  03/09/06  
      subroutine interp(np, nq, mode, e, fp, cp) 
      USE vast_kind_param,ONLY: DOUBLE 
      use molkst_C, only : norbs
      integer  :: np 
      integer  :: nq 
      integer , intent(inout) :: mode 
      real(double) , intent(in) :: e 
      real(double) , intent(in) :: fp((norbs*(norbs + 1))/2) 
      real(double) , intent(inout) :: cp(norbs,norbs) 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
