      MODULE local_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:23  03/09/06  
      SUBROUTINE local (C, NOCC, EIG) 
      USE vast_kind_param,ONLY: DOUBLE 
      use molkst_C, only : norbs
      REAL(DOUBLE), DIMENSION(norbs, norbs), INTENT(INOUT) :: C 
      INTEGER, INTENT(IN) :: NOCC 
      REAL(DOUBLE), DIMENSION(norbs), INTENT(INOUT) :: EIG 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
