      MODULE mpcpop_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:29  03/09/06  
      SUBROUTINE mpcpop (C, ICOK) 
      USE vast_kind_param,ONLY: DOUBLE 
      use molkst_C, only : norbs
      REAL(DOUBLE), DIMENSION(NORBS*NORBS), INTENT(IN) :: C 
      integer, intent(in) :: icok
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
