      MODULE overlp_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:12:16  03/10/06  
      SUBROUTINE overlp (DMAX, OSMIN, NEWMOD, NVAR, LORJK, U) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), INTENT(IN) :: DMAX 
      real(DOUBLE), INTENT(IN) :: OSMIN 
      integer, INTENT(OUT) :: NEWMOD 
      integer, INTENT(IN) :: NVAR 
      logical, INTENT(OUT) :: LORJK 
      real(DOUBLE), DIMENSION(NVAR,NVAR), INTENT(IN) :: U 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
