      MODULE partxy_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:32  03/09/06  
      SUBROUTINE partxy (C34, PQ34, W, WD) 
      USE vast_kind_param,ONLY: DOUBLE 
      use molkst_C, only : lm6
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: C34 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: PQ34 
      REAL(DOUBLE), DIMENSION(*) :: W 
      REAL(DOUBLE), DIMENSION(LM6,LM6), INTENT(IN) :: WD 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
