      MODULE rotatd_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE rotatd (IP, JP, IA, IB, JA, JB, NI, NJ, CI, CJ, W, LMW, ENUC) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer :: IP 
      integer :: JP 
      integer, INTENT(IN) :: IA 
      integer, INTENT(IN) :: IB 
      integer, INTENT(IN) :: JA 
      integer, INTENT(IN) :: JB 
      integer :: NI 
      integer :: NJ 
      real(DOUBLE) :: CI(3) 
      real(DOUBLE) :: CJ(3)
      real(DOUBLE), dimension(*) :: W 
      integer :: LMW 
      real(DOUBLE) :: ENUC 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
