      MODULE rsp_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:05:01  03/09/06  
      SUBROUTINE rsp (A, N, NVECT, ROOT, VECT) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*) :: A 
      INTEGER, INTENT(IN) :: N 
      INTEGER :: NVECT 
      REAL(DOUBLE), DIMENSION(N), intent(out) :: ROOT 
      REAL(DOUBLE), DIMENSION(N,N), intent(out) :: VECT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
