      MODULE timout_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:16  03/09/06  
      SUBROUTINE timout (NOUT, TIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NOUT 
      REAL(DOUBLE), INTENT(IN) :: TIM 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
