      MODULE updhes_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:12:16  03/10/06  
      SUBROUTINE updhes (SVEC, TVEC, NVAR, IUPD, HESS) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: SVEC 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: TVEC 
      integer, INTENT(IN) :: NVAR 
      integer, INTENT(IN) :: IUPD 
      real(DOUBLE), DIMENSION(NVAR,NVAR), INTENT(INOUT) :: HESS 
!VAST.../OPTEF/ OLDF(IN), D(INOUT), DD(IN), IPRNT(IN)
!VAST.../GRADNT/ GRAD(IN)
!VAST.../NUMCAL/ NUMCAL(IN)
!VAST...Calls: DOT
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
