      MODULE wstore_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE wstore (W) 
      USE vast_kind_param,ONLY: DOUBLE 
      use molkst_C, only : lm6
      real(DOUBLE), DIMENSION(LM6,LM6), INTENT(INOUT) :: W 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
