      SUBROUTINE XERBLA( SRNAME, INFO )
*
*  -- LAPACK AUXILIARY ROUTINE (VERSION 1.0B) --
*     UNIV. OF TENNESSEE, UNIV. OF CALIFORNIA BERKELEY, NAG LTD.,
*     COURANT INSTITUTE, ARGONNE NATIONAL LAB, AND RICE UNIVERSITY
*     FEBRUARY 29, 1992
*
*     .. SCALAR ARGUMENTS ..
      CHARACTER*6        SRNAME
      INTEGER            INFO
C MOPAC CHANGE
      COMMON /CHANEL/ IFILES(30)
      EQUIVALENCE(IW,IFILES(6))
C END OF MOPAC CHANGE
*     ..
*
*  PURPOSE
*  =======
*
*  XERBLA  IS AN ERROR HANDLER FOR THE LAPACK ROUTINES.
*  IT IS CALLED BY AN LAPACK ROUTINE IF AN INPUT PARAMETER HAS AN
*  INVALID VALUE.  A MESSAGE IS PRINTED AND EXECUTION STOPS.
*
*  INSTALLERS MAY CONSIDER MODIFYING THE STOP STATEMENT IN ORDER TO
*  CALL SYSTEM-SPECIFIC EXCEPTION-HANDLING FACILITIES.
*
*  ARGUMENTS
*  =========
*
*  SRNAME  (INPUT) CHARACTER*6
*          THE NAME OF THE ROUTINE WHICH CALLED XERBLA.
*
*  INFO    (INPUT) INTEGER
*          THE POSITION OF THE INVALID PARAMETER IN THE PARAMETER LIST
*          OF THE CALLING ROUTINE.
*
*     .. EXECUTABLE STATEMENTS ..
*
C MOPAC CHANGE
C     WRITE( *, FMT = 9999 )SRNAME, INFO
      WRITE( IW, FMT = 9999 )SRNAME, INFO
C END OF MOPAC CHANGE
*
      STOP
*
 9999 FORMAT( ' ** ON ENTRY TO ', A6, ' PARAMETER NUMBER ', I2, ' HAD ',
     $      'AN ILLEGAL VALUE' )
*
*     END OF XERBLA
*
      END
