/*
	*** Command Function Definitions
	*** src/command/commands.cpp
	Copyright T. Youngs 2007-2009

	This file is part of Aten.

	Aten is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	Aten is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with Aten.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "command/commands.h"
#include "parser/commandnode.h"
#include "main/aten.h"
#include "base/bundle.h"
#include "parser/tree.h"

// Static singleton
Command commands;

/* Argument Specification Tokens:
       Char	Meaning		Acceptable Types in VTypes
	N	Number		IntegerData, DoubleData
	I	Integer		IntegerData
	R	Real		DoubleData
	C	Character	StringData
	S	Any Simple	IntegerData, DoubleData, StringData
	U	Vector		VectorData
	B	Boolean		Any
	E	Element		StringData,IntegerData,DoubleData,AtomData
	A	Atom/Id		IntegerData, AtomData
	M	Model/ID/Name	ModelData, StringData, IntegerData
	F	Frcefld/ID/Name	ForcefieldData, IntegerData, StringData
	P	Pattern/ID/Name	PatternData, StringData, IntegerData
	G	Grid/ID		GridData, StringData, IntegerData
	X	Pointer		Any pointer object
	V	Variable	Any simple variable (not path)
	Z	Any		Any
	*	<Repeat>	Any number of the last type again
	^	<Require Var>	Next token must be a modifiable variable and not a constant
	[]	<Cluster>	Surrounds groups of optional arguments that must be specified together
	|	<Or>		Separates alternative lists of arguments for the command
	&	<Array>		Next token must be an array
	/	<type Or>	Specifies an argument may be one of two types
	2-9	<NRepeat>	Next argument should occur N times
*/

// Command action
CommandData Command::data[Command::nCommands] = {

	// Operators
	{ "+",			"..",		VTypes::NoData, "",
		"Internal Operator (+)" },
	{ "&&",			"..",		VTypes::NoData, "",
		"Internal Operator (&&)" },
	{ "=",			"..",		VTypes::NoData, "",
		"Internal Operator (=)" },
	{ "/=",			"..",		VTypes::NoData, "",
		"Internal Operator (/=)" },
	{ "*=",			"..",		VTypes::NoData, "",
		"Internal Operator (*=)" },
	{ "+=",			"..",		VTypes::NoData, "",
		"Internal Operator (+=)" },
	{ "-=",			"..",		VTypes::NoData, "",
		"Internal Operator (-=)" },
	{ "/",			"..",		VTypes::NoData, "",
		"Internal Operator (/)" },
	{ "==",			"..",		VTypes::NoData, "",
		"Internal Operator (==)" },
	{ "",			"..",		VTypes::NoData, "",
		"Internal Operator (>)" },
	{ ">=",			"..",		VTypes::NoData, "",
		"Internal Operator (>=)" },
	{ "<",			"..",		VTypes::NoData, "",
		"Internal Operator (<)" },
	{ "<=",			"..",		VTypes::NoData, "",
		"Internal Operator (<=)" },
	{ "%",			"..",		VTypes::NoData, "",
		"Internal Operator (%)" },
	{ "*",			"..",		VTypes::NoData, "",
		"Internal Operator (*)" },
	{ "-NEG",		".",		VTypes::NoData, "",
		"Internal Operator (negate)" },
	{ "!",			"..",		VTypes::NoData, "",
		"Internal Operator (!)" },
	{ "!=",			"..",		VTypes::NoData, "",
		"Internal Operator (!=)" },
	{ "||",			"..",		VTypes::NoData, "",
		"Internal Operator (||)" },
	{ "X--",		"..",		VTypes::NoData, "",
		"Internal Operator (X--)" },
	{ "X++",		"..",		VTypes::NoData, "",
		"Internal Operator (X++)" },
	{ "^",			"..",		VTypes::NoData, "",
		"Internal Operator (^)" },
	{ "--X",		"..",		VTypes::NoData, "",
		"Internal Operator (--X)" },
	{ "++X",		"..",		VTypes::NoData, "",
		"Internal Operator (++X)" },
	{ "-",			"..",		VTypes::NoData, "",
		"Internal Operator (-)" },

	// AST Nodes
	{ "*nofunction*",	"",		VTypes::NoData, "",
		"" },
	{ "*joiner*",		"",		VTypes::NoData, "",
		"" },
	{ "*declaration*",	"^Z*",		VTypes::NoData, "",
		"" },

	// Analysis commands
	{ "finalise",		"",		VTypes::NoData,
		"",
		"Finalise all calculated quantities" },
	{ "frameanalyse",	"",		VTypes::NoData,
		"",
		"Analyse quantities for the current trajectory frame" },
	{ "geometry",		"CNNNCNNnn",	VTypes::NoData,
		"string name, double min, double binwidth, int nbins, string filename, int site1, int site2, int site3 = 0, int site4 = 0",
		"Calculate geometries" },
	{ "modelanalyse",	"",		VTypes::NoData,
		"",
		"Analyse quantities for the current model" },
	{ "pdens",		"CNNCNN",	VTypes::NoData,
		"string name, double griddelta, int nstep, string filename, int site1, int site2",
		"Request calculation of a probability density between sites" },
	{ "listjobs",		"",		VTypes::NoData,
		"",
		"Print the current list of quantities to calculate" },
	{ "rdf",		"CNNNCNN",	VTypes::NoData,
		"string name, double rmin, double binwidth, int nbins, string filename, int site, int site2",
		"Request calculation of radial distribution function between sites" },
	{ "savequantities",	"",		VTypes::NoData,
		"",
		"Save calculated quantities to file" },
	{ "trajanalyse",	"NNn",		VTypes::NoData,
		"int startframe, int frameskip, int nframes = -1",
		"Analyse quantities for all frames in current trajectory" },
	
	// Atom commands
	{ "atomstyle",		"Ca",		VTypes::NoData,
		"string style, atom|int id = 0",
		"Set the individual style of the current atom selection (or supplied atom)" },
	{ "currentatom",	"a",		VTypes::AtomData,
		"atom|int id = <none>",
		"Make the specified atom (or atom id) the current atom, or return current atom" },
	{ "fix",		"a",		VTypes::AtomData,
		"atom|int id = 0",
		"Fix position of current atom selection or specified atom in various methods" },
	{ "free",		"a",		VTypes::AtomData,
		"atom|int id = 0",
		"Free positions of current atom selection or specified atom in various methods" },
	{ "getatom",		"N",		VTypes::AtomData,
		"int id",
		"Retrieve pointer for atom id specified, returning a reference to it" },
	{ "hide",		"a",		VTypes::NoData,
		"atom|int id = 0",
		"Hide the current selection of atoms (or supplied atom)" },
	{ "setcharge",		"Na",		VTypes::NoData,
		"double q, atom|int id = 0",
		"Set the charge of the current (or specified) atom" },
	{ "setcoords",		"NNNa",		VTypes::NoData,
		"double x, double y, double z, atom|int id = 0",
		"Set the coordinates of the current (or specified) atom" },
	{ "setelement",		"Ea",		VTypes::NoData,
		"element el, atom|int id = 0",
		"Set the element of the current (or specified) atom" },
	{ "setforces",		"NNNa",		VTypes::NoData,
		"double fx, double fy, double fz, atom|int id = 0",
		"Set the forces of the current (or specified) atom" },
	{ "setfx",		"Na",		VTypes::NoData,
		"double fx, atom|int id = 0",
		"Set the x force of the current (or specified) atom" },
	{ "setfy",		"Na",		VTypes::NoData,
		"double fy, atom|int id = 0",
		"Set the y force of the current (or specified) atom" },
	{ "setfz",		"Na",		VTypes::NoData,
		"double fz, atom|int id = 0",
		"Set the z force of the current (or specified) atom" },
	{ "setid",		"Na",		VTypes::NoData,
		"int id, atom|int id = 0",
		"Set the id of the current (or specified) atom" },
	{ "setrx",		"Na",		VTypes::NoData,
		"double rx, atom|int id = 0",
		"Set the x coordinate of the current (or specified) atom" },
	{ "setry",		"Na",		VTypes::NoData,
		"double ry, atom|int id = 0",
		"Set the y coordinate of the current (or specified) atom" },
	{ "setrz",		"Na",		VTypes::NoData,
		"double rz, atom|int id = 0",
		"Set the z coordinate of the current (or specified) atom" },
	{ "setvelocities",	"NNNa",		VTypes::NoData,
		"double vx, double vy, double vz, atom|int id = 0",
		"Set the velocities of the current (or specified) atom" },
	{ "setvx",		"Na",		VTypes::NoData,
		"double vx, atom|int id = 0",
		"Set the x velocity of the current (or specified) atom" },
	{ "setvy",		"Na",		VTypes::NoData,
		"double vy, atom|int id = 0",
		"Set the y velocity of the current (or specified) atom" },
	{ "setvz",		"Na",		VTypes::NoData,
		"double vz, atom|int id = 0",
		"Set the z velocity of the current (or specified) atom" },
	{ "show",		"a",		VTypes::NoData,
		"atom|int id = 0",
		"Show (make visible) the current selection of atoms (or supplied atom)" },
	{ "showall",		"",		VTypes::NoData,
		"",
		"Show all atoms in the current model" },

	// Bonding commands
	{ "augment",		"",		VTypes::NoData,
		"",
		"Automatically augment all bonds in the current model" },
	{ "bondtolerance",	"n",		VTypes::DoubleData,
		"double tol = <prefs.bondtolerance",
		"Set bonding tolerance for automatic calculation" },
	{ "clearbonds",		"",		VTypes::NoData,
		"",
		"Delete all bonds in the current model" },
	{ "clearselectedbonds",	"",		VTypes::NoData,
		"",
		"Delete all bonds in the current selection" },
	{ "newbond",		"AAs",		VTypes::NoData,
		"atom|int atom1, atom|int atom2, string|int|double bondtype = 1",
		"Create a bond between specified atoms" },
	{ "newbondid",		"NNs",		VTypes::NoData,
		"int id1, int id2, string|int|double bondtype = 1",
		"Create a bond between atoms with ids specified" },
	{ "rebond",		"b",		VTypes::NoData,
		"bool augment = <aten.prefs.augmentafterrebond>",
		"Calculate bonding in the current model" },
	{ "rebondpatterns",	"b",		VTypes::NoData,
		"bool augment = <aten.prefs.augmentafterrebond>",
		"Calculate bonds between atoms, restricted to atoms in pattern molecules" },
	{ "rebondselection",	"b",		VTypes::NoData,
		"bool augment = <aten.prefs.augmentafterrebond>",
		"Calculate bonds between atoms in the current selection" },

	// Build commands
	{ "addhydrogen",	"a",		VTypes::NoData,
		"atom|int id = 0",
		"Hydrogen satisfy all (or specified) atom in model" },
	{ "bohr",		"X*",		VTypes::NoData,
		"object, [object...]",
		"Convert coordinates in the specified object(s) from Angstroms to Bohr" },
	{ "chain",		"Es|E3Ns",	VTypes::AtomData,
		"element el, string|int|double bondtype = 1  |  element el, double x, double y, double z, string|int|double bondtype = 1",
		"Create a new atom in the current model, bound to the last" },
	{ "endchain",		"",		VTypes::AtomData,
		"",
		"End the current bond chain (the next call to 'chain' will create an unbound atom)" },
	{ "insertatom",		"EN[nnn]",	VTypes::AtomData,
		"element el, int id, double x = 0.0, double y = 0.0, double z = 0.0",
		"Insert a new atom into the model such that it has the ID specified" },
	{ "locate",		"NNN",		VTypes::NoData,
		"double x, double y, double z",
		"Position pen at specified coordinates" },
	{ "move",		"NNN",		VTypes::NoData,
		"double dx, double dy, double dz",
		"Move pen by specified coordinates" },
	{ "movetoend",		"",		VTypes::NoData,
		"",
		"Move current atom selection to end of list" },
	{ "movetostart",	"",		VTypes::NoData,
		"",
		"Move current atom selection to start of list" },
	{ "newatom",		"E[nnn][nnn][nnn]",	VTypes::AtomData,
		"element el, double x = 0.0, double y = 0.0, double z = 0.0, double vx = 0.0, double vy = 0.0, double vz = 0.0, double fx = 0.0, double fy = 0.0, double fz = 0.0",
		"Create a new atom in the current model, with optional coordinates, velocities, and forces" },
	{ "newatomfrac",	"ENNN",		VTypes::AtomData,
		"element el, double fracx, double fracy, double fracz, double vx = 0.0, double vy = 0.0, double vz = 0.0, double fx = 0.0, double fy = 0.0, double fz = 0.0",
		"Create a new atom in the current model, converting fractional coordinates to real coordinates, and with optional velocities and forces" },
	{ "reorder",		"",		VTypes::NoData,
		"",
		"Reorder atoms in the current selection such that bond partners have adjacent atom IDs" },
	{ "resetpen",		"",		VTypes::NoData,
		"",
		"Reset the pen orientation to the identity matrix (but leave the current position intact)" },
	{ "rotx",		"N",		VTypes::NoData,
		"double angle",
		"Rotate pen about its x axis by given angle" },
	{ "roty",		"N",		VTypes::NoData,
		"double angle",
		"Rotate pen about its y axis by given angle" },
	{ "rotz",		"N",		VTypes::NoData,
		"double angle",
		"Rotate pen about its z axis by given angle" },
	{ "selectionaddhydrogen","",		VTypes::NoData,
		"",
		"Hydrogen satisfy selected atoms in model" },
	{ "shiftdown",		"n",		VTypes::NoData,
		"int n = 1",
		"Shift current atom selection down 1 (or 'n') places" },
	{ "shiftup",		"n",		VTypes::NoData,
		"int n = 1",
		"Shift current atom selection up 1 (or 'n') places" },
	{ "transmute",		"E",		VTypes::NoData,
		"element el",
		"Transmute selection to element given" },
	
	// Cell commands
	{ "addgenerator",	"C",		VTypes::NoData,
		"string generator",
		"Manually add a spacegroup generator definition to the current model's cell" },
	{ "adjustcell",		"CN",		VTypes::NoData,
		"string quantity, double change",
		"Adjust a single value of the current cell specification (e.g. <quantity, = a, beta, cz, etc.)" },
	{ "cell",		"NNNNNN",	VTypes::NoData,
		"double a, double b, double c, double alpha, double beta, double gamma",
		"Set or create a unit cell for the current model from lengths/angles provided" },
	{ "cellaxes",		"9N",		VTypes::NoData,
		"double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz",
		"Set or create a unit cell for the current model from the cell axes provided" },
	{ "fold",		"",		VTypes::NoData,
		"",
		"Fold atoms into model's unit cell" },
	{ "foldmolecules",	"",		VTypes::NoData,
		"",
		"Fold molecules (defined by patterns) so that they are unbroken across cell boundaries" },
	{ "fractoreal",		"",		VTypes::NoData,
		"",
		"Convert (assumed) fractional model coordinates to real coordinates" },
	{ "millercut",		"NNNn",		VTypes::NoData,
		"int h, int k, int l, bool inside = FALSE",
		"Cleave the current periodic system along the specified Miller plane" },
	{ "nocell",		"", 		VTypes::NoData,
		"",
		"Remove any cell definition from the current model" },
	{ "pack",		"",		VTypes::NoData,
		"",
		"Pack the unit cell with symmetry operators list in associated spacegroup" },
	{ "printcell",		"",		VTypes::NoData,
		"",
		"Print the unit cell of the current model" },
	{ "replicate",		"NNNNNN",	VTypes::NoData,
		"double negx, double negy, double negz, double posx, double posy, double posz",
		"Replicate the cell by the unit cell amounts specified in each direction, beyond the original cell" },
	{ "rotatecell",		"CN",		VTypes::NoData,
		"string axis, double angle",
		"Rotate the cell and its contents about the specified orthogonal axis (x, y, or z)" },
	{ "scale",		"NNNb",		VTypes::NoData,
		"double x, double y, double z, bool calcenergy = FALSE",
		"Scale the unit cell and atomic positions of the current model" },
	{ "scalemolecules",	"NNNb",		VTypes::NoData,
		"double x, double y, double z, bool calcenergy = FALSE",
		"Scale the unit cell and molecular positions of the current model" },
	{ "setcell",		"CN",		VTypes::NoData,
		"string quantity, double value",
		"Set a single value of the current cell specification (e.g. <quantity, = a, beta, cz, etc.)" },
	{ "sginfo",		"C",		VTypes::IntegerData,
		"string|int spacegroup",
		"Invoke SGInfo, search for the spacegroup name/id provided, and print out its details" },
	{ "spacegroup",		"S",		VTypes::NoData,
		"string|int spacegroup",
		"Set the spacegroup for the current model" },
	
	// Charge commands
	{ "charge",		"n",		VTypes::DoubleData,
		"[double q]",
		"Set charges of atoms in the current selection, or return total charge of current selection" },
	{ "chargeff",		"",		VTypes::NoData,
		"",
		"Charge atoms in the model according to their forcefield atom types" },
	{ "chargefrommodel",	"",		VTypes::NoData,
		"",
		"Charge atoms in the current trajectory frame from the parent model" },
	{ "chargepatom",	"NN",		VTypes::NoData,
		"int id, double q",
		"Set charges for specific atom id in all molecules of the current pattern" },
	{ "chargetype",		"CN",		VTypes::NoData,
		"string type, double q",
		"Set charges of all atoms of the given type" },
	{ "clearcharges",	"",		VTypes::NoData,
		"",
		"Zero all charges in the current model" },

	// Colourscale commands
	{ "addpoint",		"NNNNNn",	VTypes::NoData,
		"int scaleid, double value, double r, double g, double b, double a = 1.0",
		"Add a new point to the specified colourscale" },
	{ "clearpoints",	"N",		VTypes::NoData,
		"int scaleid",
		"Clear all points from the specified colourscale" },
	{ "listscales",		"",		VTypes::NoData,
		"",
		"List details on all colourscales" },
	{ "removepoint",	"NN",		VTypes::NoData,
		"int scaleid, int pointid",
		"Remove the selected point from the specified colourscale" },
	{ "scaleinterpolate",	"NB",		VTypes::IntegerData,
		"int scaleid, bool interpolate",
		"Set whether colour is interpolated between points in the colourscale specified" },
	{ "scalename",		"Nc",		VTypes::StringData,
		"int scaleid [string name]",
		"Print (or set) the name of the colourscale specified" },
	{ "scalevisible",	"NB",		VTypes::NoData,
		"int scaleid, bool visible",
		"Set the visibility of the specified colourscale" },
	{ "setpoint",		"NNNNNNn",	VTypes::NoData,
		"int scaleid, int pointid, double value, double r, double g, double b, double a = 1.0",
		"Set an existing point on the specified colourscale" },
	{ "setpointcolour", 	"NNNNNn",	VTypes::NoData,
		"int scaleid, int pointid, double r, double g, double b, double a = 1.0",
		"Set the colour for an existing colourscale point" },
	{ "setpointvalue", 	"NNN",		VTypes::NoData,
		"int scaleid, int pointid, double value",
		"Set the value for an existing colourscale point" },

	// Disordered Builder Commands
	{ "disorder",		"N",		VTypes::NoData,
		"int nsteps",
		"Run the disordered builder" },
	{ "listcomponents",	"",		VTypes::NoData,
		"",
		"Print a list of the components requested in the disordered builder" },
	{ "nmols",		"N",		VTypes::NoData,
		"int n",
		"Set the number of molecules required for the component" },
	{ "regioncentre",	"NNN",		VTypes::NoData,
		"double x, double y, double z",
		"Set the region centre of the current model" },
	{ "regioncentrefrac",	"NNN",		VTypes::NoData,
		"double x, double y, double z",
		"Set the region centre of the current model (fractional coordinates)" },
	{ "regiongeometry",	"NNN",		VTypes::NoData,
		"double x, double y, double z",
		"Set the region geometry of the current model" },
	{ "regiongeometryfrac",	"NNN",		VTypes::NoData,
		"double x, double y, double z",
		"Set the region geometry of the current model (fractional coordinates)" },
	{ "regionoverlap",	"B",		VTypes::NoData,
		"bool allowoverlap",
		"Set the overlap flag of the current model" },
	{ "regionrotation",	"NN",		VTypes::NoData,
		"double rotx, double roty",
		"Set the x and y axis rotations for the current region" },
	{ "regionshape",	"C",		VTypes::NoData,
		"string shape",
		"Set the region shape of the current model" },
	{ "setregion",		"CNNNNNNb",	VTypes::NoData,
		"string shape, double cx, double cy, double cz, double x, double y, double z, bool allowoverlap = TRUE",
		"Set the shape, centre, size, and overlap flag of the region for the current model" },
	{ "setregionfrac",	"CNNNNNNb",	VTypes::NoData,
		"string shape, double cx, double cy, double cz, double x, double y, double z, bool allowoverlap = TRUE",
		"Set the shape, centre, size, and overlap flag of the region for the current model (fractional coordinates)" },
	{ "vdwscale",		"n",		VTypes::DoubleData,
		"[double scale]",
		"Retrieve (or set) the VDW scaling factor to use in the disordered builder" },

	// Edit commands
	{ "copy",		"",		VTypes::NoData,
		"",
		"Copy selected atoms" },
	{ "cut",		"",		VTypes::NoData,
		"",
		"Cut the selected atoms" },
	{ "delete",		"",		VTypes::NoData,
		"",
		"Delete selected atoms" },
	{ "paste",		"[nnn]",	VTypes::NoData,
		"double dx = 0.0, double dy = 0.0, double dz = 0.0",
		"Paste previously-cut or copied atoms to the model (with optional shift from original position" },
	{ "redo",		"",		VTypes::NoData,
		"",
		"Redo last change in current model" },
	{ "undo",		"",		VTypes::NoData,
		"",
		"Undo last change in current model" },

	// Energy commands
	{ "ecut",		"n",		VTypes::DoubleData,
		"[double dist]",
		"Return (or set) the electrostatic cutoff distance" },
	{ "elec",		"Cnnnn",	VTypes::NoData,
		"string type = none|coulomb|ewald|ewaldauto. [ double precision, | double alpha, int kx, int ky, int kz ]",
		"Set the style of electrostatic energy calculation" },
	{ "frameenergy",	"",		VTypes::DoubleData,
		"",
		"Calculate the energy of the current trajectory frame" },
	{ "modelenergy",	"",		VTypes::DoubleData,
		"",
		"Calculate the energy of the current model" },
	{ "printelec",		"",		VTypes::NoData,
		"",
		"Print the electrostatic pattern matrix of the last calculated energy" },
	{ "printewald",		"",		VTypes::NoData,
		"",
		"Print the Ewald decomposition of the last calculated energy" },
	{ "printinter",		"",		VTypes::NoData,
		"",
		"Print the total intermolecular pattern matrix of the last calculated energy" },
	{ "printintra",		"",		VTypes::NoData,
		"",
		"Print the total intramolecular pattern matrix of the last calculated energy" },
	{ "printenergy",	"",		VTypes::NoData,
		"",
		"Print a short description of the last calculated energy" },
	{ "printsummary",	"",		VTypes::NoData,
		"",
		"Print a one-line summary of the last calculated energy" },
	{ "printvdw",		"",		VTypes::NoData,
		"",
		"Print the VDW pattern matrix of the last calculated energy" },
	{ "vcut",		"n",		VTypes::DoubleData,
		"[double dist]",
		"Return (or set) the VDW cutoff distance" },

	// Flow control
	{ "break",		"",		VTypes::NoData,
		"",
		"Exit from the current for loop" },
	{ "continue",		"",		VTypes::NoData,
		"",
		"Skip to the next iteration of the current loop" },
	{ "dowhile",		"_",		VTypes::NoData,
		"",
		"Run the enclosed block or statement as many times as the supplied expression evaluates to TRUE" },
	{ "for",		"_",		VTypes::NoData,
		"initial expression; increment; termination condition",
		"" },
	{ "if",			"_",		VTypes::NoData,
		"",
		"Perform a conditional test between the supplied expressions (or variables or constants)" },
	{ "return",		"z",		VTypes::NoData,
		"value = <no value>",
		"Terminate execution of the current program/filter/function, optionally returning the value provided" },
	{ "while",		"_",		VTypes::NoData,
		"",
		"Run the enclosed block or statement as many times as <expression, evaluates to TRUE" },
	
	// Force commands
	{ "frameforces",	"",		VTypes::NoData,
		"",
		"Calculate forces for the current trajectory frame" },
	{ "modelforces",	"",		VTypes::NoData,
		"",
		"Calculate forces for the current model" },
	{ "printforces",	"",		VTypes::NoData,
		"",
		"Print calculated forces for the current model" },
	
	// Forcefield commands
	{ "angledef",		"CCCCNnnnnn",	VTypes::NoData,
		"string form, string type1, string type2, string type3, double data1, double data2 = 0.0 ...",
		"Add an angle definition to the current forcefield" },
	{ "bonddef",		"CCCNnnnnn",	VTypes::NoData,
		"string form, string type1, string type2, double data1, double data2 = 0.0 ...",
		"Add a bond definition to the current forcefield" },
	{ "clearmap",		"",		VTypes::NoData,
		"",
		"Clear manual import type mapping list" },
	{ "clearexportmap",	"",		VTypes::NoData,
		"",
		"Clear manual export type mapping list" },
	{ "clearexpression",	"",		VTypes::NoData,
		"",
		"Clear the current model's expression" },
	{ "createexpression",	"b",		VTypes::NoData,
		"[bool nointra = FALSE]",
		"Create a forcefield expression for the current model" },
	{ "currentff",		"f",		VTypes::ForcefieldData,
		"string|int|forcefield f = <none>",
		"Make the specified forcefield (or forcefield id) the current forcefield, or return current forcefield" },
	{ "defaultff",		"F",		VTypes::NoData,
		"string|int|forcefield ff",
		"Make named forcefield the default for occasions where no other is specified" },
	{ "equivalents",	"CC*",		VTypes::NoData,
		"string equivname, string type ...",
		"Define forcefield equivalents" },
	{ "exportmap",		"C*",		VTypes::NoData,
		"string 'typename=name ...' ...",
		"Add export typename mappings" },
	{ "ffmodel",		"c",		VTypes::NoData,
		"[string name]",
		"Associate current (or named) forcefield to current model" },
	{ "ffpattern",		"p",		VTypes::NoData,
		"[pattern|id|string p]", 
		"Associate current forcefield to current pattern" },
	{ "finaliseff",		"",		VTypes::NoData,
		"",
		"Finalise current forcefield" },
	{ "fixtype",		"Na",		VTypes::NoData,
		"int typeid, atom|id = 0",
		"Fix the atom type of the current selection, or specified atom" },
	{ "freetype",		"a",		VTypes::NoData,
		"atom|id = 0",
		"Free any previously-fixed atom type in the current selection, or for the specified atom" },
	{ "genconvert",		"N*",		VTypes::NoData,
		"int dataid ...",
		"Set energetic generator data to convert" },
	{ "generator",		"NNnnnnnnnnn",	VTypes::NoData,
		"int typeid, double data ...",
		"Set generator data for specified atom type" },
	{ "getff",		"C",		VTypes::ForcefieldData,
		"string name",
		"Return reference to named (loaded) forcefield" },
	{ "interdef",		"CNNNnnnnn",	VTypes::NoData,
		"string form, int typeid, double q, double data ...",
		"Add a new interatomic definition to the current forcefield" },
	{ "loadff",		"Cc",		VTypes::ForcefieldData,
		"string filename, string nickname = filename",
		"Load forcefield from file, renaming to new name if one was supplied" },
	{ "map",		"C*",		VTypes::NoData,
		"string 'name=element ...' ...",
		"Add typename mappings" },
	{ "newff",		"C",		VTypes::ForcefieldData,
		"string name",
		"Create a new, empty forcefield" },
	{ "printsetup",		"",		VTypes::NoData,
		"",
		"Print the current energy/force calculation setup" },
	{ "printtype",		"N",		VTypes::NoData,
		"int i",
		"Print the internal NETA description details of type ID 'i' in the current forcefield" },
	{ "recreateexpression",	"b",		VTypes::NoData,
		"[bool nointra = FALSE]",
		"Delete any existing expression, then create a forcefield expression for the current model" },
	{ "rules",		"C",		VTypes::NoData,
		"string rules",
		"Set rules set to use for parameter generation" },
	{ "saveexpression",	"CC",		VTypes::IntegerData,
		"string format, string filename",
		"Save the expression for the current model" },
	{ "torsiondef",		"CCCCCNnnnnn",	VTypes::NoData,
		"string form, string type1, string type2, string type3, string type4, double data1, double data2 = 0.0 ...",
		"Add a torsion definition to the current forcefield" },
	{ "typedef",		"NCCECc", VTypes::NoData,
		"int typeid, string name, string equiv, element el, string neta, string description = <empty>",
		"Add an atom type to the current forcefield" },
	{ "typemodel",		"",		VTypes::IntegerData,
		"",
		"Perform atom typing on the current model" },
	{ "typetest",		"NA",		VTypes::IntegerData,
		"int typeid, atom|int id",
		"Test atomtype score on atom id provided" },
	{ "units",		"C",		VTypes::NoData,
		"string unit",
		"Set energy unit of forcefield" },

	// Glyph commands
	{ "autoellipsoids",	"c*",		VTypes::NoData,
		"string option = <empty> ...",
		"Automatically add ellipsoids to the current atom selection" },
	{ "autopolyhedra",	"c*",		VTypes::NoData,
		"string option = <empty> ...",
		"Automatically add polyhedra to the current atom selection" },
	{ "glyphatomf",		"Na",		VTypes::NoData,
		"int n, atom|int id = 0",
		"Set current (or specified) atom's forces as n'th data in current glyph" },
	{ "glyphatomr",		"Na",		VTypes::NoData,
		"int n, atom|int id = 0",
		"Set current (or specified) atom's coordinates as n'th data in current glyph" },
	{ "glyphatomv",		"Na",		VTypes::NoData,
		"int n, atom|int id = 0",
		"Set current (or specified) atom's velocities data n'th in current glyph" },
	{ "glyphatomsf",	"Aaaa",		VTypes::NoData,
		"atom|int id1, atom|int id2 = 0, atom|int id3 = 0, atom|int id4 = 0",
		"Set all atom forces data in current glyph" },
	{ "glyphatomsr",	"Aaaa",		VTypes::NoData,
		"atom|int id1, atom|int id2 = 0, atom|int id3 = 0, atom|int id4 = 0",
		"Set all atom coordinates data in current glyph" },
	{ "glyphatomsv",	"Aaaa",		VTypes::NoData,
		"atom|int id1, atom|int id2 = 0, atom|int id3 = 0, atom|int id4 = 0",
		"Set all atom velocities data in current glyph" },
	{ "glyphcolour",	"NNNNn",	VTypes::NoData,
		"int n, double r, double g, double b, double a = 1.0",
		"Set colour data <n, in current glyph" },
	{ "glyphdata",		"NNnn",		VTypes::NoData,
		"int n, double x, double y = 0.0, double z = 0.0",
		"Set vector data <n, in current glyph" },
	{ "glyphsolid",		"B",		VTypes::NoData,
		"bool solid"
		"Set the glyph to be drawn in solid (true) or wireframe (false) modes (glyph-permitting)" },
	{ "glyphtext",		"C",		VTypes::NoData,
		"string text",
		"Set text data in current glyph" },
	{ "newglyph",		"Cc",		VTypes::GlyphData,
		"string style, string option ...",
		"Add a glyph with the specified style to the current model" },

	// Grid commands
	{ "addgridpoint",	"NNNN",		VTypes::NoData,
		"int ix, int iy, int iz, double value",
		"Set specific gridpoint value" },
	{ "addnextgridpoint",	"N",		VTypes::NoData,
		"double value",
		"Add next gridpoint value" },
	{ "currentgrid",	"g",		VTypes::GridData,
		"grid|int g = <none>",
		"Make the specified grid (or grid id) the current grid, or return current grid" },
	{ "finalisegrid",	"",		VTypes::NoData,
		"",
		"Finalise grid import" },
	{ "getgrid",		"N",		VTypes::GridData,
		"int id",
		"Return a reference to grid in current model with id specified" },
	{ "gridalpha",		"N",		VTypes::DoubleData,
		"double alpha",
		"Set the alpha value of the surface (when not using a colourscale)" },
	{ "gridaxes",		"NNNNNNNNN",	VTypes::NoData,
		"double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz",
		"Set axis system for the current grid" },
	{ "gridcolour",		"NNNn",		VTypes::NoData,
		"double r, double g, double b, double a = 1.0",
		"Set the (positive) colour of the surface (when not using a colourscale)" },
	{ "gridcolournegative",	"NNNn",		VTypes::NoData,
		"double r, double g, double b, double a = 1.0",
		"Set the negative colour of the surface (when not using a colourscale)" },
	{ "gridcolourscale",	"N",		VTypes::NoData,
		"int scaleid",
		"Links the surface to the specified colour scale (or zero to return to internal colour)" },
	{ "gridcubic",		"N",		VTypes::NoData,
		"double l",
		"Setup a cubic axis system for the current grid" },
	{ "gridcutoff",		"N",		VTypes::NoData,
		"double cutoff",
		"Set the cutoff for the current grid" },
	{ "gridlooporder",	"S",		VTypes::NoData,
		"string looporder",
		"Set the loop ordering (e.g. 'xyz', 'zyx', '213') to use in 'addnextgridpoint'" },
	{ "gridorigin",		"NNN",		VTypes::NoData,
		"double x, double y, double z",
		"Set the origin of the axes system for the current grid" },
	{ "gridortho",		"NNN",		VTypes::NoData,
		"double a, double b, double c",
		"Setup an orthorhombic axis system for the current grid" },
	{ "gridsize",		"NNN",		VTypes::NoData,
		"int nx, int ny, int nz",
		"Set the number of points along each axis for the current grid" },
	{ "gridstyle",		"C",		VTypes::NoData,
		"string style",
		"Set the drawing style of the current grid" },
	{ "gridsymmetric",	"B",		VTypes::IntegerData,
		"bool symm",
		"Set whether the isodata is symmetric about zero (i.e. whether to draw both halves)" },
	{ "gridusez",		"B",		VTypes::IntegerData,
		"bool usez",
		"Whether a 2D surface uses the vertex data value as its z (height) data" },
	{ "gridvisible",	"B",		VTypes::IntegerData,
		"bool visible",
		"Set (or return) whether the current grid is visible" },
	{ "loadgrid",		"C",		VTypes::GridData,
		"string filename",
		"Load grid data" },
	{ "newgrid",		"C",		VTypes::GridData,
		"string title",
		"Create new grid data" },

	// Image commands
	{ "savebitmap",		"CCnnn",	VTypes::NoData,
		"string format, string filename, int width = -1, int height = -1, int quality = -1",
		"Save the current model view as a bitmap image: formats available are bmp, jpg, png, ppm, xbm, and xpm" },
	{ "savevector",		"CC",		VTypes::NoData,
		"string format, string filename",
		"Save the current model view as a vector image: formats available are ps, eps, tex, pdf, svg, and pgf" },
	
	// Labeling commands
	{ "clearlabels",	"",		VTypes::NoData,
		"",
		"Remove all atom labels in the current model" },
	{ "label",		"Ca",		VTypes::NoData,
		"string label, atom|int id = 0",
		"Add labels to the current atom selection (or specified atom)" },
	{ "removelabel",	"Ca",		VTypes::NoData,
		"string label, atom|int id = 0",
		"Remove labels from the current atom selection (or specified atom)" },
	{ "removelabels",	"a",		VTypes::NoData,
		"atom|int id = 0",
		"Remove all labels from the current atom selection (or specified atom)" },

	// Math Commands.
	{ "abs",		"N",		VTypes::DoubleData,
		"double number",
		"Return absolute (i.e. positive) of value" },
	{ "acos",		"N",		VTypes::DoubleData,
		"double cosx",
		"Return inverse cosine (in degrees) of supplied argument" },
	{ "asin",		"N",		VTypes::DoubleData,
		"double sinx",
		"Return inverse sine (in degrees) of supplied argument" },
	{ "atan",		"N",		VTypes::DoubleData,
		"double tanx",
		"Return inverse tangent (in degrees) of supplied argument" },
	{ "cos",		"N",		VTypes::DoubleData,
		"double degrees",
		"Return cosine of specified angle (supplied in degrees)" },
	{ "dotproduct",		"UU",		VTypes::DoubleData,
		"vector u, vector v",
		"Calculate dot product of the two supplied vectors" },
	{ "exp",		"N",		VTypes::DoubleData,
		"double value",
		"Return exponential of the argument" },
	{ "ln",			"N",		VTypes::DoubleData,
		"double value",
		"Return natural (base-e) logarithm" },
	{ "log",		"N",		VTypes::DoubleData,
		"double value",
		"Return base-10 logarithm" },
	{ "nint",		"N",		VTypes::IntegerData,
		"double number",
		"Return nearest integer to supplied real value" },
	{ "normalise",		"U",		VTypes::DoubleData,
		"vector v",
		"Normalise the values of the 3-vector supplied" },
	{ "sin",		"N",		VTypes::DoubleData,
		"double degrees",
		"Return sine of specified angle (supplied in degrees)" },
	{ "sqrt",		"N",		VTypes::DoubleData,
		"double number",
		"Return square root of number" },
	{ "tan",		"N",		VTypes::DoubleData,
		"double degrees",
		"Return tangent of specified angle (supplied in degrees)" },

	// MC commands
	{ "mcaccept",		"CN",		VTypes::NoData,
		"string movetype, double energy",
		"Set Monte Carlo move type acceptance energies" },
	{ "mcallow",		"CB",		VTypes::NoData,
		"string movetype, bool allowmove",
		"Restrict or allow Monte Carlo move types" },
	{ "mcmaxstep",		"CN",		VTypes::NoData,
		"string movetype, double step",
		"Set maximum step sizes for Monte Carlo move types" },
	{ "mcntrials",		"CN",		VTypes::NoData,
		"string movetype, double ntrials",
		"Set trial numbers for Monte Carlo move types" },
	{ "printmc",		"",		VTypes::NoData,
		"",
		"Print current Monte Carlo parameters" },
	
	// Measurements
	{ "angle",		"AAA",		VTypes::DoubleData,
		"atom|int id1, atom|int id2, atom|int id3", 
		"Measure angle between atoms specified" },
	{ "angles",		"",		VTypes::NoData,
		"",
		"Measure bond angles between atoms in current selection" },
	{ "clearmeasurements",	"",		VTypes::NoData,
		"",
		"Clear all measurements in the current model" },
	{ "distance",		"AA",		VTypes::DoubleData,
		"atom|int id1, atom|int id2",
		"Measure distance between atoms specified" },
	{ "distances",		"",		VTypes::NoData,
		"",
		"Measure bond distances between atoms in current selection" },
	{ "listmeasurements",	"",		VTypes::NoData,
		"",
		"List all measurements in the current model" },
	{ "measure",		"AAaa",		VTypes::DoubleData,
		"atom|int id1, atom|int id2, atom|int id3 = 0, atom|int id4 = 0", 
		"Make a measurement between the specified atoms" },
	{ "torsion",		"AAAA",		VTypes::DoubleData,
		"atom|int id1, atom|int id2, atom|int id3 , atom|int id4", 
		"Measure torsion angle between atoms specified" },
	{ "torsions",		"",		VTypes::NoData,
		"",
		"Measure torsion angles between atoms in current selection" },

	// Messaging
	{ "error",		"Cz*",		VTypes::NoData,
		"string format ...",
		"Raise an error message (causes exit of current command list) (C printf-style)" },
	{ "printf",		"Cz*",		VTypes::NoData,
		"string format ...",
		"Print a message (C printf-style)" },
	{ "verbose",		"Cz*",		VTypes::NoData,
		"string format ...",
		"Print a message when verbose output is enabled (C printf-style)" },
	
	// Minimisation commands
	{ "cgminimise",		"n",		VTypes::NoData,
		"int maxsteps = 100",
		"Run a conjugate gradient minimiser on the current model" },
	{ "converge",		"NN",		VTypes::NoData,
		"double energy, double forces",
		"Set energy and RMS force convergence limits for minimisation algorithms" },
	{ "linetol",		"N",		VTypes::NoData,
		"double tolerance",
		"Set tolerance of line minimiser" },
	{ "mcminimise",		"n",		VTypes::NoData,
		"int maxsteps = 100",
		"Run Monte Carlo minimiser on the current model" },
	{ "sdminimise",		"n",		VTypes::NoData,
		"int maxsteps = 100",
		"Run steepest descent minimiser on the current model" },
	{ "simplexminimise",	"",		VTypes::NoData,
		"",
		"Run the Simplex minimiser on the current model" },
	
	// Model commands
	{ "createatoms",	"",		VTypes::NoData,
		"",
		"Create enough atoms in the current trajectory frame to match the parent model" },
	{ "currentmodel",	"m",		VTypes::ModelData,
		"string|int|model m = <no value>",
		"Return reference to the current model, or set the current model" },
	{ "finalisemodel",	"",		VTypes::NoData,
		"",
		"Finalise the current model" },
	{ "firstmodel",		"",		VTypes::ModelData,
		"",
		"Make the first loaded/created model current" },
	{ "getmodel",		"M",		VTypes::ModelData,
		"string|int|model m",
		"Find the named (loaded) model, and return a reference to it" },
	{ "info",		"",		VTypes::NoData,
		"",
		"Print data on the current model" },
	{ "lastmodel",		"",		VTypes::ModelData,
		"",
		"Make the last loaded/created model current" },
	{ "listmodels",		"",		VTypes::NoData,
		"",
		"List the currently-loaded models" },
	{ "loadmodel",		"Cc",		VTypes::IntegerData,
		"string filename [string name]",
		"Load a model from file" },
	{ "loginfo",		"",		VTypes::NoData,
		"",
		"Print log information for model" },
	{ "modeltemplate",	"",		VTypes::NoData,
		"",
		"Template the atoms in the current trajectory frame, matching the parent model" },
	{ "newmodel",		"C",		VTypes::ModelData,
		"string name",
		"Create a new model" },
	{ "nextmodel",		"",		VTypes::ModelData,
		"",
		"Skip to the next loaded model" },
	{ "prevmodel",		"",		VTypes::ModelData,
		"",
		"Skip to the previous loaded model" },
	{ "savemodel",		"CC",		VTypes::IntegerData,
		"string format, string filename",
		"Save the current model in the specified model format" },
	{ "saveselection",	"CC",		VTypes::IntegerData,
		"string format, string filename",
		"Save the current selection in the current model (including cell, if any) in the specified model format" },
	{ "setname",		"C",		VTypes::NoData,
		"string name",
		"Set the name of the current model" },

	// Pattern commands
	{ "clearpatterns",	"",		VTypes::NoData,
		"",
		"Remove all pattern definitions from the current model" },
	{ "createpatterns",	"",		VTypes::NoData,
		"",
		"Automatically determine pattern definitions for the current model" },
	{ "currentpattern",	"p",		VTypes::PatternData,
		"string|int|pattern p = <none>",
		"Make the specified pattern (or pattern id) the current pattern, or return current pattern" },
	{ "fixpattern",		"B",		VTypes::NoData,
		"bool fixed",
		"Set whether atoms in the current pattern are fixed in minimisations" },
	{ "getpattern",		"P",		VTypes::PatternData,
		"string|int|pattern p",
		"Return a reference to the specified pattern" },
	{ "listpatterns",	"",		VTypes::NoData,
		"",
		"Print the pattern definition for the current model" },
	{ "newpattern",		"CNN",		VTypes::PatternData,
		"string name, int nmolecules, int natoms",
		"Add a pattern definition 'node' to the current model" },

	// Read / Write Commands
	{ "addreadoption",	"C",		VTypes::NoData,
		"string option",
		"Add a read option: usequotes, skipblanks, stripbrackets" },
	{ "eof",		"",		VTypes::IntegerData,
		"",
		"Return whether the end of the file has been reached (or only whitespace remains)" },
	{ "filterfilename",	"",		VTypes::StringData,
		"",
		"Returns the name of the file that the current filter is reading from / writing to" },
	{ "find",		"C^c",		VTypes::IntegerData,
		"string source, string var = <none>",
		"Search for a string in the input file (placing matching line in optional variable)" },
	{ "getline",		"^C",		VTypes::IntegerData,
		"string var",
		"Read the next line from the file, placing in variable supplied, and returning read success" },
	{ "nextarg",		"^Z",		VTypes::IntegerData,
		"",
		"Read the next whitespace-delimited argument from the current file" },
	{ "peekchar",		"",		VTypes::StringData,
		"", 
		"Peek the next character from the current input file, and return it as a string" },
	{ "peekchari",		"",		VTypes::IntegerData,
		"", 
		"Peek the next character from the current input file, and return its ASCII code" },
	{ "readchars",		"Nb",		VTypes::StringData,
		"int nchars, bool skipeol = TRUE",
		"Read a number of characters from the input file" },
	{ "readdouble",		"n",		VTypes::DoubleData,
		"int nbytes = <sizeof(double)>",
		"Read a floating point value from the (binary) input file" },
	{ "readdoublearray",	"&DN",		VTypes::IntegerData,
		"double arrayvar, int nvalues",
		"Read floating point values from the (binary) input file, placing in the array provided" },
	{ "readint",		"n",		VTypes::IntegerData,
		"int nbytes = <sizeof(int)>",
		"Read an integer value from the (binary) input file" },
	{ "readintarray",	"&IN",		VTypes::IntegerData,
		"int arrayvar, int nvalues",
		"Read integer values from the (binary) input file, placing in the array provided" },
	{ "readline",		"^Z*",		VTypes::IntegerData,
		"string|double|int var ...",
		"Read a line from the input file, and split into supplied variables according to delimiting whitespace" },
	{ "readlinef",		"C^z*",		VTypes::IntegerData,
		"string format ...",
		"Read a line from the input file, and parse into supplied variables using format string" },
	{ "readnext",		"^Z",		VTypes::IntegerData,
		"string|int|double var",
		"Read the next delimited item from the last line read with 'getline' and place in the variable supplied" },
	{ "readvar",		"C^z*",		VTypes::IntegerData,
		"Parse delimited arguments from a character variable" },
	{ "readvarf",		"CC^z*",	VTypes::IntegerData,
		"string source, string format, string|int|double var ...",
		"Parse a character variable according to the supplied format" },
	{ "removereadoption",	"C",		VTypes::NoData,
		"string option",
		"Remove a read option" },
	{ "rewind",		"",		VTypes::NoData,
		"",
		"Rewind to the start of the input file" },
	{ "skipchars",		"N",		VTypes::NoData,
		"int nchars",
		"Skip a number of characters in the input file" },
	{ "skipline",		"n",		VTypes::NoData,
		"int nlines = 1",
		"Skip a number of lines in the input file" },
	{ "writeline",		"Z*",		VTypes::NoData,
		"string|double|int data ...",
		"Write an formatted line to the output file, with data items separated by spaces" },
	{ "writelinef",		"Cz*",		VTypes::NoData,
		"string format, string|double|int data ...",
		"Write a formatted line to the output file" },
	{ "writevar",		"^Cz*",		VTypes::NoData,
		"string destvar, string|double|int data ...",
		"Write a delimited series of arguments to the supplied character variable" },
	{ "writevarf",		"^CCz*",	VTypes::NoData,
		"string destvar, string format, string|double|int data ...",
		"Write a formatted line to the supplied character variable" },

	// Script commands
	{ "listscripts",	"",		VTypes::NoData,
		"",
		"List available scripts" },
	{ "loadscript",		"Cc",		VTypes::NoData,
		"<filename, [nickname]",
		"Load script from file" },
	{ "runscript",		"S",		VTypes::NoData,
		"string name",
		"Execute the named script" },

	// Selection commands
	{ "deselect",		"Z*",		VTypes::IntegerData,
		"string|int|element atom(s) ...",
		"Deselect specific atoms / ranges in the current model" },
	{ "deselectf",		"Cz*",		VTypes::IntegerData,
		"string format ...",
		"Deselect specific atoms / ranges in the current model using a formatted string" },
	{ "deselecttype",	"EC",		VTypes::IntegerData,
		"element el, string neta",
		"Deselect all atoms that match the provided atomtype description" },
	{ "expand",		"n",		VTypes::IntegerData,
		"int nsteps = 1",
		"Expands the current atom selection along bonds" },
	{ "invert",		"",		VTypes::IntegerData,
		"",
		"Invert the current selection" },
	{ "select",		"Z*",		VTypes::IntegerData,
		"string|int|element atom(s) ...",
		"Select specific atoms / ranges in the current model" },
	{ "selectall",		"",		VTypes::NoData,
		"",
		"Select all atoms in the current model" },
	{ "selectfftype",	"C",		VTypes::IntegerData,
		"string typename",
		"Select all atoms of a specific forcefield type" },
	{ "selectf",		"Cz*",		VTypes::IntegerData,
		"string format ...",
		"Select specific atoms / ranges in the current model using a formatted string" },
	{ "selectinsidecell",	"b",		VTypes::IntegerData,
		"bool usemoleculecog = FALSE",
		"Select all atoms (or molecule centres) which are inside the current unit cell" },
	{ "selectioncog",	"",		VTypes::VectorData,
		"",
		"Return centre of geometry of current selection" },
	{ "selectioncom",	"",		VTypes::VectorData,
		"",
		"Return centre of mass of current selection" },
	{ "selectline",		"NNNNNNN",	VTypes::IntegerData,
		"double lx, double ly, double lz, double x, double y, double z, double dr",
		"Select all atoms within a distance dr, from a line <lxyz>, containing a point <xyz>" },
	{ "selectmiller",	"NNNn",		VTypes::NoData,
		"int h, int k, int l, bool inside = FALSE",
		"Select all atoms that would be removed if a cleave of the supplied Miller plane `was performed" },
	{ "selectmolecule",	"A",		VTypes::IntegerData,
		"atom|int target",
		"Select the whole bound fragment/molecule to which the target atom belongs" },
	{ "selectnone",		"",		VTypes::NoData,
		"",
		"Deselect all atoms in the current model" },
	{ "selectoverlaps",	"n",		VTypes::IntegerData,
		"double tolerance = 0.2",
		"Select all atoms which are within a given distance of each other" },
	{ "selectoutsidecell",	"b",		VTypes::IntegerData,
		"bool usemoleculecog = FALSE",
		"Select all atoms (or molecule centres) which are outside the current unit cell" },
	{ "selectpattern",	"p",		VTypes::IntegerData,
		"string|int|pattern p",
		"Select all atoms in the current (or named) pattern" },
	{ "selectradial",	"AN",		VTypes::IntegerData,
		"atom|int target, double radius",
		"Select all atoms less than some distance from a central atom" },
	{ "selecttype",		"EC",		VTypes::IntegerData,
		"element el, string neta",
		"Select all atoms that match the provided atomtype description (returning the number matched)" },
	
	// Site commands
	{ "getsite",		"C",		VTypes::NoData,
		"string name",
		"Select the defined site and make it current" },
	{ "listsites",		"",		VTypes::NoData,
		"",
		"Print all sites defined for the current model" },
	{ "newsite",		"CCc",		VTypes::NoData,
		"string name, string pattern, string atomlist = <empty>",
		"Adds a new site definition to the current model" },
	{ "siteaxes",		"CC",		VTypes::NoData,
		"string atomlist, string atomlist",
		"Set the axis definitions for the current site" },

	// String Commands
	{ "afterstr",		"CC",		VTypes::StringData,
		"string source, string search",
		"Return the part of the source string after the first occurrence of the search string" },
	{ "atof",		"C",		VTypes::DoubleData,
		"string s",
		"Convert supplied string to floating point number" },
	{ "atoi",		"C",		VTypes::IntegerData,
		"string s",
		"Convert supplied string to integer number" },
	{ "beforestr",		"CC",		VTypes::StringData,
		"string source, string search",
		"Return the part of the string before the first occurrence of the search string" },
	{ "contains",		"CC",		VTypes::IntegerData,
		"string source, string search",
		"Return the number of times the search string occurs in the source string" },
	{ "ftoa",		"N",		VTypes::StringData,
		"double d",
		"Convert supplied real value to a string" },
	{ "itoa",		"N",		VTypes::StringData,
		"int n",
		"Convert supplied integer to a string" },
	{ "replacechars",	"CCC",		VTypes::StringData,
		"string source, string searchchars, string replacechar",
		"Replace all occurrences of the supplied characters in the supplied variable with the supplied character" },
	{ "replacestr",		"CCC",		VTypes::StringData,
		"string source, string searchstr, string replacestr",
		"Replace all occurrences of 'searchstr' in the supplied string with 'replacestr'" },
	{ "removestr",		"CC",		VTypes::StringData,
		"string source, string searchstr",
		"Remove all occurrences of 'searchstr' from the supplied string" },
	{ "stripchars",		"CC",		VTypes::StringData,
		"string source, string searchchars",
		"Strip all occurrences of the supplied characters from the supplied string" },
	{ "toa",		"Cz*",		VTypes::StringData,
		"string format ...",
		"Return a string formatted in the C printf style)" },

	// System commands
	{ "debug",		"C",		VTypes::NoData,
		"string mode",
		"Toggle debugging for the specified mode" },
	{ "getenv",		"C",		VTypes::StringData,
		"string varname",
		"Retrieve the named environment variable" },
	{ "getenvf",		"C",		VTypes::DoubleData,
		"string varname",
		"Retrieve the named environment variable, converting it to a floating-point value" },
	{ "getenvi",		"C",		VTypes::IntegerData,
		"string varname",
		"Retrieve the named environment variable, converting it to an integer value" },
	{ "gui",		"",		VTypes::NoData,
		"",
		"Start the GUI (if it is not already active)" },
	{ "_help",		"N",		VTypes::NoData,
		"int commandid",
		"(Internal) Provide short help on the command ID supplied" },
	{ "searchcommands",	"C",		VTypes::NoData,
		"string cmd",
		"Search all available commands for the string specified" },
	{ "seed",		"N",		VTypes::NoData,
		"int seed",
		"Set the random seed" },
	{ "quit",		"",		VTypes::NoData,
		"",
		"Exit the program" },
	{ "version",		"",		VTypes::NoData,
		"",
		"Print program version information" },

	// Trajectory commands
	{ "addframe",		"c",		VTypes::ModelData,
		"string name = <empty>",
		"Add a new trajectory frame to the current model (which becomes the the current model)" },
	{ "cleartrajectory",	"",		VTypes::NoData,
		"",
		"Clear any trajectory data in the current model" },
	{ "finaliseframe",	"",		VTypes::NoData,
		"",
		"Finalise the current trajectory frame" },
	{ "firstframe",		"",		VTypes::NoData,
		"",
		"Go to the first frame in the current trajectory" },
	{ "lastframe",		"",		VTypes::NoData,
		"",
		"Go to the last frame in the current trajectory" },
	{ "loadtrajectory",	"C",		VTypes::IntegerData,
		"string filename",
		"Load the specified trajectory and associate it to the current model" },
	{ "nextframe",		"",		VTypes::NoData,
		"",
		"Go to the next frame in the current trajectory" },
	{ "prevframe",		"",		VTypes::NoData,
		"",
		"Go to the previous frame in the current trajectory" },
	{ "seekframe",		"N",		VTypes::NoData,
		"int frameno",
		"Jump to the specified frame in the current trajectory" },
	
	// Transformation commands
	{ "axisrotate",		"NNNNnnn|AANnnn",	VTypes::NoData,
		"double ax, double ay, double az, double theta, double ox = 0.0, double oy = 0.0, double oz = 0.0  |  atom|int i, atom|int j, double theta, double ox = 0.0, double oy = 0.0, double oz = 0.0",
		"Rotate the current selection about a defined axis and origin" },
	{ "centre",		"NNN[bbb]",		VTypes::NoData,
		"double x, double y, double z, bool lockx = FALSE, bool locky = FALSE, bool lockz = FALSE",
		"Centre the atom selection of the current model at the specified coordinates" },
	{ "matrixconvert",	"NNNNNNNNNNNNnnnnnnnnn",VTypes::NoData,
		"int i_sx, int j_sx, int i_sy, int j_sy, int i_sz, int j_sz, int i_dx, int j_dx, int i_dy, int j_dy, int i_dz, int j_dz, double ox = 0.0, double oy = 0.0, double oz = 0.0  |  double sax, double say, double saz, double sbx, double sby, double sbz, double scx, double scy, double scz, double dax, double day, double daz, double dbx, double dby, double dbz, double dcx, double dcy, double dcz, double ox = 0.0, double oy = 0.0, double oz = 0.0",
		"Transform selected atoms in reference frame specified to destination frame specified" },
	{ "matrixtransform",	"NNNNNNNNNnnn",	VTypes::NoData,
		"double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double ox = 0.0, double oy = 0.0, double oz = 0.0",
		"Transform selected atoms by the matrix supplied" },
	{ "mirror",		"C",		VTypes::NoData,
		"string axis",
		"Mirror the atom selection of the current model about its geometric centre in the specified axis" },
	{ "reorient",		"AAAAAANNNNNNNNNnnn",	VTypes::NoData,
		"atom|int i_sx, atom|int j_sx, atom|int i_sy, atom|int j_sy, atom|int i_sz, atom|int j_sz, double dax, double day, double daz, double dbx, double dby, double dbz, double dcx, double dcy, double dcz, double ox = 0.0, double oy = 0.0, double oz = 0.0",
		"Rotate current selection from axis system defined by supplied atoms into specified axis system" },
	{ "translate",		"NNN",		VTypes::NoData,
		"double dx, double dy, double dz",
		"Translate the atom selection of the current model" },
	{ "translateatom",	"NNN",		VTypes::NoData,
		"double dx, double dy, double dz",
		"Translate the current atom" },
	{ "translatecell",	"NNN",		VTypes::NoData,
		"double dx, double dy, double dz",
		"Translate the current selection along the cell axes by the fractional axes specified" },
	{ "translateworld",	"NNN",		VTypes::NoData,
		"double dx, double dy, double dz",
		"Translate the current selection in world (view) coordinates" },

	// View
	{ "axisrotateview",	"NNNN",		VTypes::NoData,
		"double ax, double ay, double az, double angle",
		"Rotate the current view about the specified axis (going through the origin)" },
	{ "getview",		"",		VTypes::NoData,
		"",
		"Print the rotation matrix, camera position, and camera z-rotation for the current model" },
	{ "orthographic",	"",		VTypes::NoData,
		"",
		"Render in an orthographic projection" },
	{ "perspective",	"n",		VTypes::NoData,
		"[double fov]",
		"Render in a perspective projection" },
	{ "resetview",		"",		VTypes::NoData,
		"",
		"Reset the camera and rotation for the current model" },
	{ "rotateview",		"NN",		VTypes::NoData,
		"double x, double y",
		"Rotate the current model about the x and y axes by the specified amounts" },
	{ "setview",		"NNNNNNNNNNNNn",VTypes::NoData,
		"double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double camx, double camyu, double camz [double zrot]",
		"Set the rotation matrix, camera position, and camera z-rotation for the current model" },
	{ "speedtest",		"n",		VTypes::NoData,
		"int nrenders = 100",
		"Perform a crude timing of updates to the model display" },
	{ "translateview",	"NNN",		VTypes::NoData,
		"double dx, double dy, double dz",
		"Translate the camera for the current model" },
	{ "viewalong",		"NNN",		VTypes::NoData,
		"double x, double y, double z",
		"Set the rotation for the current model so the view is along the specified vector" },
	{ "viewalongcell",	"NNN",		VTypes::NoData,
		"double x, double y, double z",
		"Set the rotation for the current model so the view is along the specified cell vector" },
	{ "zoomview",		"N",		VTypes::NoData,
		"double dz",
		"Zoom in/out the camera - equivalent to 'translateview 0 0 dz'" },
	{ "zrotateview",	"N",		VTypes::NoData,
		"double dr",
		"Rotate the model in the plane of the screen" }
};

// Return enumerated command from string
Command::Function Command::command(const char *s)
{
	int result;
	for (result = Command::NoFunction; result < Command::nCommands; result++) if (strcmp(data[result].keyword,s) == 0) break;
	return (Command::Function) result;
}

// Constructor
Command::Command()
{
	// Create pointer list
	initPointers();
}

// Constructor
Command::~Command()
{
}

// Return whether command accepts any arguments
bool CommandData::hasArguments()
{
	return (!(arguments[0] == '\0'));
}

// Execute command
bool Command::call(Command::Function cf, CommandNode *c, ReturnValue &rv)
{
	msg.print(Messenger::Commands, "Calling command '%s' (node is %p)...\n", data[cf].keyword, c);
	return (this->pointers_[cf])(c, aten.current, rv);
}

