      MODULE addfck_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  14:15:03  03/10/06  
      SUBROUTINE addfck (p) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(double), dimension(*), intent(in) :: p

      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
