      MODULE brlzon_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:02  03/09/06  
      SUBROUTINE brlzon (FMATRX, N3, MONO3, STEP, MODE) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: FMATRX 
      real(double), intent(in) :: step
      INTEGER, INTENT(IN) :: MODE , n3, mono3
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
