      MODULE densit_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:06  03/09/06  
      SUBROUTINE densit (C, MDIM, NORBS, NDUBL, NSINGL, FRACT, P, MODE) 
      USE vast_kind_param,ONLY: DOUBLE       
      INTEGER, INTENT(IN) :: MDIM, mode
      INTEGER, INTENT(IN) :: NORBS 
      INTEGER, INTENT(IN) :: NDUBL 
      INTEGER, INTENT(INOUT) :: NSINGL 
      REAL(DOUBLE), INTENT(IN) :: FRACT 
      REAL(DOUBLE), DIMENSION((NORBS*(NORBS + 1))/2), INTENT(INOUT) :: P 
      REAL(DOUBLE), DIMENSION(MDIM,MDIM), INTENT(IN) :: C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
