      MODULE dfockd_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE dfockd (F, W, NATI) 
      USE vast_kind_param,ONLY: DOUBLE 
      use molkst_C, only : lm6
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: F 
      real(DOUBLE), DIMENSION(LM6,45), INTENT(IN) :: W       
      integer, INTENT(IN) :: NATI 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
