      MODULE ffreq2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE ffreq2 (F, PTOT, W, WD) 
      USE vast_kind_param,ONLY: DOUBLE 
      use molkst_C, only : lm6, norbs
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(INOUT) :: F 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: PTOT 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: W 
      real(DOUBLE), DIMENSION(LM6,LM6), INTENT(IN) :: WD 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
