      MODULE formd_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:12:16  03/10/06  
      SUBROUTINE formd (EIGVAL, FX, NVAR, DMAX, OSMIN, TS, LORJK, RRSCAL, DONR&
        , U) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: EIGVAL 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: FX 
      integer, INTENT(IN) :: NVAR 
      real(DOUBLE), INTENT(IN) :: DMAX 
      real(DOUBLE) :: OSMIN 
      logical, INTENT(IN) :: TS 
      logical, INTENT(IN) :: LORJK 
      logical, INTENT(IN) :: RRSCAL 
      logical, INTENT(IN) :: DONR 
      real(DOUBLE), DIMENSION(NVAR,NVAR), INTENT(IN) :: U 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
