      MODULE openda_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE openda (IREST) 
      integer, INTENT(IN) :: IREST 
!VAST.../IODAF/ IDAF(OUT), IRECLN(OUT), IRECST(OUT), IFILEN(INOUT)
!VAST.../IODAF/ IODA(INOUT)
!VAST.../JOBNAM/ JOBNAM(IN)
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
