/*
// Mini CIF Dictionary
*/
enum cifdic { CD_OTHER, CD_LOOP, CD_NAME,
	CD_CELLA, CD_CELLB, CD_CELLC,
	CD_CELLALPHA, CD_CELLBETA, CD_CELLGAMMA, 
	CD_ELEMENT, CD_FRACX, CD_FRACY, CD_FRACZ,
	CD_SYMOPERATOR, CD_SYMEQUIVPOS,
	CD_NITEMS };
