#!/bin/bash

# Create the 'icons.cpp' and 'icons.h' files that create and give us access to the pixbufs
echo "Creating icon sources:"

echo "#include \"gui-gtk/icons.h\"" > icons.cpp

rm iconlist.tmp

for icondir in `ls -d _*`; 
do
  echo "...Entering into directory $icondir..."
  cd $icondir
  for icon in `ls *.png`;
  do
    TARGET=icon_${icon/png/xpm}
    echo "      Generating "$TARGET
    # Convert PNG to XPM format
    convert $icon $TARGET
    # Set background color (gray100) to transparent (none)
    sed "s/gray100/none/" $TARGET > tmpicon
    sed "s/static/const/" tmpicon > $TARGET
    rm tmpicon
    # Add this icon onto the temp list of icons ready for incredible gawk action later on....
    echo ${TARGET%.xpm} >> ../iconlist.tmp
  done
  # Concatenate all xpm files in this dir into one file
  FILE=${icondir/_/}.xpms
  cat *.xpm > ../../$FILE
  # Return to parent directory
  cd ../
  # Add this master xpm file to the include list of 'icons.cpp'
  echo "#include \"gui-gtk/$FILE\"" >> icons.cpp
done

# Finalise the cpp and h files
# icons.cpp
echo "" >> icons.cpp
echo "pixbuf_data pixbufs;" >> icons.cpp
echo "" >> icons.cpp
echo "// *** Constructor" >> icons.cpp
echo "pixbuf_data::pixbuf_data()" >> icons.cpp
echo "{" >> icons.cpp
echo "	// Create pixbufs from xpm image data" >> icons.cpp
echo "	g_type_init();" >> icons.cpp
for a in `cat iconlist.tmp`;
do
  echo -e "\tpixbufs.${a/icon_/xpm_} = gdk_pixbuf_new_from_xpm_data(${a});" >> icons.cpp
done
echo "}" >> icons.cpp
echo "" >> icons.cpp
echo "pixbuf_data::~pixbuf_data()" >> icons.cpp
echo "{" >> icons.cpp
echo "	// Free the pixbuf memory" >> icons.cpp
for a in `cat iconlist.tmp`;
do
  echo -e "\tg_object_unref(${a/icon_/xpm_});" >> icons.cpp
done
echo "}" >> icons.cpp

# icons.h
echo "#ifndef _ICONS_H" > icons.h
echo "#define _ICONS_H" >> icons.h
echo "" >> icons.h
echo "#include <gdk/gdkpixbuf.h>" >> icons.h
echo "#include \"classes/atom.h\"" >> icons.h
echo "" >> icons.h
echo "typedef struct pixbuf_data" >> icons.h
echo "{" >> icons.h
for a in `cat iconlist.tmp`;
do
  echo -e "\tGdkPixbuf *${a/icon_/xpm_};" >> icons.h
done
echo "	// Functions" >> icons.h
echo "	pixbuf_data();" >> icons.h
echo "	~pixbuf_data();" >> icons.h
echo "};" >> icons.h
echo "" >> icons.h
echo "extern pixbuf_data pixbufs;" >> icons.h
echo "" >> icons.h
echo "#endif" >> icons.h

# Need to do a special operation on the header and source files to make an array for xpm_ds...
sed "s/xpm_ds_scaled/xpm_ds[DS_SCALED]/" icons.cpp > tempfile
sed "s/xpm_ds_stick/xpm_ds[DS_STICK]/" tempfile > icons.cpp
sed "s/xpm_ds_tube/xpm_ds[DS_TUBE]/" icons.cpp > tempfile
sed "s/xpm_ds_sphere/xpm_ds[DS_SPHERE]/" tempfile > icons.cpp
sed "s/xpm_ds_individual/xpm_ds[DS_INDIVIDUAL]/" icons.cpp > tempfile
mv tempfile ../icons.cpp
rm icons.cpp

sed "s/xpm_ds_scaled/xpm_ds[DS_NITEMS]/" icons.h > tempfile
grep -v "xpm_ds_" tempfile > ../icons.h
rm tempfile icons.h iconlist.tmp
